### ISSUE TITLE
Benzoimidazole

### ISSUE THREAD

**Issue by alintheopen** [OpenSourceMalaria/OSM_To_Do_List#11]
![github7](https://f.cloud.github.com/assets/2626599/486894/2bed8c20-b93d-11e2-9412-0d192c265a62.png)
InChI=1S/C13H12N4O2S/c14-10-5-2-6-11-12(10)17-13(16-11)8-3-1-4-9(7-8)20(15,18)19/h1-7H,14H2,(H,16,17)(H2,15,18,19)

**Comment by mattodd** [comment]
Linked to this page on the wiki, so closing.
