### ISSUE TITLE
16) Does Github have a daily digest function?

### ISSUE THREAD

**Issue by alintheopen** [OpenSourceMalaria/OSM_To_Do_List#134]
Github is generating too many emails for some people and is likely to be off-putting to those unused to working with this platform. Gmail collates these fairly painlessly, but other programs like Outlook do not, meaning there's a lot of apparent "spam". Is there a digest function for GitHub to limit the number of emails sent per day?

**Comment by mwpowellhtx** [comment]
a digest feature would be great. most mailing lists support something like this. would help with the inbox clutter, for sure. one or three routers would probably thank ye as well. :+1:

**Comment by gusaiani** [comment]
Sorry to get everyone notified via email about exactly this :), but a "digest" option when following a repo would be so welcome.

Imagine being able to:
· follow
· unfollow
· ignore
· get a daily digest
· get a weekly digest

If done well in the UI, this would be great.

**Comment by drc007** [comment]
Sounds like a volunteer?

**Comment by mattodd** [comment]
sure - in fact the one that @PatrickThomson made, and which I signed up to, is still working very nicely (thanks Patrick). So nicely that I'd forgotten it wasn't a standard feature... Does anyone else use it? 
And to revisit the question from scratch - does Github itself yet have a digest feature?

**Comment by pmucci** [comment]
This is a must-have feature for github, and I truly can't image how something so simple is not implemented. The lack of such a feature is evidence of design-by-engineers not design-for-users. The fact that there's a debate about this solidifies the fact that my groups wouldn't consider paying github for anything unless this is implemented. 

Come on folks. This can be implemented with a few dozen lines of Python ...

**Comment by jcrben** [comment]
You can vote on this at the unofficial public feature request / bug tracker at https://github.com/isaacs/github/issues/340 but you should be sure to send an email to Github if you care about it...

**Comment by cryptoralf** [comment]
+1 
Please implement daily digest emails.

**Comment by olafdimigen** [comment]
+ 1
Please do.

**Comment by imtrobin** [comment]
I hope microsoft add it in.

**Comment by alexholcombe** [comment]
Gitlab doesn't offer digests, but maybe gives more control of notifications? https://docs.gitlab.com/ee/workflow/notifications.html

**Comment by imtrobin** [comment]
It's different. I want to know the project progress, but not when there's 10 emails coming in every hour

**Comment by JohannesMP** [comment]
+1
Please add a setting to limit notification emails to a single daily digest on subscribed repos. Either as a global setting or on a per-repo basis, both would be fine.

**Comment by pmucci** [comment]
It's 2020 folks. I'm now unfollowing repos due to the lack of a digest function.

**Comment by 0xdevalias** [comment]
While not a native solution, I came across these while looking today:

- https://www.cockroachlabs.com/blog/creating-a-digestible-github-digest/
- https://github.com/spencerkimball/repo-digest
