### ISSUE TITLE
Enantioselective synthesis of the alcohol 'arm' for the ether compounds

### ISSUE THREAD

**Issue by alintheopen** [OpenSourceMalaria/OSM_To_Do_List#167]
Paucity of TMS-CN, lack of preparative chiral HPLC and a passion for enantioselective synthesis has led me to consider an alternative route to the alcohol side chain required for the chiral ether compounds (e.g. MMV670652).
Based on PhD work that I did with Aurélien Bigot and Matthew J Gaunt, I'm working on an catalytic enantioselective route to this side chain. Based on (http://pubs.acs.org/doi/abs/10.1021/ja206047h) and the route below:
![chiral synthesis](https://cloud.githubusercontent.com/assets/2626599/2534876/e184c9e8-b583-11e3-8080-dae31037fc37.png)

**Comment by david1597** [comment]
Info is installed on the [wiki](https://github.com/OpenSourceMalaria/Series4/wiki/Chirality-Stereogenic-Centres-in-This-Series#enantioselective-approaches).

See also another [possible route](https://github.com/OpenSourceMalaria/Series4/issues/58) to enantioselective compounds.

Closing issue.
