### ISSUE TITLE
Check: Protocol for OSM-S-19

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#243]
@alintheopen To check: Procedure for OSM-S-19 for paper is the acid chloride-mediated route
http://malaria.ourexperiment.org/tcmdc_ap/1819
The EDC-mediated direct coupling
http://malaria.ourexperiment.org/tcmdc_ap/7552
didn't work? If not, could you please insert initial line of conclusion to that ELN entry then close this?

**Comment by mattodd** [comment]
As for #246 please annotate as much as possible, but either way close, particularly if there is no impact on the current draft of the paper or its SI.

**Comment by alintheopen** [comment]
Added missing experimental data and spectra. Did work but spectra not entirely pure. Also added data to Exptl.
