### ISSUE TITLE
Check: Coupling reagents for OSM-S-21

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#245]
@alintheopen To check: Coupling attempt to OSM-S-21 using EDCl

http://malaria.ourexperiment.org/tcmdc_ap/7563

was unsuccessful? If so, please insert initial conclusion to that ELN entry and close this Issue. (i.e. in paper we report acid chloride as the route to take).

**Comment by mattodd** [comment]
As with #247 can we note this in the ELN (here we are using the acid chloride method in the Series 1 paper) or not, and either way close this issue? Always good to note previous attempts even unsuccessful, but there are diminishing returns at this stage!

**Comment by alintheopen** [comment]
Reaction worked but final product not completely pure. Have updated ELN from notes and uploaded NMR.
