### ISSUE TITLE
Check: EDCl coupling in synthesis of OSM-S-8

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#246]
@alintheopen was the EDCl-mediated coupling to give OSM-S-8 successful? 

http://malaria.ourexperiment.org/tcmdc_ap/7554

Currently we have T3P as the synthetic method of choice, with one previous EDC coupling unsuccessful:
http://malaria.ourexperiment.org/tcmdc_ap/983

**Comment by mattodd** [comment]
AS for #247 we're using the T3P procedure, but it'd be nice to know if the other worked. Either way, please close this issue just to clear the Paper 1 decks.

**Comment by alintheopen** [comment]
not isolated cleanly. closing
