### ISSUE TITLE
Check: T3P vs EDCl for synthesis of OSM-S-17

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#247]
@alintheopen For the synthesis of the Boc-protected antipyrene compound OSM-S-17, we have a T3P protocol
http://malaria.ourexperiment.org/tcmdc_ap/1400
How did the EDCl process go?
http://malaria.ourexperiment.org/tcmdc_ap/7944
If no product formation, please note that in the ELN entry then close this Issue.

**Comment by mattodd** [comment]
So we're using the T3P protocol in the paper, but it'd still be nice to note how the EDCl process went in the ELN, for completeness. Either way, are you happy @alintheopen to close this issue now?

**Comment by alintheopen** [comment]
No NMR data found, maybe server transfer problem or may not have been measured. No conclusion so closing.
