### ISSUE TITLE
Deciding which intermediates the student should synthesise.

### ISSUE THREAD

**Issue by alintheopen** [OpenSourceMalaria/OSM_To_Do_List#263]
Following discussion with Trent Wallis and Erin Sheridan at Sydney Grammar the team are launching a School Pilot Project (OSMSPP).
Initially, the students are going to synthesise some chloroarylpyrazine cores and compounds 1-4 are currently the targets as they will be useful building plots for the OSM team.

![sydney grammar gh](https://cloud.githubusercontent.com/assets/2626599/4382471/fb8171d6-4389-11e4-91a2-f91896033c5a.png)

Does anyone have any comments/suggestions?
Health and safety issues have already been discussed with the school so comments on compound choice or route ideas are welcome.

**Comment by mattodd** [comment]
Closing since SGS have [completed a project in this area now](http://figshare.com/articles/Open_Source_Malaria_2015/1513845), and planning is underway for a follow-up project in #311
