### ISSUE TITLE
Synthesis of N-(3-chlorophenyl)-3-(4-(difluoromethoxy)phenyl)-[1,2,4]triazolo[4,3-a]pyridine-5-carboxamide

### ISSUE THREAD

**Issue by jamiescott11** [OpenSourceMalaria/OSM_To_Do_List#266]
The first target I will attempt to synthesise is compound 1, this belongs to the triazolopyridine series 4 compounds 
( OSM series 4 info http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series ) .                          This has been chosen to investigate the influence of swapping the pyrazine for a pyridine core. The pyrazine analogue (OSM-S-202, http://malaria.ourexperiment.org/osm_procedures/9880/OSMS202.html ) gained relatively good results from screening by AstraZeneca for hERG binding. 

![compound 1](https://cloud.githubusercontent.com/assets/9028489/4621735/f812c1d4-532f-11e4-8854-aa21f5838d80.png)

InChI string

InChI=1S/C20H13ClF2N4O2/c21-13-3-1-4-14(11-13)24-19(28)16-5-2-6-17-25-26-18(27(16)17)12-7-9-15(10-8-12)29-20(22)23/h1-11,20H,(H,24,28)

SMILES

O=C(NC1=CC(Cl)=CC=C1)C2=CC=CC3=NN=C(C4=CC=C(OC(F)F)C=C4)N32

**Comment by jamiescott11** [comment]
Hi all, just getting back into the project again after christmas break. I have successfully synthesized the ether  compound  shown at the very top of the page :  http://malaria.ourexperiment.org/triazolopyrazine_se/11415/Synthesis_of_452chlorophenethoxy124triazolo43apyridin3ylbenzonitrile_JS_191.html

Going to send it for testing soon. 

If you have any suggestions as to what other types of ethers to incorporate into this molecule then please let me know as I have some time left to synthesise a few derivatives now that i have the experimental procedures nailed.

**Comment by PatrickThomson** [comment]
This compound came back inactive as per: http://malaria.ourexperiment.org/biological_data/11127/Evaluation_of_some_remaining_series_3_compounds_and_series_4_pyridine_analogues.html

Closing.

**Comment by mattodd** [comment]
Hi @jamiescott11 @PatrickThomson ditto for this, obv #267
