### ISSUE TITLE
Synthesis of 4-(5-(2-chlorophenethoxy)-[1,2,4]triazolo[4,3-a]pyridin-3-yl)benzonitrile

### ISSUE THREAD

**Issue by jamiescott11** [OpenSourceMalaria/OSM_To_Do_List#267]
The second compound that I will be attempting to synthesise is shown below. This belongs to the triazolopyridine series 4 compounds (OSM series 4 info - http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series) The pyrazine core analogue (OSM-S-189) also achieved nice results from the hERG screening by AstraZeneca. 

![copound 2](https://cloud.githubusercontent.com/assets/9028489/4621849/c9dcd906-5331-11e4-8edc-2576dfbf7703.png)

SMILES :

 O=C(NC1=CC(Cl)=CC=C1)C2=CC=CC3=NN=C(C4=CC=C(OC(F)F)C=C4)N32

InChI String:

 InChI=1S/C20H13ClF2N4O2/c21-13-3-1-4-14(11-13)24-19(28)16-5-2-6-17-25-26-18(27(16)17)12-7-9-15(10-8-12)29-20(22)23/h1-11,20H,(H,24,28)

**Comment by jamiescott11** [comment]
Hi all, just getting back into the project again after christmas break. I have successfully synthesized the ether compound shown at the very top of the page : http://malaria.ourexperiment.org/triazolopyrazine_se/11415/Synthesis_of_452chlorophenethoxy124triazolo43apyridin3ylbenzonitrile_JS_191.html

Going to send it for testing soon.

If you have any suggestions as to what other types of ethers to incorporate into this molecule then please let me know as I have some time left to synthesise a few derivatives now that i have the experimental procedures nailed.

**Comment by mattodd** [comment]
Wow, Jamie, that's great news, both on this compound and on #266 . Congrats! If you're sending for testing try to group your compounds together with any others that might need to be evaluated from your lab (minimises inter-assay variability). I'm guessing if Dundee are happy to test, then they will use similar control compounds to those other labs that have tested Series 4 compounds. Browse through recent Series 4 evaluations in the relevant ELN to check this: http://malaria.ourexperiment.org/biological_data

For the NMR spectra, and any other characterization in the lab notebook, are you able to post the raw data files in addition to the png files? It's great if we can post as much raw data as possible in addition to the human-readable pictures.

As for other ethers - might you be able to make the analogs of any of the current most-wanted compounds?

http://malaria.ourexperiment.org/the_osm_blog/11379/The_Christmas_2014_Open_Source_Malaria_Shortlist.html

That'd be pretty nice to compare.

**Comment by PatrickThomson** [comment]
These compounds came back about 10 times less potent than the series 4 analogues as per: http://malaria.ourexperiment.org/biological_data/11127/Evaluation_of_some_remaining_series_3_compounds_and_series_4_pyridine_analogues.html

Closing.

**Comment by mattodd** [comment]
Hi @jamiescott11 @PatrickThomson could you please quickly check whether the data for this compound is in the spreadsheet at https://docs.google.com/spreadsheets/d/1Rvy6OiM291d1GN_cyT6eSw_C3lSuJ1jaR7AJa8hgGsc/edit#gid=510297618 and whether the compound has been added to the wiki (http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series) in the strings section but also in the main body of the series so that the result is highlighted? If not, could one of you please start an Issue for these tasks so we don't forget to incorporate these new data?

**Comment by alintheopen** [comment]
Hi, I've added to Wiki and to G Sheet. Still need to generate MMV number but closing for now as we need to start a new issue on OSM-E numbers and MMV generation.
