### ISSUE TITLE
Series 3 Synthesis: Modification to sulfonamide group on right-hand side

### ISSUE THREAD

**Issue by tpefoley** [OpenSourceMalaria/OSM_To_Do_List#279]
I am currently in the process of synthesising the following three Series 3 aminothienopyrimidine molecules with modifications to the sulfonamide group.

Starting with 3-bromobenzene sulfonyl chloride, I performed the following three syntheses by reaction with pyrollidine, methylamine and dimethylamine:

![tf9-1 synthesis](https://cloud.githubusercontent.com/assets/9027414/5855044/d02fb7c6-a22b-11e4-8050-5b814f261b14.png)
![tf10-1 synthesis](https://cloud.githubusercontent.com/assets/9027414/5855047/d7de95e6-a22b-11e4-90dc-54f0aea80a81.png)
![tf11-1 synthesis](https://cloud.githubusercontent.com/assets/9027414/5855057/e50f9d1e-a22b-11e4-807d-f27abd5bba9c.png)

[TF9-1](http://malaria.ourexperiment.org/aminotpseries/11416/Synthesis_of_13bromophenylsulfonylpyrrolidine_TF91.html) yielded an impure white solid, and NMR analysis showed that it was pure enough to take on as-is and use in the next stage of synthesis. [TF10-1](http://malaria.ourexperiment.org/aminotpseries/11418/Synthesis_of_3bromoNmethylbenzenesulfonamide_TF101.html) and [TF11-1](http://malaria.ourexperiment.org/aminotpseries/11420/Synthesis_of_3bromoNNdimethylbenzenesulfonamide_TF111.html), however, produced a brown oil and a gooey brown solid (like a melted fruit pastille) respectively - and the NMRs were very messy! We decided the impurity of the products were mainly due to two factors: leaving the reaction mixture stirring overnight, and using some very old amine hydrochlorides (vintage 1999 edition).

Instead of wasting time with two columns, I repeated the reactions on the same scale - but instead, used liquid methylamine and dimethylamine, and only left the reactions stirring for 90 minutes:

![tf10-2 synthesis](https://cloud.githubusercontent.com/assets/9027414/5855105/654e5678-a22c-11e4-8148-57a0d72da991.png)
![tf11-2 synthesis](https://cloud.githubusercontent.com/assets/9027414/5855107/66e25994-a22c-11e4-8f3c-8d9375271df5.png)

The two new reactions ([TF10-2](http://malaria.ourexperiment.org/aminotpseries/11422/Resynthesis_of_3bromoNmethylbenzenesulfonamide_TF102.html) and [TF11-2](http://malaria.ourexperiment.org/aminotpseries/11425/Resynthesis_of_3bromoNNdimethylbenzenesulfonamide_TF112.html)) produced clean, white crystalline crude products, and were taken on as-is for the next stage.

Following this, I performed the substution of Br for PinB on [TF9-1](http://malaria.ourexperiment.org/aminotpseries/11416/Synthesis_of_13bromophenylsulfonylpyrrolidine_TF91.html), [TF10-2](http://malaria.ourexperiment.org/aminotpseries/11422/Resynthesis_of_3bromoNmethylbenzenesulfonamide_TF102.html) and [TF11-2](http://malaria.ourexperiment.org/aminotpseries/11425/Resynthesis_of_3bromoNNdimethylbenzenesulfonamide_TF112.html):

![tf12-1 synthesis](https://cloud.githubusercontent.com/assets/9027414/5855153/d6a777f0-a22c-11e4-97de-f5c313bd1268.png)
![tf13-1 synthesis](https://cloud.githubusercontent.com/assets/9027414/5855154/d90b8b62-a22c-11e4-9641-514b6b1003bc.png)
![tf14-1 synthesis](https://cloud.githubusercontent.com/assets/9027414/5855155/dab9ae1c-a22c-11e4-8dc7-b4021d7691b9.png)

All 3 of the reactions ([TF12-1](http://malaria.ourexperiment.org/aminotpseries/11428/Synthesis_of_134455tetramethyl132dioxaborolan2ylphenylsulfonylpyrrolidine_TF121.html), [TF13-1](http://malaria.ourexperiment.org/aminotpseries/11430/Synthesis_of_Nmethyl34455tetramethyl132dioxaborolan2ylbenzenesulfonamide_TF131.html) and [TF14-1](http://malaria.ourexperiment.org/aminotpseries/11432/Synthesis_of_NNdimethyl34455tetramethyl132dioxaborolan2ylbenzenesulfonamide_TF141.html)) yielded black, tarry solids which I'll be purifying  by dry flash column chromatography in the next couple of days. NMR analysis shows that the likely product peaks are present, but the crude yields aren't pure enough to use as-is.

After that, all I'll have to do is the cross-coupling by reaction with the basic thienopyrimidine:

![thienopyrimidine](https://cloud.githubusercontent.com/assets/9027414/5855227/c7574c48-a22d-11e4-92aa-16f178b62bcd.png)

Then if all goes well, we'll have 3 more compounds to send off for testing!

**Comment by mattodd** [comment]
That's great, Tom. Good luck. Since there's nothing here you immediately need help with, I'll close this Issue. It would be *great* if you could:

1) Post all the above, as-is, as a blog post to the OSM blog as a new entry here
http://malaria.ourexperiment.org/the_osm_blog

2) Start 3 issues here on Github, one for each of the final molecules you're aiming for, along with relevant lab notebook pages, and the strings (SMILES, InChI and InChiKey) for each. Tag them with "Being Synthesised Now". The strings need to be text, not within the pictures, so that Google can find them. When you make the compound, close the Issue.
