### ISSUE TITLE
Short film contributions to Thinkable competition entry

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#283]
Thinkable are running an open innovation competition (closes end Feb) where they're asking for mini movie descriptions of projects.

https://www.thinkable.org/competition/6

OSM could submit something, and we'd fit well. Alice and I would film something describing what OSM actually is, but we were thinking it'd be great to include mini submissions from OSM contributors spliced in. Alice thought people could submit phone-taken vine-style video clips (10 seconds or so, mpv or mov formats) where people mention, very simply, i) who they are and ii) something they've contributed (molecule, advice, assay). To aid in the sense of continuity, the idea was that people receive an object (from off-camera) with their right hand, and pass it on (off camera) with their left - to the next video contributor. A kind of chain of virtual collaboration. 

What should the object be?

(If we can agree on this, are you happy to take a very quick video with your phone @miike @PatrickThomson @madgpap @murrayfold @cdsouthan @sabinllm and others? @ErinSheridan and @sdebbert  could your students take a 10-second video?

**Comment by ErinSheridan** [comment]
That sounds fantastic!  I think the boys would love to be involved.

**Comment by PatrickThomson** [comment]
This is brilliant and all of us here in Edinburgh would love to be involved! Wondering about the object; it'd have to be something we can all easily get our hands on, unless you're envisioning that it doesn't have to be the same object. I'll go ahead and suggest the most organo-centric object I can think of: A 250ml B24 round-bottomed flask.

**Comment by alintheopen** [comment]
Hi all, 

@ErinSheridan - would be wonderful if the boys would be involved and @PatrickThomson awesome to have Edinburgh onboard.

So, we have 3 minutes or less and therefore following on from what Mat mentioned above I propose the following format:

40-60 second introduction (Mat and Alice will take care of this)
60-100 seconds vines from team members (MMV, chemists, cheminformaticians, undergraduates, Sydney Grammar students, biologists, etc.)
40-60 second conclusion (Mat and Alice will take care of this)

For the videos from each collaborator we need to pass something from off camera so it makes sense to set up a loose order:

Alice
@PatrickThomson
Avery Group
@cdsouthan 
@sabinllm
Charman Group
Kiaran's Group
@miike 
@sdebbert 
@ErinSheridan 
@madgpap 
@murrayfold 
@miike
@PaulWillisMMV 
Chemist again
@mattodd 

We are going to struggle to fit everyone in and keep to time constraints. So, if all of the Edinburgh/Sydney Grammar/Lawrence University/Avery/Charman/Kirk groups etc. can film something together that would be great.

I'd like the video to show how many of us are part of the OSM team and the way that we are able to work together in the open. Therefore, I think it would be good if the vines told a story and we pass an object from one person to the next. @PatrickThomson, I very much like the idea of the RB flask but some people won't have one. So, in some cases I thought we could pass a generic folder with the OSM logo printed on it (found here: https://www.dropbox.com/s/q4qqxtf83a6jc19/OSM_Malaria_Logo_Final.png?dl=0) or a USB or vial or something similar. We need to firm up the order before we organise what to pass.

Mat or I will start off the video and explain the origins of the project and then I thought we could go to Edinburgh for synthesis and then Australia for biological testing and then pass from each person in order. So, if you are willing to take part AND you can get some video material to us by *Thursday 19th February* then let us know. 

What we need is a ~10s video where:
You introduce yourself and explain how you contribute to OSM - feel free to be creative in your video, we want to make it as engaging as possible. That's it really! We will edit it all together at Sydney.

Let us know asap if you think you have time to contribute and maybe look at some of the existing entries for inspiration:

https://www.thinkable.org/competition/6

Thanks everyone! Alice

**Comment by drc007** [comment]
You could intersperse the RB flask with Dreiding models, dose response curves to emphasise the iterative nature of drug discovery…

Chris

**Comment by cdsouthan** [comment]
Print one of the leads out on A4 paper ?  (maybe go over it with a marker
pen) at least between me and the other Chris

**Comment by PatrickThomson** [comment]
If we're going to go with passing different kinds of things off- and on-camera, then I guess it'd make thematic sense for us to receive data or chemical samples from @alice, then hand chemical samples on to Avery.

**Comment by mattodd** [comment]
More coming on this today, including suggested running order and what we'll
do with the objects. The first thing to do is make sure you're all happy to
have someone record you for 5-10 seconds with a camera phone, and that you
can share that file with us somehow. The editing and prettifying will be
taken care of at Sydney. Alice and I will bookend with some comments. We'll
explain what the project is all about but will make sure we don't say
anything that is too obviously controversial since we'll not have too much
time to edit and change it after it's made and before we submit it.

On 15 February 2015 at 02:21, PatrickThomson <notifications@github.com>
wrote:

>  If we're going to go with passing different kinds of things off- and
> on-camera, then I guess it'd make thematic sense for us to receive data or
> chemical samples from @alice <https://github.com/alice>, then hand
> chemical samples on to Avery.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/283#issuecomment-74378942>
> .
>



-- 
MATTHEW TODD | Associate Professor
School of Chemistry | Faculty of Science

THE UNIVERSITY OF SYDNEY
Rm 519, F11 | The University of Sydney | NSW | 2006
T +61 2 9351 2180  | F +61 2 9351 3329  | M +61 415 274104
E matthew.todd@sydney.edu.au | W
http://sydney.edu.au/science/chemistry/research/todd.html | W
http://opensourcemalaria.org/

CRICOS 00026A
This email plus any attachments to it are confidential. Any unauthorised
use is strictly prohibited. If you receive this email in error, please
delete it and any attachments.

**Comment by miike** [comment]
Sorry for the delayed response, I'm in.

**Comment by PaulWillisMMV** [comment]
Me too

Would be helpful if you could send more details today

Paul

Sent from my iPhone

On 16 Feb 2015, at 07:48, "miike" <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry for the delayed response, I'm in.

-
Reply to this email directly or view it on GitHub<https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/283#issuecomment-74466211>.

________________________________
This email and any attachments may contain confidential information. If you are not the intended recipient, please delete the email and any attachments and notify the sender immediately.
________________________________

**Comment by alintheopen** [comment]
Hi all, 
Considering the time constraints its probably going to be too difficult to work out passing different objects between the team. Instead, if each person/group of people can start their ~10s video by looking to the left as though they are speaking to previous person, then speaking to camera, then looking to right to pass on to the next person then that would be great. In the video all you need to do is acknowledge/thank the person who sends the previous video (not by name so that we have flexibility in the order) then state how you contribute to OSM and then mention who your input assists when looking to the right. If you have time to make a video then either post here or email to me (alice.williamson@sydney.edu.au). We will try to include everyone who sends us a video but we are under some strict deadlines.

Cheers everyone

Alice

**Comment by mattodd** [comment]
Yes, I think this works well. A look to the left (your left!), saying
thanks or cheers or something, then a brief improvised bit for 5-6 seconds
or so about who you are and what you've done, then say something that links
things e.g. I pass on the molecules for biological evaluation" or "and I
pass on the results to the central team via the website" and then look to
your right and....CUT. No more than 10 seconds. Feel free to do your own
thing as much as you like within this general structure.

On 16 February 2015 at 17:57, alintheopen <notifications@github.com> wrote:

>  Hi all,
> Considering the time constraints its probably going to be too difficult to
> work out passing different objects between the team. Instead, if each
> person/group of people can start their ~10s video by looking to the left as
> though they are speaking to previous person, then speaking to camera, then
> looking to right to pass on to the next person then that would be great. In
> the video all you need to do is acknowledge/thank the person who sends the
> previous video (not by name so that we have flexibility in the order) then
> state how you contribute to OSM and then mention who your input assists
> when looking to the right. If you have time to make a video then either
> post here or email to me (alice.williamson@sydney.edu.au). We will try to
> include everyone who sends us a video but we are under some strict
> deadlines.
>
> Cheers everyone
>
> Alice
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/283#issuecomment-74501259>
> .
>



-- 
MATTHEW TODD | Associate Professor
School of Chemistry | Faculty of Science

THE UNIVERSITY OF SYDNEY
Rm 519, F11 | The University of Sydney | NSW | 2006
T +61 2 9351 2180  | F +61 2 9351 3329  | M +61 415 274104
E matthew.todd@sydney.edu.au | W
http://sydney.edu.au/science/chemistry/research/todd.html | W
http://opensourcemalaria.org/

CRICOS 00026A
This email plus any attachments to it are confidential. Any unauthorised
use is strictly prohibited. If you receive this email in error, please
delete it and any attachments.

**Comment by PatrickThomson** [comment]
Ok, we've recorded three takes which will need to be trimmed of about 10-15 seconds of fluff each side, then chosen between - we have virtually no video editing capacity here, at least not that can be set up within a day and I'm concerned about hitting the quality in any case. Also I just checked and two of them are upside-down.

https://drive.google.com/file/d/0B6rAjqmPhHy5TUdtc1RBZDJLU3c/view?usp=sharing

**Comment by alintheopen** [comment]
Great job Edinburgh! This is Sydney calling and you get 12 points!! Thanks guys.

**Comment by alintheopen** [comment]
P.S. They aren't upside down here....maybe the rumours are true and you filmed them the right way around for Australia!

**Comment by sdebbert** [comment]
Here's a clip I shot with one of my students -- it's on the long side, so let me know if I need to take another crack at it.

https://drive.google.com/file/d/0Bws-d5o7Woy-YWtoLVpWUUJ2ZW8/view?usp=sharing

**Comment by mattodd** [comment]
Oh it's very good. Let's see if we can fit it in. Any chance you could make
a shorter backup just in case - both of you in the same shot, for example?
We're very pressed on time for this video, sadly.

On 20 February 2015 at 10:13, Stefan Debbert <notifications@github.com>
wrote:

>  Here's a clip I shot with one of my students -- it's on the long side,
> so let me know if I need to take another crack at it.
>
>
> https://drive.google.com/file/d/0Bws-d5o7Woy-YWtoLVpWUUJ2ZW8/view?usp=sharing
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/283#issuecomment-75159277>
> .
>



-- 
MATTHEW TODD | Associate Professor
School of Chemistry | Faculty of Science

THE UNIVERSITY OF SYDNEY
Rm 519, F11 | The University of Sydney | NSW | 2006
T +61 2 9351 2180  | F +61 2 9351 3329  | M +61 415 274104
E matthew.todd@sydney.edu.au | W
http://sydney.edu.au/science/chemistry/research/todd.html | W
http://opensourcemalaria.org/

CRICOS 00026A
This email plus any attachments to it are confidential. Any unauthorised
use is strictly prohibited. If you receive this email in error, please
delete it and any attachments.

**Comment by alintheopen** [comment]
Yes, it is great @sdebbert but Mat is right I think we do need a shorter one. We still need to fit in a few more short videos and we are running out of spare seconds. I love the video though.

**Comment by sdebbert** [comment]
?No worries -- I'll grab it in class today!

Stefan


--

Stefan Debbert

Associate Professor
Department of Chemistry
233 Science Hall

711 E. Boldt Way
Lawrence University
Appleton, WI 54911
office phone: (920) 832-6939

stefan.debbert@lawrence.edu
-----------------------------------------



________________________________

**Comment by sdebbert** [comment]
Here's a shorter clip --
https://drive.google.com/file/d/0Bws-d5o7Woy-bzRCT1RYTU01bkE/view?usp=sharing
Looking forward to seeing the final product!

**Comment by mattodd** [comment]
Really great Stefan, thanks so much - we'll definitely send round the
complete version ASAP.
M


On 21 February 2015 at 04:19, Stefan Debbert <notifications@github.com>
wrote:

>  Here's a shorter clip --
>
> https://drive.google.com/file/d/0Bws-d5o7Woy-bzRCT1RYTU01bkE/view?usp=sharing
> Looking forward to seeing the final product!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/283#issuecomment-75279028>
> .
>



-- 
MATTHEW TODD | Associate Professor
School of Chemistry | Faculty of Science

THE UNIVERSITY OF SYDNEY
Rm 519, F11 | The University of Sydney | NSW | 2006
T +61 2 9351 2180  | F +61 2 9351 3329  | M +61 415 274104
E matthew.todd@sydney.edu.au | W
http://sydney.edu.au/science/chemistry/research/todd.html | W
http://opensourcemalaria.org/

CRICOS 00026A
This email plus any attachments to it are confidential. Any unauthorised
use is strictly prohibited. If you receive this email in error, please
delete it and any attachments.

**Comment by miike** [comment]
Alright, apologies for the delay.

https://drive.google.com/file/d/0B56KFDTvfcKwcHh5d2pFWHQ2UDQ/view?usp=sharing

Let me know if you need any assistance editing as I've got AE/Premiere on this computer.

**Comment by mattodd** [comment]
Very nice, thanks!


On 22 February 2015 at 18:35, miike <notifications@github.com> wrote:

>  Alright, apologies for the delay.
>
>
> https://drive.google.com/file/d/0B56KFDTvfcKwcHh5d2pFWHQ2UDQ/view?usp=sharing
>
> Let me know if you need any assistance editing as I've got AE/Premiere on
> this computer.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/283#issuecomment-75424013>
> .
>



-- 
MATTHEW TODD | Associate Professor
School of Chemistry | Faculty of Science

THE UNIVERSITY OF SYDNEY
Rm 519, F11 | The University of Sydney | NSW | 2006
T +61 2 9351 2180  | F +61 2 9351 3329  | M +61 415 274104
E matthew.todd@sydney.edu.au | W
http://sydney.edu.au/science/chemistry/research/todd.html | W
http://opensourcemalaria.org/

CRICOS 00026A
This email plus any attachments to it are confidential. Any unauthorised
use is strictly prohibited. If you receive this email in error, please
delete it and any attachments.

**Comment by cdsouthan** [comment]
Hop this fits the bill,  Cheers Chris

*Dr Christopher Southan*, Ph.D., M.Sc.,B.Sc.
Curator, IUPHAR/BPS Guide to PHARMACOLOGY
Centre for Integrative Physiology, University of Edinburgh, EH8 9XD, UK
http://www.guidetopharmacology.org/

Working remotely from Göteborg

Mob: +46(0)702-530710 (Sweden)  Skype: cdsouthan
Twitter: http://twitter.com/#!/cdsouthan
Blog: http://cdsouthan.blogspot.com/
LinkedIN: http://www.linkedin.com/in/cdsouthan
TW2Informatics: http://www.cdsouthan.info/Consult/CDS_cons.htm
Publications:
http://www.citeulike.org/user/cdsouthan/order/year,,/publications
 Presentations: http://www.slideshare.net/cdsouthan
ORCHID  ID 0000-0001-9580-0446

**Comment by mattodd** [comment]
Closing. Entry is at https://www.thinkable.org/competition/6
Full version is at https://youtu.be/o29cq7uYWFc
Thank you all for all your hard work with this. Voting is still open, so do encourage people you know to support it!
