### ISSUE TITLE
Votes Needed for Thinkable Open Innovation Competition

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#284]
We submitted an entry for the Thinkable Open Innovation competition - thanks to everyone who helped with this! The result is really good, thanks to these great contributions from active OSM-ers.

Here it is: https://www.thinkable.org/submission/2055

The submission had to be 3 minutes long (we will post the full version elsewhere).

*Now we need votes*. The winner of this competition is the video with the most votes at the end of April.

The prize is $5000 and every dollar of the prize would go to supporting malaria research in OSM.

So please go to https://www.thinkable.org/submission/2055, sign up to Thinkable (very quick and easy - you can sign in through Facebook etc if you like) and vote for the project! Please also spread this through your social networks so that we can alert people to the work we're all doing. Sincere thanks in advance for your time in helping spread the word.

**Comment by alintheopen** [comment]
Closing as vote is over for now but a new competition is launching soon.
