### ISSUE TITLE
Primary Google indexing of OSM structures via InChIKey

### ISSUE THREAD

**Issue by cdsouthan** [OpenSourceMalaria/OSM_To_Do_List#289]
I note that while this page below  convverts well in chemicalize.org  there are no InChIKeys

http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Strings_for_Google

As you know these the Keys the most effective way for your structures to become Google findable so its a good idea to add them.  Otherwise you have the odd situation that leads like  MMV670437 PMIWBIXSAYKRGF-SFHVURJKSA-N can be found but not on the OSM site

**Comment by mattodd** [comment]
There are Keys on the page, but not yet for every compound. Some ought to
be captured..?

**Comment by drc007** [comment]
If you look at the source code it is a HTML page which is great for viewing in a web browser but I wonder if the html tags are messing up interpretation?

**Comment by cdsouthan** [comment]
Chris/Matt, there are two related issues here. As you can test chemicalize.org works fine for IUPAC, SMILES or InChI strings on (any)  html pages. But AWK it wont "convert" InChIKeys (it could do for ones it has but thats their choice).   As you can see (image attached) Google indexes the InChIKey just fine in just about any OSM instanciation. This thus solves the "findability" problem but only as exact (or inner layer) match.  Consequenct to my encouragment,  ChemAxon actually deposited their chemicalize.org structure conversion cache in PubChem
https://www.ncbi.nlm.nih.gov/pccompound?term=%22chemicalize.org%20by%20ChemAxon%22[SourceName]&cmd=DetailsSearch
The big advantage (potentialy) for OSM, would be a  quicker route for getting all structures to > PubChem (via chemicalization of the web pages) which them become globaly findable (in PubChem) by similarity as well as just exact match.  However, ChemAxon did not prioritised the updates, so you can only "find" them if you exucute a similarity search on chemicalize.org in situ  (i.e. their updated cache of structures) 




![capture](https://cloud.githubusercontent.com/assets/3713939/6941346/5d1656ac-d87f-11e4-96fd-1dc42c6217ca.JPG)

**Comment by mattodd** [comment]
Just wanting to either progress or close this. We continue to use Keys, correct, but is there some problem with including them as text on a wiki? i.e. is this a problem our end or specifically with Chemicalise? Is this issue critical (actively introducing confusion) or rather "would like to have"?

**Comment by mattodd** [comment]
Since data now being added to Google Master sheet, I'm closing this and we can re-engage with the newer ways in which we are making the strings public.
