### ISSUE TITLE
Updated OSM Website - request for suggestions

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#297]
Hello all. The OSM Landing Page is being altered to try to improve how things look. Test site:

http://opensourcemalaria.github.io/NewSite/#

We're still tweaking for another week or so. Anyone have any suggestions, or things they'd like to see? The intention is mainly to improve the appearance and grouping of To Do items in the middle of the page, clarify the text describing the project a little (that's coming) and include a link to the new molecule database feature @drc007 and @lpatiny introduced.

Suggestions/requests?

**Comment by drc007** [comment]
Would it be possible to have a moving ticker tape highlighting tweets that have the hashtag osm, malaria etc rather than the static side bar which looks a little boring. Is it possible to have the "High Priority" tag always displayed first.

**Comment by mattodd** [comment]
Thanks Chris. Tickertape - don't know. Things that move on webpages worry
me as they inevitably increase page load times. The Github tag idea is a
good one, but at the moment the default is that the post that is most
recently commented on rises to the top - that way the content best shows
what's being discussed and will change most frequently. I like your
suggestion, though.

On 6 June 2015 at 02:25, Chris Swain <notifications@github.com> wrote:

>  Would it be possible to have a moving ticker tape highlighting tweets
> that have the hashtag osm, malaria etc rather than the static side bar
> which looks a little boring. Is it possible to have the "High Priority" tag
> always displayed first.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/297#issuecomment-109352377>
> .
>



-- 
MATTHEW TODD | Associate Professor
School of Chemistry | Faculty of Science

THE UNIVERSITY OF SYDNEY
Rm 519, F11 | The University of Sydney | NSW | 2006
T +61 2 9351 2180  | F +61 2 9351 3329  | M +61 415 274104
E matthew.todd@sydney.edu.au | W
http://sydney.edu.au/science/chemistry/research/todd.html | W
http://opensourcemalaria.org/

CRICOS 00026A
This email plus any attachments to it are confidential. Any unauthorised
use is strictly prohibited. If you receive this email in error, please
delete it and any attachments.

**Comment by drc007** [comment]
A few more thoughts. When I look at the site on my iPhone half the screen is taken up by the OSM banner, and I can read down to the "Read More". If I switch tabs "Activity", "Join the Team" and "Meet us" the screen is still completely occupied by the banner and the project description, it is only when I scroll down I see the differences. I'd make the OSM banner a fraction of the size when viewed on mobile devices. You could also think about have 4 tabs, "About", "Activity", "Join the Team" and "Meet us" and having the project description on the "About" tab.

**Comment by drc007** [comment]
Would it be worth having the Twitter, google+ and Facebook links displayed more prominently? The pale grey buttons at the bottom of the Twitter Activity does not really encourage people to follow. Perhaps also have them at the top of the "Join the Team" tab, with text suggesting people might like to follow and find out what is happening?

**Comment by mattodd** [comment]
Thank you Chris for the inputs. I just spoke with the project team and
we've sadly exhausted the budget/timeframe so they need to roll-out as-is
and move to other projects. The mobile issue is an important one in
particular, but will have to be on a "future desirables" list. There is an
option to have volunteers tweak things further, not least since all the
code is freely available on Github (if you know what you're doing).

On 7 June 2015 at 17:22, Chris Swain <notifications@github.com> wrote:

>  Would it be worth having the Twitter, google+ and Facebook links
> displayed more prominently? The pale grey buttons at the bottom of the
> Twitter Activity does not really encourage people to follow. Perhaps also
> have them at the top of the "Join the Team" tab, with text suggesting
> people might like to follow and find out what is happening?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/297#issuecomment-109708573>
> .
>



-- 
MATTHEW TODD | Associate Professor
School of Chemistry | Faculty of Science

THE UNIVERSITY OF SYDNEY
Rm 519, F11 | The University of Sydney | NSW | 2006
T +61 2 9351 2180  | F +61 2 9351 3329  | M +61 415 274104
E matthew.todd@sydney.edu.au | W
http://sydney.edu.au/science/chemistry/research/todd.html | W
http://opensourcemalaria.org/

CRICOS 00026A
This email plus any attachments to it are confidential. Any unauthorised
use is strictly prohibited. If you receive this email in error, please
delete it and any attachments.

**Comment by mattodd** [comment]
Updated site now live! This thread will remain discoverable for future iterations, even though I now close it.
