### ISSUE TITLE
Post New Data from Winzeler and Syngene to ELN and Wiki

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#299]
Hi @alintheopen thanks for offering just now to do this posting to the ELN. We have new data on two Series 1 compounds from Elizabeth Winzeler and Stephan Meister on liver stage potency (which are interesting) and new potency data for latest Series 4 analogs. Both can go to the "Biological" ELN posted as OSM-ELN.

Then the data for Series 4 needs to be incorporated into the wiki (i.e. figure of structures and potencies - don't worry about adding the Series 1 data to the wiki since we need to just fold it into the paper that's at the penultimate draft stage). I'm still not sure of the best way to do the wiki. My immediate inclination is to add in the data separately (i.e. chronologically, new figure) since the data are new and that's easier, but ideally we'd just add in the compounds to the relevant existing figure (e.g. the huge ether figure already there) to help build the SAR table. We're not ultimately going to care about chronology down the line.

The strings for the Syngene set need then to go to the bottom of the wiki, and the Google sheet...
https://docs.google.com/spreadsheets/d/1Rvy6OiM291d1GN_cyT6eSw_C3lSuJ1jaR7AJa8hgGsc/edit#gid=510297618

====

As an aside, I started a Github repo of all the wiki-related files (chemdraws, pngs) for the OSTB project, which syncs the relevant Dropbox folder (which I share with Jessica) with the repo, so quite handy.

https://github.com/OpenSourceTB/Wiki-Files

At the moment for OSM we have an ELN page for this, which I think we're not using much.

http://malaria.ourexperiment.org/osdd_malaria_shared/8585/Files_Associated_with_Wiki_Page_on_Series_4.html

I wonder if we should start a collection of relevant files on GH instead? Any better? Slightly easier to combine files from various people without logging into the ELN, but there are pros and cons.

**Comment by alintheopen** [comment]
OK. Will get to this a little later on. With regard to GH/ELN maybe we should try GH for a while and see how we find this? Our dropbox is also due a serious spring clean. Perhaps we should take stock after paper one submission.

**Comment by mattodd** [comment]
Agreed!

On 12 June 2015 at 09:35, alintheopen <notifications@github.com> wrote:

>  OK. Will get to this a little later on. With regard to GH/ELN maybe we
> should try GH for a while and see how we find this? Our dropbox is also due
> a serious spring clean. Perhaps we should take stock after paper one
> submission.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/299#issuecomment-111306830>
> .
>



-- 
MATTHEW TODD | Associate Professor
School of Chemistry | Faculty of Science

THE UNIVERSITY OF SYDNEY
Rm 519, F11 | The University of Sydney | NSW | 2006
T +61 2 9351 2180  | F +61 2 9351 3329  | M +61 415 274104
E matthew.todd@sydney.edu.au | W
http://sydney.edu.au/science/chemistry/research/todd.html | W
http://opensourcemalaria.org/

CRICOS 00026A
This email plus any attachments to it are confidential. Any unauthorised
use is strictly prohibited. If you receive this email in error, please
delete it and any attachments.

**Comment by alintheopen** [comment]
Winzeler (http://malaria.ourexperiment.org/uri/7f9) and Syngene (http://malaria.ourexperiment.org/uri/7f8) data posted.

Wiki update coming soon and post on new targets.

**Comment by alintheopen** [comment]
post on new targets: http://malaria.ourexperiment.org/uri/7fe

**Comment by mattodd** [comment]
Great. Have incorporated new Winzeler results into OSM Paper 1 (no need for wiki on this one). Just need Syngene into the wiki schemes (ping me if you can't find the relevant Chemdraw), into the wiki strings section and into the Google sheet at https://docs.google.com/spreadsheets/d/1Rvy6OiM291d1GN_cyT6eSw_C3lSuJ1jaR7AJa8hgGsc/edit#gid=510297618. Interestingly in the last week or so about 3-4 people new to OSM have independently asked for the list of Series 4 compounds @drc007 so that list is already proving useful.

**Comment by alintheopen** [comment]
All Syngene compounds uploaded and Google sheet updated with all Syngene compounds. Closing now as updates to Google Sheets are being discussed in other threads #285
