### ISSUE TITLE
Website Pictures

### ISSUE THREAD

**Issue by alintheopen** [OpenSourceMalaria/OSM_To_Do_List#305]
As per issue #298 we need pictures of the boys and Erin and Trent to that we can update the new website. Best to sign up for a Gravatar, second best to send individual high def image to opensourcemalaria@gmail.com

**Comment by mattodd** [comment]
Hi @ErinSheridan any chance we could have a picture for you, or SGS, or the boys, or something we can put onto the "team" page of the website? Would be good to add you/you all in some way.

**Comment by ErinSheridan** [comment]
I've emailed photos of the boys and myself to opensourcemalaria@gmail.com, but @TrentWallis I don't have one of you!

**Comment by mattodd** [comment]
Got them, thanks! Will upload to the site ASAP.

On 4 November 2015 at 13:34, ErinSheridan <notifications@github.com> wrote:

> I've emailed photos of the boys and myself to opensourcemalaria@gmail.com,
> but @TrentWallis <https://github.com/TrentWallis> I don't have one of you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/305#issuecomment-153552514>
> .
>



-- 
MATTHEW TODD | Associate Professor
School of Chemistry | Faculty of Science

THE UNIVERSITY OF SYDNEY
Rm 519, F11 | The University of Sydney | NSW | 2006
T +61 2 9351 2180  | F +61 2 9351 3329  | M +61 415 274104
E matthew.todd@sydney.edu.au | W
http://sydney.edu.au/science/people/matthew.todd.php
W http://opensourcemalaria.org/ | W http://opensourcetb.org/ | W
http://opensourcepharma.net/

CRICOS 00026A
This email plus any attachments to it are confidential. Any unauthorised
use is strictly prohibited. If you receive this email in error, please
delete it and any attachments.

**Comment by mattodd** [comment]
Uploaded the photos @ErinSheridan - see the "Meet Us" page. Thanks for these - good to feature them all. @TrentWallis if you'd like a picture, just send it over! Closing this issue now.

**Comment by mattodd** [comment]
Ah - got it @TrentWallis - uploading.
