### ISSUE TITLE
Scheduling Next OSM Online Meeting - July 2015

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#315]
We need to meet online to discuss next steps, principally molecule design for Series 4. A good timezone compromise is:

4pm Sydney
11:30am Delhi
8am Geneva
7am London
2am New York
11pm San Francisco

I suggest as possible dates this month:
Thursday 16th
Friday 17th
Mon 20th
Tue 21st

Any bad clashes or preferences?
We'll continue to consult till then, and we'll assemble the agenda in the meantime, but we need something in the diary.

**Comment by alintheopen** [comment]
If possible not Tue 21st. Cheers Alice

**Comment by PaulWillisMMV** [comment]
All dates fine for me  Paul

**Comment by mattodd** [comment]
OK, I suggest next Monday, 20th at the times above.
I will start new Issues re agenda materials etc.
Meeting online location will be: http://webconf.ucc.usyd.edu.au/osm20jul2015/
Closing
