### ISSUE TITLE
Synthesis of  6-chloropyrazin-2-amine

### ISSUE THREAD

**Issue by tyzhengsydney** [OpenSourceMalaria/OSM_To_Do_List#316]
![tz 1-1 target](https://cloud.githubusercontent.com/assets/13214148/8585610/a466cda2-2627-11e5-8344-0c9106694461.png)

InChI=1S/C4H4ClN3/c5-3-1-7-2-4(6)8-3/h1-2H,(H2,6,8)
ClC1=CN=CC(N)=N1

Hi, I am Tianyi. I am a student on exchange from Nanjing University and I am working with Alice on the lab. We try to make 6-chloropyrazin-2-amine under the same conditions used to make 2-Chloro-6-hydrazinylpyrazine (AEW 85-7), but replacing hydrazine hydrate with ammonia (http://malaria.ourexperiment.org/uri/810). The TLC so far suggests only starting material but we will confirm today. I did literature search and found a patent describing synthesis of 6-chloropyrazin-2-amine using the same starting material but with aqueous solvent at 100 degrees in a sealed tube. We will try that today.http://worldwide.espacenet.com/publicationDetails/originalDocument?CC=WO&NR=2013068755A1&KC=A1&FT=D&ND=&date=20130516&DB=&&locale=en_EP

Ref https://github.com/tyzhengsydney

**Comment by alintheopen** [comment]
Product made in 67% yield on 500 mg scale, to be scaled-up on Monday. http://malaria.ourexperiment.org/uri/819

**Comment by mattodd** [comment]
Great. The NMR data you have - do the data match any literature data for this compound? i.e. how do you know that your compound is the right compound? Has anyone else made it before?

It's also a crystalline solid, so is there a lit melting point? What's the mp of your sample?

For publication we'll need LRMS or IR etc too - usually 3 points of data for known compounds.
