### ISSUE TITLE
Call for Agenda Items for Online Meeting 10

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#317]
Updated due to meeting postponement: Meeting number 10 will happen on Monday July **27th** at [these times](http://www.timeanddate.com/worldclock/meetingdetails.html?year=2015&month=7&day=27&hour=6&min=0&sec=0&p1=224&p2=179&p3=136&p4=87&p5=176&p6=240) and at [this location](http://webconf.ucc.usyd.edu.au/osm20jul2015/).

The two main items under discussion will be [analog design](http://malaria.ourexperiment.org/the_osm_blog/11565/What_Should_We_Synthesise_Next.html) (also #301 ) and [metabolic clearance](http://malaria.ourexperiment.org/biological_data/8225/Summary_of_Series_4_Metabolic_Data__July_2015.html) <-- this is a new post. A more detailed agenda is now needed, and slides will be sent round before the meeting.

Anyone like to suggest items for discussion below? These will then be incorporated.

**Comment by mattodd** [comment]
Current Composite Agenda:

1) Analysis of Metabolic Data (links to resources)
2) Analog Design (links to resources)
3) Shall we Order a Compound from a CRO (summary of status coming)

**Comment by mattodd** [comment]
Hi @wvanhoorn - note the change in day to the 27th. It'd be really great if you could join us and describe the predictive work you've been doing.

**Comment by wvanhoorn** [comment]
Thanks for the heads up, I will be there on the 27th

**Comment by mattodd** [comment]
Hi @wvanhoorn great - would you be amenable to talking us through your approach for literally 2 minutes on Monday? All you'd need is a laptop and browser. I will take the last set of compounds you recommended as an image, but it'd be great if you could very quickly speak to the method. It is a tad early UK time.

**Comment by cdsouthan** [comment]
Extra slide (time permitting natch)

**************************
250 InChIs from OSM master sheet > PubChem mapping https://pubchem.ncbi.nlm.nih.gov/idexchange/idexchange.cgi 
 167 are CIDs in PubChem http://www.ncbi.nlm.nih.gov/sites/myncbi/christopher.southan.1/collections/48338932/public/    and 155 have a ChEMBL match

Suggestions
Optimise  sheet (e.g. missing InChIKeys, round tripping between SMILES and InChI, rounding off significant figs)
Submit confirmed summary data as a PubChemBioAssay 
Refresh (latest data)  and extend ChEMBL submission
Deposit rest of the (73) structures into PubChem, including pending designs, but clearly labelled as transient virtuals (makes everything globally findable by similarity search)
Lock down in-house synonym mapping (structure > OSM >other? > MMV > ChEMBL ID > PubChem CID) and choose what you surface to ROW via ChEMBL/ PubChem

**Comment by mattodd** [comment]
Added - thanks, though we're under major time pressure. A data-focussed meeting later on might be a good idea. Sept? 

Quick and basic question. Are the data in the Master sheet visible to Google? If not, do the data only become visible once we submit to a database?

**Comment by cdsouthan** [comment]
Fine - initial results exposed here anyway.  AWK Google indexing is somewhat mysterious but we can of course do check seaches quickly.  For exampe UYWFTHNNGLIMAY-UHFFFAOYSA-N  seems to be surfacing from OSM instantiations and Chris's blog but not the Google doc directly

**Comment by wvanhoorn** [comment]
@mattodd I can present something on Monday, two minutes is very brief so it will be a wizz through

**Comment by mattodd** [comment]
Yes, great. If you're able to send me a slide beforehand for incorporation
into the deck that'd be useful, but no pressure.

On 27 July 2015 at 02:57, Willem van Hoorn <notifications@github.com> wrote:

>  @mattodd <https://github.com/mattodd> I can present something on Monday,
> two minutes is very brief so it will be a wizz through
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/317#issuecomment-125017398>
> .
>



-- 
MATTHEW TODD | Associate Professor
School of Chemistry | Faculty of Science

THE UNIVERSITY OF SYDNEY
Rm 519, F11 | The University of Sydney | NSW | 2006
T +61 2 9351 2180  | F +61 2 9351 3329  | M +61 415 274104
E matthew.todd@sydney.edu.au | W
http://sydney.edu.au/science/people/matthew.todd.php
W http://opensourcemalaria.org/ | W http://opensourcetb.org/ | W
http://opensourcepharma.net/

CRICOS 00026A
This email plus any attachments to it are confidential. Any unauthorised
use is strictly prohibited. If you receive this email in error, please
delete it and any attachments.

**Comment by mattodd** [comment]
Meeting [took place](http://malaria.ourexperiment.org/osddmalaria_meeting_/8194). Closing.
