### ISSUE TITLE
Synthesis of 5-chloro-[1,2,4]triazolo[4,3-a]pyrazine (TZ 2-1)

### ISSUE THREAD

**Issue by tyzhengsydney** [OpenSourceMalaria/OSM_To_Do_List#326]
![5-chloro- 1 2 4 triazolo 4 3-a pyrazine](https://cloud.githubusercontent.com/assets/13214148/8698378/f61112ac-2b40-11e5-80c1-a980e9104a82.png)
5-chloro-[1,2,4]triazolo[4,3-a]pyrazine (TZ 2-1) Strings: 
ClC1=CN=CC2=NN=CN21 
and 
InChI=1S/C5H3ClN4/c6-4-1-7-2-5-9-8-3-10(4)5/h1-3H

Hi I'm Tianyi. I've been working with Alice on the lab for one week. We next plan to synthesise 5-chloro-[1,2,4]triazolo[4,3-a]pyrazine. We make this compound in order to  develop some bromination chemistry and new methods for core synthesis. In this case, we'll develop methods to conduct bromination at 3-position. Reaction conditions are shown below.
Hydrazinylpyrazine (8g, 55.3mmol, 1 equiv.), triethyl orthoformate (18.4 ml, 110.6 mmol, 2 equiv.), and tosylic acid (2.765mmol, 0.05 equiv.) were dissolved in toluene (to around 0.35 M) and heated at reflux for 24 h.
We'll see what happens this Thursday morning.

**Comment by mattodd** [comment]
Hi @tyzhengsydney - can you update? How is this looking, based on your [latest experiment](http://malaria.ourexperiment.org/triazolopyrazine_se/9754/Synthesis_of_5Chloro124triazolo43apyrazine_TZ_21.html)? The details of the experiment go in the ELN, but you can say here whether you've made this compound. If yes, we can close this issue.

**Comment by mattodd** [comment]
Closing. Cross-link to #433 . Link installed in [synthetic chemistry section of wiki](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Alternative_Routes_to_the_Triazolopyrazine_Core).
