### ISSUE TITLE
Adding IC50 values for compounds tested by GSK

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#329]
Hi Jun @jhon4903 following on from #328 you could, while you're at it, add the accurate potencies for these compounds?

So some of the compounds assayed in the "single shot" assay were then examined in more detail to derive an IC50. These results are [here](http://malaria.ourexperiment.org/biological_data/10456/IC50_determination_of_Compounds_Sent_to_GSK.html)

Could you add the potency numbers (where it says "PfIC50" in the scheme) into the right cells in column I of the sheet ("Pfal IC50 (GSK)")? There are values there for 6 of the Series 4 compounds, and if you're happy to add the others there (Series 3 and TB), that'd be absolutely great too!

**Comment by jhon4903** [comment]
@mattodd I have just finished adding the single shot potencies for the compounds from series 3,4 and TB including the values for the Pfal IC50 (GSK).

**Comment by mattodd** [comment]
That's fantastic, Jun, great work. We need to include you on the [Team](http://opensourcemalaria.org/) page - can you email me a picture of yourself that is 80 x 80 pixels?

**Comment by jhon4903** [comment]
Here is the attached picture of myself as a jpg file (80x80 pixels)

________________________________
