### ISSUE TITLE
Resynthesise TCMDC 132385 to confirm potency 

### ISSUE THREAD

**Issue by alintheopen** [OpenSourceMalaria/OSM_To_Do_List#33]
Prior to synthesis of more piperazine derivatives it is important to confirm the potency of this compounds:
![tcmdc-132385](https://f.cloud.github.com/assets/2626599/566084/88c25172-c669-11e2-84b1-8e591e0be178.png)

**Comment by mattodd** [comment]
Compound above is OSM-S-449. FC(C=C1)=CC=C1CN(CC2)CCN2C3=C4C(C=C(C5=CC=CC=C5)S4)=NC=N3, implying made.
Linked also in #4 . Linked in wiki. Closing.
