### ISSUE TITLE
Collecting the Most Recent Potency Data for Monday's Meeting

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#330]
Hi @tyzhengsydney - we're due to have our next OSM meeting on Monday #317 and part of that meeting will be discussion of the most recent compounds synthesised for testing. It would be very useful if you could gather together the images of the three most recently evaluated sets of compounds (from [June](http://malaria.ourexperiment.org/biological_data/11080/Results_for_samples_sent_for_in_vitro_efficacy_evaluation_against_Plasmodium_falciparum_asexual_blood_stage.html), [November](http://malaria.ourexperiment.org/biological_data/11216/Evaluation_of_Latest_Series_4_Analogs_in_Ether_and_Amide_Series.html), and [July](http://malaria.ourexperiment.org/biological_data/10456/IC50_determination_of_Compounds_Sent_to_GSK.html)), and make sure we have 3 powerpoint slides ready to share with people who are coming to the meeting. The powerpoint template you can use is [here](http://malaria.ourexperiment.org/data/files/14168/OSM%20Nov%202014%20Meeting%20Slides%20v1.ppt). 

Typically the png image format works best, but whatever gives a clear slide that people can see. Once you have the slides, email them to me and I'll share them with everyone.

Once we have those, would you also be able to check whether the potency data for the relevant compounds are in the [Compound Sheet](https://docs.google.com/spreadsheets/d/1Rvy6OiM291d1GN_cyT6eSw_C3lSuJ1jaR7AJa8hgGsc/edit#gid=510297618)? If yes, great. If some data are missing, are you able to add the data for the compounds in columns A-F and the potency data (in micromolar) in column J for the Syngene compounds. I believe @jhon4903 has taken care of the data from July 2014 from GSK already.

Thanks for this Tianyi. Let me know here if you have any questions about any of this.

**Comment by tyzhengsydney** [comment]
Hi professor,
I am not sure about the following things about this.
1. Is it OK if we make the three images into four or five slides?
One of them
<http://malaria.ourexperiment.org/biological_data/10456/IC50_determination_of_Compounds_Sent_to_GSK.html>
is
too big to be seen clearly if we put it as a whole in one slide. It
includes three different sets of compounds. Would that be possible if we
cut it into three smaller pieces and put them in separate slides?
2. Do I need to put the conclusions of these in the slides like
observations in this
<http://malaria.ourexperiment.org/biological_data/11216/Evaluation_of_Latest_Series_4_Analogs_in_Ether_and_Amide_Series.html>
?

Thanks.

**Comment by mattodd** [comment]
Hi Tianyi
Answers are:
1) Yes, fine
2) No, no need to do that.

On 22 July 2015 at 10:47, Tianyi Zheng <notifications@github.com> wrote:

>  Hi professor,
> I am not sure about the following things about this.
> 1. Is it OK if we make the three images into four or five slides?
> One of them
> <
> http://malaria.ourexperiment.org/biological_data/10456/IC50_determination_of_Compounds_Sent_to_GSK.html
> >
> is
> too big to be seen clearly if we put it as a whole in one slide. It
> includes three different sets of compounds. Would that be possible if we
> cut it into three smaller pieces and put them in separate slides?
> 2. Do I need to put the conclusions of these in the slides like
> observations in this
> <
> http://malaria.ourexperiment.org/biological_data/11216/Evaluation_of_Latest_Series_4_Analogs_in_Ether_and_Amide_Series.html
> >
> ?
>
> Thanks.
>
>
> On Tue, Jul 21, 2015 at 11:18 PM, Mat Todd <notifications@github.com>
> wrote:
>
> > Hi @tyzhengsydney <https://github.com/tyzhengsydney> - we're due to have
> > our next OSM meeting on Monday #317
> > <https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/317> and
> part
> > of that meeting will be discussion of the most recent compounds
> synthesised
> > for testing. It would be very useful if you could gather together the
> > images of the three most recently evaluated sets of compounds (from June
> > <
> http://malaria.ourexperiment.org/biological_data/11080/Results_for_samples_sent_for_in_vitro_efficacy_evaluation_against_Plasmodium_falciparum_asexual_blood_stage.html
> >,
> > November
> > <
> http://malaria.ourexperiment.org/biological_data/11216/Evaluation_of_Latest_Series_4_Analogs_in_Ether_and_Amide_Series.html
> >,
> > and July
> > <
> http://malaria.ourexperiment.org/biological_data/10456/IC50_determination_of_Compounds_Sent_to_GSK.html
> >),
> > and make sure we have 3 powerpoint slides ready to share with people who
> > are coming to the meeting. The powerpoint template you can use is here
> > <
> http://malaria.ourexperiment.org/data/files/14168/OSM%20Nov%202014%20Meeting%20Slides%20v1.ppt
> >.
> >
> >
> > Typically the png image format works best, but whatever gives a clear
> > slide that people can see. Once you have the slides, email them to me and
> > I'll share them with everyone.
> >
> > Once we have those, would you also be able to check whether the potency
> > data for the relevant compounds are in the Compound Sheet
> > <
> https://docs.google.com/spreadsheets/d/1Rvy6OiM291d1GN_cyT6eSw_C3lSuJ1jaR7AJa8hgGsc/edit#gid=510297618
> >?
> > If yes, great. If some data are missing, are you able to add the data for
> > the compounds in columns A-F and the potency data (in micromolar) in
> column
> > J for the Syngene compounds. I believe @jhon4903
> > <https://github.com/jhon4903> has taken care of the data from July 2014
> > from GSK already.
> >
> > Thanks for this Tianyi. Let me know here if you have any questions about
> > any of this.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/330>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/330#issuecomment-123519923>
> .
>



-- 
MATTHEW TODD | Associate Professor
School of Chemistry | Faculty of Science

THE UNIVERSITY OF SYDNEY
Rm 519, F11 | The University of Sydney | NSW | 2006
T +61 2 9351 2180  | F +61 2 9351 3329  | M +61 415 274104
E matthew.todd@sydney.edu.au | W
http://sydney.edu.au/science/people/matthew.todd.php
W http://opensourcemalaria.org/ | W http://opensourcetb.org/ | W
http://opensourcepharma.net/

CRICOS 00026A
This email plus any attachments to it are confidential. Any unauthorised
use is strictly prohibited. If you receive this email in error, please
delete it and any attachments.

**Comment by mattodd** [comment]
File received. Closing.
