### ISSUE TITLE
Retrieving the data from the spreadsheet for script and webservice

### ISSUE THREAD

**Issue by lpatiny** [OpenSourceMalaria/OSM_To_Do_List#331]
It would be nice to get the information from the google docs directly from a script and webservice.

We should also be able to retrieve molfile and predicted values for further processing.

**Comment by lpatiny** [comment]
A first project has been down allowing to retrieve the information directly from a node or iojs application thanks for a npm module.



https://www.npmjs.com/package/osm-lookup

Here is an exemple of the code required to retrieve some information from the google spreadsheet

https://github.com/cheminfo/osm-lookup/blob/master/test.js

**Comment by drc007** [comment]
Looks interesting, will have to have a look in more detail

Chris

**Comment by lpatiny** [comment]
Webservice are available from the following links (they could change in the future ...)

Retrieve all the info as a JSON:
http://nodejs.epfl.ch/osmLookup

Retrieve all the info for a specific entry as a JSON
* http://nodejs.epfl.ch/osmLookup?id=OSM-S-271
or
* http://nodejs.epfl.ch/osmLookup/OSM-S-271

Retrieve a specific field (you may use any of the column names)
* http://nodejs.epfl.ch/osmLookup?id=OSM-S-271&field=molfile
* http://nodejs.epfl.ch/osmLookup?id=OSM-S-271&field=smiles
or
* http://nodejs.epfl.ch/osmLookup/OSM-S-271/molfile
* http://nodejs.epfl.ch/osmLookup/OSM-S-271/smiles
* http://nodejs.epfl.ch/osmLookup/OSM-S-271/InChI
* http://nodejs.epfl.ch/osmLookup/OSM-S-271/oclLogP
