### ISSUE TITLE
Structures missing

### ISSUE THREAD

**Issue by drc007** [OpenSourceMalaria/OSM_To_Do_List#335]
There are a couple of rows without structures on the Google spreadsheet
https://docs.google.com/spreadsheets/d/1Rvy6OiM291d1GN_cyT6eSw_C3lSuJ1jaR7AJa8hgGsc/edit#gid=510297618 

MMV669543
MMV669849
MMV669850
MMV670767
MMV676963

Rows with no MMV number or structure

OSM-S-56
OSM-S-66
OSM-S-67

Some appear to be on this page http://malaria.ourexperiment.org/biological_data/8540/Inherited_Data_on_Series_4_Amides.html

Anyone fancy doing a little detective work to find the remaining structures?

**Comment by mattodd** [comment]
Hi @tyzhengsydney - you're good at this. Want to have a go?

**Comment by drc007** [comment]
Also noted that we have two rows labeled OSM-S-271, OSM-S-142, OSM-S-38

**Comment by lpatiny** [comment]
Fix SMILES that could not be parsed:
OSM-S-10 : extra space at the end of the SMILES code

**Comment by lpatiny** [comment]
We have problems with the following SMILES:
OSM-S-101 : there are @ in the code that should not be there. It should only be used for chirality in [ ]

**Comment by mattodd** [comment]
Fixed OSM-S-101, problem derived from [here](http://malaria.ourexperiment.org/osm_procedures/7184/Preparation_of_OSMS101.html)

Looks like you've fixed OSM-S-5, -10 and -35, @lpatiny 

Fixed duplicate OSM-S-271 (MMV675963)
Fixed duplicate OSM-@-142
Looks like OSM-S-38 only has one entry now.

OSM-S-56 may not have an MMV number assigned. Has strings.
OSM-S-66 now has strings
OSM-S-67 now has strings

Supplied strings to:
MMV669543
MMV669849
MMV669850
MMV670767

MMV676963 is coming up a blank for me in the sheet, so may have been deleted.

Closing. Thanks for flagging.
