### ISSUE TITLE
Competition for Making a Graphical Abstract

### ISSUE THREAD

**Issue by alintheopen** [OpenSourceMalaria/OSM_To_Do_List#336]
[Open Source Malaria (OSM)](http://opensourcemalaria.org/) is a consortium of researchers who are trying to find a new medicine for malaria in a new way...we're working in 'the open’, sharing all of our experiments and results on the internet and anyone can take part.

Because we’re open, communication of our work is especially important and now we need some help from talented artists. 

**What's Needed**
OSM needs a graphical abstract image for its first paper, which is ready for submission to a journal. **We’re offering a cash prize** for the best and we hope this might be the first of many collaborations between artists and scientists!

The paper describes how we made a number of molecules, and the measurement of the ability of those molecules to kill the parasite that causes malaria. All the data and ideas involved in the project have been publicly available throughout. Many people have contributed from around the world (47 authors, 8 countries) including an undergraduate lab class. The molecules we discovered were very capable of killing the parasite, but didn’t quite perform well enough in a malaria-infected mouse to proceed any further. Maybe someone in the future will take the OSM data and find a way round this problem.

The text of the paper’s abstract is shown below. We need one graphical image to capture this paper in spirit. i.e. to convey that the paper is about molecules [these ones](http://openwetware.org/wiki/OpenSourceMalaria:GSK_Arylpyrrole_Series), that the project adhered to open source principles, and that the worldwide community was able to participate in the research as it was happening. The Six Laws of the consortium are [here](http://openwetware.org/wiki/Open_Source_Research).

In order to convey the spirit/story of the paper, there are certain things that MUST be included in the design:
1. A representation (in some form) of the molecule [OSM-S-5](http://malaria.ourexperiment.org/osm_procedures/7054/Preparation_of_OSMS5.html)
2. An image of/allusion to the [electronic lab notebook](http://malaria.ourexperiment.org/?allblogs), which is where people can find all the data
3. A sense of sharing data between multiple people around the world in real time

There are some existing OSM images shared in [this repo](https://github.com/OpenSourceMalaria/OSM_Website_Code/tree/master/images), such as OSM’s logo, which can be used if you like.

We're an open project and so this is an open art prize, which means that the rules might sound a little unusual. But here they are:

**Rules:**
1. Submissions must be public, as must all source files used to make the image.
2. The license governing all submissions must be [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/).
3. Anyone else is free to take those files and rework them into their own image after the competition. Files can be uploaded anywhere where such reuse is possible, but we have a [Github repository](https://github.com/OpenSourceMalaria/OSMSeries1Paper1/tree/master/Graphical%20Abstract) that can be used.
4. If files are uploaded before the deadline, other entrants can use those files and incorporate them into their own entry but the prize will be split accordingly.
4. The submitter of the winning image must be willing after the close of the competition to alter the final image into a form (size, format) that is acceptable to the journal where the article is to be submitted. Here are some [example guidelines](http://journals.plos.org/plosmedicine/s/figures) 

**Deadline:** August 21st 2015 at 5pm Sydney Time, which is [these times](http://www.timeanddate.com/worldclock/meetingdetails.html?year=2015&month=8&day=21&hour=7&min=0&sec=0&p1=240&p2=176&p3=87&p4=136&p5=179&p6=224) elsewhere.

**Prize money:**
Winning Image $600 (even if we don’t end up using it as it is)
Two other key contributors: $100 each

Judges will be Mat Todd (OSM), Alice Williamson (OSM), [Justine Alltimes](http://www.childrenslaureate.org.au/about/#team) (works in children's publishing and is the project manager for the Australian Children's Laureate) and 2 other members of the Open Source Malaria Consortium who are authors on the paper.

To get a further feel for the paper, here is the accompanying abstract text: 

Abstract Text
The development of new antimalarial compounds remains a pivotal part of the strategy for malaria elimination. Recent large-scale phenotypic screens have provided a wealth of potential starting points for hit-to-lead campaigns. One such public set is explored, employing an open source research mechanism in which all data and ideas were shared in real time, anyone was able to participate and patents were not sought. One chemical sub-series was found to exhibit oral activity but contained a labile ester that could not be replaced without loss of activity, and the original hit exhibited remarkable sensitivity to minor structural change. A second sub-series displayed high potency, including activity within a late stage gametocyte assay, but at the cost of low solubility. As an open source research project, unexplored avenues are clearly identified and may be explored further by the community; new findings may be cumulatively added to the present work.

Good Luck!

**Comment by ryancoleman** [comment]
Hey, just a thought, some people may want to use actual chemical structures from the series you found. Since the project is open, these are probably out there, but a sample structure might be helpful.

**Comment by mattodd** [comment]
Hi Ryan - sure. These are linked in the announcement above, e.g. for the molecule OSM-S-5, and there are lots of structures on the wiki. Is that what you mean?

**Comment by ryancoleman** [comment]
Hi, missed the links, feeling a bit silly!

**Comment by alintheopen** [comment]
Don't feel silly! Thanks for checking it out Ryan :)

**Comment by drc007** [comment]
Image of molecule that could be included.
![osm](https://cloud.githubusercontent.com/assets/7080516/8951135/41332000-35c2-11e5-9810-567265ab3e56.png)

**Comment by alintheopen** [comment]
Thanks Chris! Entrants should also feel free to draw there own representation of 'flat' or 3D chemical structures.

**Comment by vsitaraman** [comment]
Just made a pull request with my submission on behalf of [Draw Science](http://drawscience.org)!
https://github.com/OpenSourceMalaria/OSMSeries1Paper1/pull/1

**Comment by merindajayne** [comment]
Hi, Just wondering where i submit my graphic? and what file type?

**Comment by alintheopen** [comment]
Hi Merinda,

You can upload your file as a PNG here or push a file to the repository or
you can post a link to a Dropbox folder containing your entry. We would
prefer it if you could share all file types if possible, e.g. photoshop and
also an image file that anyone can open!

Thanks

Can't wait to see it!

Alice :)

On Wednesday, August 12, 2015, merindajayne <notifications@github.com>
wrote:

> Hi, Just wondering where i submit my graphic? and what file type?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/336#issuecomment-130155549>
> .
>


-- 
Alice Williamson | Postdoctoral Research Associate and Postdoctoral
Teaching Fellow
School of Chemistry | Faculty of Science

THE UNIVERSITY OF SYDNEY
Lab 528, F11 | The University of Sydney | NSW | 2006
E alice.williamson@sydney.edu.au <matthew.todd@sydney.edu.au>  | W
www.opensourcemalaria.org
T @all_isee

**Comment by merindajayne** [comment]
Hi,
Please find attached my entry for the Open Source Malaria Graphic Competition.
Hope you like it :)
Merinda 


![graphic](https://cloud.githubusercontent.com/assets/13759286/9216904/e3f47c7a-4103-11e5-9938-43886821bfa2.png)

**Comment by merindajayne** [comment]
Hi,
Please find attached my entry for the Open Source Malaria Graphic Competition.
Hope you like it :)
Merinda
![graphic](https://cloud.githubusercontent.com/assets/13759286/9216995/6284e3ee-4105-11e5-95c9-5dcb07c806d5.png)

**Comment by alintheopen** [comment]
Thanks Merinda!

Wonderful :)

On Wednesday, August 12, 2015, merindajayne <notifications@github.com>
wrote:

> Hi,
> Please find attached my entry for the Open Source Malaria Graphic
> Competition.
> Hope you like it :)
> Merinda
> [image: graphic]
> <https://cloud.githubusercontent.com/assets/13759286/9216995/6284e3ee-4105-11e5-95c9-5dcb07c806d5.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/336#issuecomment-130171524>
> .
>


-- 
Alice Williamson | Postdoctoral Research Associate and Postdoctoral
Teaching Fellow
School of Chemistry | Faculty of Science

THE UNIVERSITY OF SYDNEY
Lab 528, F11 | The University of Sydney | NSW | 2006
E alice.williamson@sydney.edu.au <matthew.todd@sydney.edu.au>  | W
www.opensourcemalaria.org
T @all_isee

**Comment by merindajayne** [comment]
no worries, Your welcome :)

**Comment by vsitaraman** [comment]
When will you announce your decision? Thanks a ton!

**Comment by mattodd** [comment]
Hi @merindajayne  - would you be able to shoot me an email so we can arrange a funds transfer? matthew.todd@sydney.edu.au

**Comment by mattodd** [comment]
Results announced, so closing.
http://malaria.ourexperiment.org/the_osm_blog/8245/And_the_winner_is__Announcement_of_OSM_Graphical_Abstract_Competition_Winners.html
Thank you everyone!
