### ISSUE TITLE
New tool for 3D conformations exploration

### ISSUE THREAD

**Issue by lpatiny** [OpenSourceMalaria/OSM_To_Do_List#337]
Just added a new tool on the website: 3D MODELS

It allows to generate possible conformation and to quickly check if there is some hydrogen bonds.

http://www.cheminfo.org/flavor/malaria/3D_models.html

To check a distance double click on an atom and then double click on another atom.

You can also check angles:
* double click, single click, double click
* double click, single click, single click, double click

**Comment by mattodd** [comment]
@lpatiny that's wonderful!
