### ISSUE TITLE
First Year project student (TSP) targets for OSM

### ISSUE THREAD

**Issue by alintheopen** [OpenSourceMalaria/OSM_To_Do_List#338]
The OSM team is lucky to have three more members this semester: Christina Xia, Tom York and Ben Xie.

The guys are going to be working on the synthesis of three triazolopyrazine targets and maybe some other compounds if we have time.

![tsp compounds sem 2 2015](https://cloud.githubusercontent.com/assets/2626599/9102119/352de256-3c32-11e5-852d-fea92a04fd2a.png)

*Christina*
OC(C1=CC=CC=C1)COC2=CN=CC3=NN=C(C4=CC(OCO5)=C5C=C4)N32
InChI=1S/C20H16N4O4/c25-15(13-4-2-1-3-5-13)11-26-19-10-21-9-18-22-23-20(24(18)19)14-6-7-16-17(8-14)28-12-27-16/h1-10,15,25H,11-12H2

*Tom*
OC(C1=CC=CC=C1)COC2=CN=CC3=NN=C(C4=C(C=CC=C5)C5=CC=C4)N32
InChI=1S/C23H18N4O2/c28-20(17-8-2-1-3-9-17)15-29-22-14-24-13-21-25-26-23(27(21)22)19-12-6-10-16-7-4-5-11-18(16)19/h1-14,20,28H,15H2

*Ben*
OC(C1=CC=CC=C1)COC2=CN=CC3=NN=C(C4=CC(F)=CC(F)=C4)N32
InChI=1S/C19H14F2N4O2/c20-14-6-13(7-15(21)8-14)19-24-23-17-9-22-10-18(25(17)19)27-11-16(26)12-4-2-1-3-5-12/h1-10,16,26H,11H2

**Comment by mattodd** [comment]
Related compounds (no OH) [have been sent for evaluation](http://malaria.ourexperiment.org/biological_data/13775), so closing this.
