### ISSUE TITLE
Volunteer Request: Submitting Proposal to Lilly OIDD Synthesis

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#341]
There is a new facility being offered by the Open Innovation guys at Lilly, involving automated synthesis: [Overview](https://openinnovation.lilly.com/dd/what-we-offer/synthesis.html) and [User Guide](https://openinnovation.lilly.com/dd/docs/Protected/Website_Usage_Training_Materials/6_OIDD_Training_Guide_VI_Creating_a_Synthesis_Proposal.pdf)

This might be useful for OSM, e.g.:
1) Optimising a troublesome synthetic step
2) Making some analogs <-- particularly this, if it's possible.

**Would anyone like to act as primary contact point with Lilly to draft up some work for them to try on Series 4?** i.e. to submit a proposal to them for something? Suggestions/refinement can come from the wider OSM community before submission, but someone needs to be the driver and prepare the proposal on behalf of us all.

A key uniqueness of Lilly interacting with OSM would obviously be that we could easily share with the wider world a case study of the capabilities of their system. This is useful PR, potentially.

Public contact email: openinnovation@lilly.com but I imagine this works better if someone already has a contact there? Anyone?

**Comment by MedChemProf** [comment]
Mattodd,
I have been following the OpenSourceMalaria project from a distance for awhile now. I also have a very small antimalarial project ongoing in my lab. I have been a member of of the Lilly Open Innovation Drug Discovery (OIDD) collaboration for a number of years and I have submitted my own compounds to the lab. If possible, I would be willing to take point on the submission of compounds to their new automated synthesis group. I have already been looking into this anyway with some work that I had been doing in my own lab. Please let me know how you might like to proceed if you would like my help. Chase Smith (MCPHS University)

**Comment by mattodd** [comment]
Hi @MedChemProf 
That's fantastic, thanks. I think the idea is that we would, as a group, work out what synthetic steps or compounds could benefit from a synthetic blitz. We can do that in the coming week or so together. Then we would need someone to take those ideas and funnel them into the OIDD synthesis call, which is to say just formulate the ideas in a way (document or other files, put into the web/email submission they use) that is appropriate to Lilly, and then to act as contact point. i.e. it's essentially the crucial bit of translation from needs to submission. This would be very useful. Are you happy to do so?

At some point it will need to be explained that OSM is different, in the sense that any OIDD inputs we receive will go into the public domain. I expect this will be fine, but it needs to be made clear up front. I just spoke with someone an hour ago about this at the conference I'm at. I may have a contact we could use at Lilly too, which might help with this extra explanation part.

**Comment by MedChemProf** [comment]
Sounds good. The OIDD personnel are good at replying to requests for information. They have always responded to my emails within one day with an answer. I can send a preliminary email asking if there needs to be something new worked out since the compounds would not be coming from the university with which the OIDD has a material transfer agreement. They may have seen this sort of request in the past.

**Comment by mattodd** [comment]
Have just been in touch with OIDD by email and am hopeful we'll receive a contact there and some comments on what kinds of things they'd be happy to support. When I have that, we can plan more fully. Will write more here as soon as I have that.

**Comment by MedChemProf** [comment]
Prior to reading your last comment I had sent in an email with a few general questions about working with the OIDD. I just received a response which is pasted below. Please let me know how to proceed. Thanks.

"The OIDD Team is excited about the potential opportunities ahead. The Director of OIDD, the OIDD Medicinal Chemist, and the OIDD Neglected and Tropical Disease Chemist would like to schedule a teleconference with you to discuss the best possible way to move forward. The OIDD Director is leaving on an extended business trip, so the earliest we would be able to schedule the teleconference would be the second week in October. Would you be interested in scheduling a teleconference with the Lilly scientists? "

**Comment by mattodd** [comment]
Yes, that's perfect, great. Would you be happy to assess convenient times for them and you? If you were able to set this up so I could join, then I will (e.g. 9 a.m. New York is 11 p.m. Sydney which would be OK), but I'm happy for you to go ahead alone and discuss since we can establish clearly all the issues/questions beforehand.

The one thing perhaps we could clarify with the OIDD guys is whether they foresee the main area of collaborative interactions as being in 1) Optimising troublesome chemical steps or 2) Analog synthesis using an established procedure? If we could decide this, based on their advice, we can plan where best to deploy resources. If they have no preference, so be it. Some of the relevant chemistry can be forwarded to them from the wiki:

http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Synthetic_Chemistry

i.e. to highlight the general kinds of steps/compounds involved. i.e. small molecule heterocyclic chemistry.

One area I was hopeful about was this: What about if we sent OIDD 100 mg of a "typical" Series 4 compound - an active compound that is structurally simple? Could they do some late stage functionalisation of this compound - i.e. subject it to some oxidation/halogenation etc conditions that might generate a few mg of 5 derivatives that could be characterised and sent for biological evaluation? This is a fast way of obtaining new compounds in a divergent fashion, but is only really practical with some expensive kit and some "go-to" chemistry for this kind of work.

**Comment by MedChemProf** [comment]
I would be more than happy to work out the details of the meeting. At the moment, they have proposed an online meeting on either Monday, October 12th or Thursday, October 22nd. They have further suggested the meeting times be early in the afternoon on Eastern Standard Time. I am going to request that we move the meeting time to as late in the afternoon as convenient for them in order for you to join in (very early in the morning the next day for you.) Since the meeting is not until October 12th at the earliest, we have sufficient time to generate a list of questions in order to make any discussion productive.

     I like your suggestion on the late stage functionalization chemistry, especially if they are able to perform chiral resolution on analogs is so generated. While in industry however, I spent quite a bit of time working with high throughput synthesis chemists and they seemed to prefer exploding chemical series starting from a common intermediate and established chemistry. We will have to discuss as well as hear them out on their preferences.

     The OIDD also has an in silico evaluation step to QC any proposed compound to determine if it fits within the Lilly library of compounds. I do not know if this is the same with their Neglected Tropical Disease group which will also be at the meeting.

      In any case, I will notify the OSM group as soon as I learn the details of the meeting.

**Comment by MedChemProf** [comment]
The web meeting with Lilly is set up for Thu 10/22/2015 at 2:00PM EST. I had them send you an invite, but it will be awfully early in the morning for you. Please let me know how the group can arrange a pre-meeting in order to plan for the discussion and relay the group's main goals to the OIDD.

**Comment by mattodd** [comment]
Yes, I saw that! 5am for me I think.
How about a pre-meeting by online TC at 6:30pm Boston time Tuesday Oct 6th, which is 9:30 a.m. Wed Oct 7th in Sydney?
Alternatively 7:30 a.m. Boston time Wed Oct 7th which is 10:30 pm Wed Oct 7th in Sydney. 
Not ideal, but both are possible for me.
Here is the timezone comparison
http://www.timeanddate.com/worldclock/meetingtime.html?iso=20151007&p1=240&p2=43
Feel free to suggest alternatives.
Anyone else listening to this conversation is welcome to join if they'd like to suggest ways in which we might best tap into the OIDD hardware.

**Comment by MedChemProf** [comment]
The online TC at 6:30pm Boston time Tuesday Oct 6th works best for me. I have a previously scheduled appointment on the 7th that I cannot move. The time and date are on my calendar.

**Comment by mattodd** [comment]
Perfect, done. Whichever of us gets round to it first can make a Google hangout link and post it here, else we can Skype but that's less good for anyone else wanting to join us.
Thanks for pursuing the Lilly discussion. This could be an important development for the project.

**Comment by MedChemProf** [comment]
I believe that I have created a Google Hangout for the meeting on Tuesday, October 6th at 6:30PM EST. Would anyone more familiar with Google Hangouts please let me know if I have done this correctly and made it Public for any to join. I appreciate the double check. Thank you in advance.

**Comment by mattodd** [comment]
Looks good to me. Could you post the link here that people need to click to join? We can then disseminate via other places too.

**Comment by MedChemProf** [comment]
I cannot seem to find the link to post in Hangouts. Any help appreciated.

**Comment by mattodd** [comment]
OK, I believe it's this?
https://plus.google.com/hangouts/_/event/cn8u130g158ifdul1rpc6fmqi84?hl=en-GB&authuser=0

**Comment by mattodd** [comment]
Will be there a few minutes late.

**Comment by MedChemProf** [comment]
No problem. The link for any others is: https://hangouts.google.com/call/tfikivm3nk64z2pbygkfqx6mhma

**Comment by MedChemProf** [comment]
@mattodd @alintheopen - I was reviewing my notes earlier today in preparation for the OIDD Meeting on Thursday and I thought I would ask if anyone had any additional questions that they would like me to discuss with Lilly. Please let me know. Thanks.

**Comment by mattodd** [comment]
I can't think of anything. The requests we've discussed before centered around analog synthesis (great), methodology blitzing (pretty great) or late stage functionalisation (super great) are all of interest, but there needs to be benefit to everyone here - I'm happy for Lilly to recommend something if they'd like to showcase a particular method/capability publicly. We need to do what we're doing openly - it'd be hard to look at chemistry where we're not able to report outcomes because of lots of secrecy surrounding the methodology. Not a deal breaker (e.g. late stage functionalisation using secret method giving rise to compounds that may be shared in full - still useful) but just undesirable.
Really looking forward to catching up with you after the call.

**Comment by MedChemProf** [comment]
Attached are my notes from the Lilly OIDD teleconference. Please let me know if you have any problems opening the attached document. The meeting went very well and the automated synthesis laboratory capabilities are much more extensive than we discussed previously.  I was as complete as possible in my notes, but please let me know if you have any follow-up questions or if you need any clarifications.
[OIDD Teleconference.pdf](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/18999/OIDD.Teleconference.pdf)

**Comment by mattodd** [comment]
Chase, that's incredibly helpful in understanding what we can do.
So as a starting point we ought to get together a list of Series 4 compounds to be screened in silico? This is obviously trivial given the [spreadsheet](http://tinyurl.com/OSM-Compounds), but is that the next step?
Interesting comment about this working better with a dedicated operator who is not a prof. I guess we need someone to step into that role and guide the science.

**Comment by MedChemProf** [comment]
From my understanding of the whole process, I suggest that the next series of steps should be followed:

1) Download the attached OIDD Program Agreement and begin the process of obtaining the requisite signatures at your university. The 'Authorized Representative' of the university will be someone able to represent the university as a whole (Dean, Provost, etc.). You will probably want yourself to be the 'Affiliation Coordinator of the Institution'. The Affiliation Coordinator will oversee the OIDD account and has the ability to add individual users that want to submit materials to the OIDD.

2) Submit the signed agreement and create your account. This will also give you some exposure to the OIDD web interface and give your a better understanding of the next steps.

3) Once the agreement is in place and an account is created, then compound structures can be uploaded (or added individually) and then submitted for in silico evaluation. Once the 20 molecule threshold is exceeded, then the library proposal can be initiated.

4) The OSM would design a synthetic route appropriate to achieve the synthesis of the desired molecules that passed the in silico screening. The OSM would then complete the 'Synthesis Questionnaire' and the 'Reagent List' and submit to the ASL. I have attached both forms for you to inspect.

5) Once the library proposal is approved, you will then need to sign an additional agreement known as the 'ASL Agreement'. ASL Agreements are prepared on a case-by-case basis after the OIDD Synthesis Proposal has been approved.

6) Following approval and agreement signing, then the designated scientist would work with the ASL to be trained and then carry out the remote synthesis.

I am hoping this helps. Please reach out to me if you need any clarification or additional details. Finally, I have attached a fourth document which summarizes the operation of the ASL. :)

[OIDD-Program-Agreement-2015-Global.pdf](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/19542/OIDD-Program-Agreement-2015-Global.pdf)
[asl_questionnaire.docx](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/19552/asl_questionnaire.docx)
[asl_reagent.docx](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/19553/asl_reagent.docx)
[What-is-ASL.pdf](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/19554/What-is-ASL.pdf)

**Comment by mattodd** [comment]
OK, great advice, Chase. I'm sending the program agreement to USyd's legal people to see what they say.

**Comment by mattodd** [comment]
Based on two emails I received yesterday and today, the Lilly OIDD program is being closed down in Q1 2019, so I'm closing this Issue. Thanks @MedChemProf for all the initial effort here. To avoid orphaning, I'll install [a link to this Issue in the Tech Ops wiki](https://github.com/OpenSourceMalaria/TechOps/wiki/External-Open-Innovation-Platforms) about how we source chemical compounds. There may be other related schemes in the future with which we might want to interact.
