### ISSUE TITLE
Adding GSK PRR data and codes to the main sheet

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#345]
Hey @minkyungchong - do you have time for a short piece of data entry?

We need the data on [this page](http://malaria.ourexperiment.org/biological_data/13274) added to the [Master Sheet](https://docs.google.com/spreadsheets/d/1Rvy6OiM291d1GN_cyT6eSw_C3lSuJ1jaR7AJa8hgGsc/edit#gid=510297618). Specifically:

1) Can you make sure the 6 relevant compounds are actually in the sheet, along with the OSM and MMV codes, and their strings?
2) Can you add in the rate of killing (i.e. "slow", "moderate" etc) into the new column I created, column N
3) GSK re-measured the potencies of these compounds before doing the assay. These data need to go into column I - I think that you will just need to separate the new numbers from the old numbers with a comma and a space, but @lpatiny or @drc007 may think differently...

These compounds are all Series 1, so please put that into column F if needed. We're actually going to need a push on Series 1 in the short term, but this is a good place to start since we have just acquired these data.

Thank you!

**Comment by minkyungchong** [comment]
Hi
I've added 6 compounds to the list and GSK values based on the GSK PRR OSM Report,.
Hut I'm not sure what you meant by 'old' GSK values because I could only see one set of Pfal IC50 values in the report

**Comment by mattodd** [comment]
Ah @minkyungchong - you've added duplicate entries for these compounds. First thing to do, at the start, is to check if the compounds you're entering are already in the sheet (increasingly common as the dataset grows) and it looks like they are. You can do a quick search by eye using the OSM codes, or a comprehensive search on the sheet using e.g. SMILES.

So... could you take the data you added in and combine it with any data already in there for these compounds, please, to make sure we only have one (complete) record for each?

Actually it's looking to me like these compounds still don't have any values for potency already in there, right? So:

The “old” GSK potencies come from:

http://malaria.ourexperiment.org/biological_data/1438

for OSM-S-5 0.818 

and

http://malaria.ourexperiment.org/biological_data/2722

for

OSM-S-35 0.036
OSM-S-37 0.028
OSM-S-39 0.007
OSM-S-51 0.309

Could you quickly check these are right, and add the data into column I?


The values for OSM-S-10 are from other sources:

0.201 from Ralph (http://malaria.ourexperiment.org/biological_data/1389) please put into the new column N

0.176 from Avery (http://malaria.ourexperiment.org/biological_data/1393) please put into the new column L

0.361 from Avery (http://malaria.ourexperiment.org/biological_data/1393) but against K1 strain, so column M

But while we’re at it, we should add in other potency data that we have for these six compounds. Could you please check that the following potencies are correct, and then put them in the relevant columns?

OSM-S-5
0.610 from Ralph (http://malaria.ourexperiment.org/biological_data/1389) Column N
0.404 from Avery (http://malaria.ourexperiment.org/biological_data/1393) Column L

OSM-S-35:
0.011 Ralph (http://malaria.ourexperiment.org/biological_data/3152) Column N
0.026 Avery (http://malaria.ourexperiment.org/biological_data/2430) Column L
0.038 Avery (http://malaria.ourexperiment.org/biological_data/6734) Column L

OSM-S-37
0.009 Ralph (http://malaria.ourexperiment.org/biological_data/3152) Column N
0.015 Avery (http://malaria.ourexperiment.org/biological_data/2430) Column L
0.161 Guy (http://malaria.ourexperiment.org/biological_data/11103) Column O
0.176 (against strain K1) Guy (http://malaria.ourexperiment.org/biological_data/11103) Column P

OSM-S-39
0.005 Ralph (http://malaria.ourexperiment.org/biological_data/3152) Column N
0.001 Avery (http://malaria.ourexperiment.org/biological_data/2430) Column L

OSM-S-51
0.442 Ralph (http://malaria.ourexperiment.org/biological_data/3152) Column N
0.307 Avery (http://malaria.ourexperiment.org/biological_data/2430) Column L

Thank you! This is all part of the important process of tidying up Series 1. A bunch of other data are missing from the sheet (you may notice this as you’re going through!). We’ll try to deal with this systematically, but let's manage the above data for now.

**Comment by minkyungchong** [comment]
All done!

**Comment by mattodd** [comment]
Wonderful, thanks. The InChIKey entries in column E are highlighted yellow for these compounds - is there a reason?

**Comment by minkyungchong** [comment]
Oh just flagged it so you could find it easier! I'll undo them now.
Also, the SMILES for some compounds were different to the one on the
website that you linked me to.
The SMILES that's in the spreadsheet now were the ones that were already in
the spreadsheet before I added additional data.
I guessed that they were the same molecules just wrote in different way, is
that right?

**Comment by mattodd** [comment]
Yes, that's right - the SMILES can be slightly different depending on how things are drawn. It's one of the problems with that string and one of the reasons we use multiple strings. See this too http://malaria.ourexperiment.org/the_osm_blog/8550
Closing now. Thanks for this, Min!
