### ISSUE TITLE
Single Link in ChemInfo Page for Series 1 Compounds for Paper

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#348]
Hi @lpatiny - the [OSM molecule database](https://docs.google.com/spreadsheets/d/1Rvy6OiM291d1GN_cyT6eSw_C3lSuJ1jaR7AJa8hgGsc/edit#gid=510297618) (which I have tinyURL'd finally to http://tinyurl.com/OSM-Compounds) nearly contains all the data for Series 1, the subject of OSM's first proper paper. Some final strings are being added by @jhon4903 and @minkyungchong and then we'll add in biological data.

In the manuscript we mention that the data for all compounds may be browsed "live". Is there a way of including a stable URL so that readers may visit the ChemInfo page for Series 1? Or how might you describe to a casual reader how to browse the dataset within ChemInfo? Should we direct them to the malaria page and say that they can filter on Series 1? That might be cleaner, but happy to be guided by you.

**Comment by drc007** [comment]
People could either filter the dataset in whichever client they are using to view the data, or they could create their own Google spreadsheet with just the data they want to access and then modify the script to access it?
Linking to Malaria page would probably be the easiest to maintain long term since you could provide a variety of "download" options.

**Comment by mattodd** [comment]
Yes, I'm thinking of the long term picture since I'd like any links we use
to have a half-life approximating to that of the published article. I'm
being aspirational.

**Comment by drc007** [comment]
You could also mention that we decided to store molecular information in plain text formats for exactly that reason. We should be able to always read text whilst we cannot guarantee being able to read a proprietary binary file format.

**Comment by lpatiny** [comment]
For a publication the data are not expected to change anymore. I can retrieve the data at a specific time and save it directly in a new view. We can then create a small URL so that you can cite it.
When you plan to submit the paper ?

**Comment by drc007** [comment]
A downloads page could also include things like pharmacophore models people have built together with the actual data used to generate the model etc. Any analysis on metabolism etc...

**Comment by lpatiny** [comment]
It is not a problem to add a download link in tab-delimited format of SDF format

**Comment by alintheopen** [comment]
I wonder if it is OK for the data to change for this publication. We have
provided all of the 'normal' data as part of the paper, which will be
captured as a pdf. I think having 'living' data to accompany the paper
could be a positive thing.

**Comment by drc007** [comment]
You could of course provide both, a static dataset described in the paper, and a link to a live update.

**Comment by lpatiny** [comment]
I just added a new domain in order to keep links short
http://malaria.cheminfo.org
I will create
http://malaria.cheminfo.org/series1 that will point to a static page

**Comment by mattodd** [comment]
Thank you for the above. Yes a static snapshot version is useful as SI for a paper (archived at a journal) but one key distinguishing feature of this project is that the ELNs and datasets are "live". Having both is nice, and it's the permanence/simplicity of the "live" URL that can ultimately help maintain the connection between them. If someone is reading the paper in 5 years' time it helps if the link (to the live dataset, which may now contain many more molecules vs the snapshot) still works. Hard, I know.

**Comment by lpatiny** [comment]
After updating the layout of the data page to make it more clear I also added the possibility to filter the data from a URL parameter.
In order to site the data of series 1 you may just use the following URL:
http://malaria.cheminfo.org/Display_data.html?series=1

**Comment by lpatiny** [comment]
In the page:
http://malaria.cheminfo.org/Display_data.html?series=1
I just added the "Download SDF" in the bottom right.
PLEASE submit this SDF with the paper as a supplementary. Like that all the data will really be fixed and it is the Publisher that should keep it available for ever ...
The link itself will stay alive if there is any new biological result or any mistake that is fixed.

**Comment by mattodd** [comment]
Great stuff @lpatiny , will do that - this is very useful and exactly what I was meaning.
