### ISSUE TITLE
Download SDF and tab-delimited files

### ISSUE THREAD

**Issue by lpatiny** [OpenSourceMalaria/OSM_To_Do_List#349]
http://www.cheminfo.org/flavor/malaria/Display_data.html

Allows not only to display and filter the data but also to download all the structures as a SDF or a tab-separated value file (TSV) for further processing in other programs (top right of the screen).

In the file there is also predicted logP, logS, PSA and the number of H donor, H acceptor, molecular weight, exact mass, molecular formula, number of rotatable bonds and number of stereocenters. Those are calculated with openchemlib-js, another MIT project in which we are involved: https://github.com/cheminfo/openchemlib-js

**Comment by mattodd** [comment]
Very nice @lpatiny ! The calculation of logP directly from the strings ought, I'm guessing, to fix a slight [issue we'd found with calculation of that value using Chemdraw](http://malaria.ourexperiment.org/the_osm_blog/11283/Chemdraw_LogP__CLogP_Calculation_Issues.html) where the outcome depended on how you drew the molecules. @alintheopen

**Comment by mattodd** [comment]
Hi @lpatiny before I take the snapshot I just wanted to check that the SDF captures everything in the [Master Sheet](http://tinyurl.com/OSM-Compounds)? We've a nice manually curated column for mean potency now (column U). Am I right in thinking that will be captured? It's the primary value that a med chemist would want to see upon browsing the dataset in Cheminfo (along with structures, obv).

**Comment by lpatiny** [comment]
@mattodd You should not be afraid to open the SDF in a text editor to check what there is inside. It is relatively "readable". Here is a small extract of the first product, please check if everything is there 
```

Actelion Java MolfileCreator 1.0

 31 34  0  0  0  0  0  0  0  0999 V2000
    3.2215   -2.6160   -0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.8147   -1.7024   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.3147   -0.8364   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.6456   -0.0933   -0.0000 S   0  0  0  0  0  0  0  0  0  0  0  0
    4.3092   -0.7319   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.7160    0.1817   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.6941    0.3896   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.4373   -0.2796   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.7987    1.3841   -0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    4.8851    1.7908   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.6772    2.7690   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.2160    1.0477   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.6647    1.8841   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.5307    1.3841   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.3967    1.8841   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.3967    2.8841   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    9.2628    3.3841   -0.0000 S   0  0  0  0  0  0  0  0  0  0  0  0
    9.7628    2.5181   -0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   10.1288    3.8841   -0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    8.7628    4.2501   -0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    7.5307    3.3841   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.6647    2.8841   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.8366   -1.4945   -0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    1.7321   -0.5000   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8660   -0.0000   -0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000   -0.5000   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8660    0.0000   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.7321   -0.5000   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.7321   -1.5000   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8660   -2.0000   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0000   -1.5000   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  2  1  2  0  0  0  0
  3  2  1  0  0  0  0
  4  3  1  0  0  0  0
  5  3  2  0  0  0  0
  6  5  1  0  0  0  0
  7  6  2  0  0  0  0
  8  7  1  0  0  0  0
  9  7  1  0  0  0  0
 10  9  1  0  0  0  0
 11 10  1  0  0  0  0
 12 10  2  0  0  0  0
 12  6  1  0  0  0  0
 13  9  1  0  0  0  0
 14 13  2  0  0  0  0
 15 14  1  0  0  0  0
 16 15  2  0  0  0  0
 17 16  1  0  0  0  0
 18 17  2  0  0  0  0
 19 17  1  0  0  0  0
 20 17  2  0  0  0  0
 21 16  1  0  0  0  0
 22 21  2  0  0  0  0
 22 13  1  0  0  0  0
 23  2  1  0  0  0  0
 24 23  1  0  0  0  0
 24  4  1  0  0  0  0
 25 24  2  3  0  0  0
 26 25  1  0  0  0  0
 27 26  2  0  0  0  0
 28 27  1  0  0  0  0
 29 28  2  0  0  0  0
 30 29  1  0  0  0  0
 31 30  2  0  0  0  0
 31 26  1  0  0  0  0
M  END
>  <OSM>
OSM-A-1

>  <PubChem CID>
1233035

>  <InChI>
InChI=1S/C22H20N4O3S2/c1-14-12-16(15(2)26(14)18-8-10-19(11-9-18)31(23,28)29)13-20-21(27)25-22(30-20)24-17-6-4-3-5-7-17/h3-13H,1-2H3,(H2,23,28,29)(H,24,25,27)/b20-13-

>  <IChI Key>
ODRSSOQWOHNABY-MOSHPQCFSA-N

>  <Series>
1

>  <Pfal IC50 (Guy)>
3.05

>  <Pfal (K1) IC50 (Guy)>
4.379

>  <PfaI EC50 uMol (Mean)>
3.7145

>  <hAcceptor>
7

>  <hDonor>
2

>  <oclLogP>
2.674600023776293

>  <oclLogS>
-7.315000135451555

>  <oclPSA>
140.22999811172485

>  <oclRotatable>
4

>  <oclStereoCenter>
0

>  <mw>
452.5578

>  <mf>
C22H20N4O3S2

>  <em>
452.097681

$$$$
```

**Comment by cdsouthan** [comment]
This is very good but we should be circumspect about how we populate the fields/tags. It also raises issues about batch loaders and parsers  (i.e. refreshing inputs and generating new outputs without changing the structures  e.g. re-calcuated properties).  There is an argument for de-coupling assay data from the structures (since it is a transient attribute and may be refreshed in the master sheet).  Another point is not to put the CID (or any other derived ID) in the "master"  SDfile since its PubChem's "task" to compute what the CID is automatically when you submit an SID (and dont manually re-cycle any synonyms in fact).  We only need to lock down the one primary mapping  for OSMID <> SID file. Everything else (i.e. the rest of the hextet) can be generated automatically from the SD files.  It could be useful to index MMV numbers (as secondary mappings) but take care to note how this is done (i.e. manual or automated).

**Comment by mattodd** [comment]
Thanks @lpatiny . Asking me to read the SDF is like me asking you to open a bottle of butyl lithium. Looks good though.

@cdsouthan Don't understand, sorry. Can you translate to English? ;) What are you wanting us to do or not do? This SDF is being created purely for the paper submission as a static object i.e. for the academic record.

**Comment by mattodd** [comment]
SDF downloaded, as a zip. Here:

https://dl.dropboxusercontent.com/u/7431373/OSM%20Paper%201/SI/Datasets/Dataset%20S2%20Molecules%20SDF.zip

Unzipped. Opened in Textedit. I selected Series 1 on the cheminfo page before generating the SDF, but the SDF contains all compounds, i.e. from all four series. @lpatiny  Is there a way to create the SDF only for those compounds that have been selected - here just the Series 1 compounds? Would be easier than a manual prune...

**Comment by lpatiny** [comment]
@mattodd ... You know I did a PhD in organic chemistry. So I manipulated BuLi, tBuLi and even condensed COCl2 to pour it liquified in another flask 😉

**Comment by lpatiny** [comment]
@mattodd In fact for generating the SDF for a specific serie you should use the URL that display only this serie like : http://www.cheminfo.org/flavor/malaria/Display_data/index.html?series=1
In this case the SDF will only contain the selected molecules

**Comment by cdsouthan** [comment]
Apols for unclarities - but this is where at least an outline  workflow description of what the current triage for populating the master sheet would come in handy :)   I mistakenly assumed @lpatiny had convinced you to switch to SD files as master structure records.  Submitting these with a paper is unusual and I don't know what PLOS will do with them.  I woule have thought table of the triad (SMILES and the two InChI's) would be acceptable for in-manuscript or suplimentary data

**Comment by mattodd** [comment]
That's perfect, thank you!

On 7 December 2015 at 18:40, lpatiny <notifications@github.com> wrote:

> @mattodd <https://github.com/mattodd> In fact for generating the SDF for
> a specific serie you should use the URL that display only this serie like :
> http://www.cheminfo.org/flavor/malaria/Display_data/index.html?series=1
> In this case the SDF will only contain the selected molecules
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/349#issuecomment-162438522>
> .
>



-- 
MATTHEW TODD | Associate Professor
School of Chemistry | Faculty of Science

THE UNIVERSITY OF SYDNEY
Rm 519, F11 | The University of Sydney | NSW | 2006
T +61 2 9351 2180  | F +61 2 9351 3329  | M +61 415 274104
E matthew.todd@sydney.edu.au | W
http://sydney.edu.au/science/people/matthew.todd.php
W http://opensourcemalaria.org/ | W http://opensourcetb.org/ | W
http://opensourcepharma.net/

CRICOS 00026A
This email plus any attachments to it are confidential. Any unauthorised
use is strictly prohibited. If you receive this email in error, please
delete it and any attachments.

**Comment by mattodd** [comment]
Closing since paper submitted.
