### ISSUE TITLE
Re-synthesise OSM-S-138 to collect data 

### ISSUE THREAD

**Issue by alintheopen** [OpenSourceMalaria/OSM_To_Do_List#35]
Full data needed for the paper, @murrayfold made this compound which was clean by proton NMR but with residual DMF. Following purification, and removal of DMF the compound was very insoluble and so spectra were very weak.
![osm-s-138](https://f.cloud.github.com/assets/2626599/576368/04c51e3e-c800-11e2-810d-a3b31750a183.jpg)

**Comment by mattodd** [comment]
Compound included in Series paper, about to be submitted, so closing.
