### ISSUE TITLE
Addition of OSM-E-13 data to Series 1 Paper SI

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#355]
@alintheopen  to add data from @PatrickThomson  for OSM-E-13 to the SI document of Paper 1. [Relevant ELN page](http://malaria.ourexperiment.org/tcmdc_ap/6438/Attempted_synthesis_of_sulfonamide_PT13.html) containing the raw data.

**Comment by alintheopen** [comment]
Done.
