### ISSUE TITLE
Presubmission Inquiry to PLOS Medicine for OSM Paper 1

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#360]
According to the rules for PLOS Medicine, a [presubmission inquiry is needed](http://journals.plos.org/plosmedicine/s/presubmission-inquiries). Besides author info, two items are required. Abstract text (to be pasted into the web form) and a cover letter. Current drafts for both are below. **Comments/edits welcome**. 

We have to convey the content of the paper, but also sell why we think the paper is worthy of this publication venue. Is anything over-sold? Is anything missing? We're aiming to submit as soon as we can if this submission is approved by the journal. If it's not, we'll need to seek another target.

(Note that I have not yet made the working draft of the paper public for historical reasons. I originally cleared with PLOS Med's Board that we could submit a paper that was assembled from public components, but I never cleared the idea that the draft of the paper itself was already public. I erred on the side of caution and kept the draft closed, not least because we had no simple way of working collaboratively on a paper of this size and complexity in the public domain. In this day and age (of preprint servers) I suspect that this would be fine now, and we should aim to draft in public for all future OSM papers. There are better technical solutions for this now, too, that might actually compete with email.)

[OSM 1 Cover Letter v2.docx](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/38890/OSM.1.Cover.Letter.v2.docx)

**Abstract Text for Web-based Form** (includes edits from Paul Willis document posted in a later comment)

*Background*

The development of new antimalarial compounds remains a pivotal part of the strategy for malaria elimination. Recent large-scale phenotypic screens have provided a wealth of potential starting points for hit-to-lead campaigns. In this paper one such public set is explored, employing a so-called open source research mechanism in which all data and ideas were shared in real time, anyone was able to participate and patents were not to be sought.

*Methods and Findings*

The new chemical entities in this paper were explored with a range of chemical and biological methods, but also with an online technical platform that permitted the research to be undertaken with a unique level of transparency and community input.

One chemical sub-series was studied and found to exhibit some oral availability at high dose in mice but contained a metabolic liability that probably prevented oral efficacy and which could not be engineered out of the molecule without loss of potency. A second sub-series displayed high potency against multiple parasite stages, but at a cost of low solubility. Methods used in the biological profiling of the series included microsomal stability assays, metabolite identification and glutathione trapping experiments, assessment of hERG liability, late stage and dual gamete formation assays, liver stage assessment and oral efficacy in mice coupled with analysis of plasma samples. Assessment of the potential mechanism of action of these compounds was made with both in silico and experimental approaches. The latter included a yeast-based genetic sensitivity Hip Hop assay that was cross-checked with a parasite reduction ratio assay. Specific assays were undertaken for dihydroorotate dehydrogenase inhibition and an ion homeostasis assay to investigate possible activity against the important antimalarial target PfATP4. The evidence points to the series having an unknown novel mode of action, which could be the basis for further investigation.

The consortium’s technical platform involved: 1) an open source online electronic lab notebook that was the principal data store of all research conducted. This remains “live”. A snapshot has been taken and archived in an institutional repository, and may be downloaded and browsed to reveal the full project history; 2) Similarly an online “live” database of all 145 molecules described in this study may be added to by future researchers, but there is an offline snapshot of the dataset that will be archived with the paper as supporting information; iii) Fora for online discussion of the project as it takes place, including public “to do” lists, social media and a wiki. The composite technical platform is not prescriptive, through, for example, the construction of a monolithic new workspace, in order to encourage franchised activity by any contributor and keep barriers to participation as low as possible.

*Conclusions*

The series possessed both desirable and undesirable features, but ultimately it has not been possible to date to resolve the metabolic lability of the first sub-series of compounds, nor the poor solubility displayed by the second sub-series, therefore work has been stopped. This represents a successful outcome for a hit-to-lead project, where the objective is to identify series most likely to deliver drug candidates. As an open source research project, unexplored avenues are clearly identified and may be explored further by the community. Likely productive areas of future enquiry are identified, most importantly around improvement of solubility and experiments to establish the mechanism of action. New findings may be cumulatively added to the present work. The project therefore can be continued easily by others, who will be in full possession of all data and importantly can use this full data set in order to identify any unexplored medicinal chemistry strategies.

The open nature of the research provided some challenges. There is the logistical complexity of coordinating the inputs of so many disparate scientists, and there is a heavy requirement on the alignment of controls and assay methods where different laboratories are adding to a communal dataset. Yet the research method described here also provided major advantages, most important of which is that anyone qualified to assist the project is able to do so, allowing the meritocratic self-assembly of a team of interested scholars. Publication of this first open source drug discovery case history should provide valuable lessons for, and contribute to the further optimization of, this new model for drug discovery.

**Comment by madgpap** [comment]
Both read very well and are well balanced and thorough.

**Comment by mattodd** [comment]
Approval via email from Kiaran Kirk and here are some tracked changes for the abstract text from Paul Willis. Will incorporate/accept, apart from the comment on the PRR data, which [showed](http://malaria.ourexperiment.org/biological_data/13274/Series_1_Rate_of_Killing_PRR_Assay_Data.html) a fairly consistent MoA.

[osm abstract_PW.docx](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/42609/osm.abstract_PW.docx)

Anyone else? Probably submitting on **Friday** (Nov 27 2015).

**Comment by murrayfold** [comment]
I agree, both read very well and I'm happy as they are

**Comment by mattodd** [comment]
Email-based approval from Vicky Avery, Javier Gamo, Sue Charman. Suggested change in title was agreed, removing "GlaxoSmithKline" and instead reading "..the Tres Cantos arylpyrroles". 

Presubmission inquiry submitted just now. Will keep everyone posted. Closing.

**Comment by mattodd** [comment]
Well that was quick. PLOS Med say Yes they would like to receive the full article, in the next 10 days. Will ping people for any remaining things that are needed.

**Comment by madgpap** [comment]
great. is the ms on google docs somewhere?

**Comment by mattodd** [comment]
No, the need for particular formatting and images prevented that. I'll send round the final copy ASAP.
