### ISSUE TITLE
OSM Paper 1 - check on patent used for procedure in AEW4-7

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#362]
Besides downloading the OSM Series 1 dataset there's now only *one* thing remaining in red in the current draft of the OSM Series 1 paper - the need for a source for the patent used in AEW4-7 [here](http://malaria.ourexperiment.org/tcmdc_ap/4327) - @alintheopen do you know what this is? In final draft it's reference 106. It's on the use of silver carbonate as base in the failed synthesis of the ether analog OSM-S-236 from the corresponding alcohol and bromoacetamide.

**Comment by madgpap** [comment]
what is the patent code?

**Comment by alintheopen** [comment]
Hi George - the trouble is that I don't have the patent code. I've been searching SciFinder etc and can't find anything that looks right. 
I wrote a post here, which references a patent but without a reference (http://www.thesynapticleap.org/node/421) <Sigh> 
Must have been something I came across in a quick search and then gave it a go.
So...just in case anyone fancies having a search, I'm looking for an o-alkylation using silver carbonate and triethylamine in DCM. Leaving this issue open for a few more days and then I think we'll have to draw a line under it. Cheers Alice

**Comment by madgpap** [comment]
Could it be any of these:
https://www.surechembl.org/search/results/f1524575df8579743809fb3a3d36940f/?page=1

?

**Comment by madgpap** [comment]
go to https://www.surechembl.org/search/

paste this into the search box:

```
alkylation AND "silver carbonate" AND triethylamine
```

click search

Any luck?

**Comment by alintheopen** [comment]
no dice unfortunately. Thanks though @madgpap. Closing.
