### ISSUE TITLE
Please consider using Thinklab for your Open Science Prize application

### ISSUE THREAD

**Issue by jspauld** [OpenSourceMalaria/OSM_To_Do_List#366]
Hey folks,

If OSM will be submitting a proposal to the [Open Science Prize](https://www.openscienceprize.org/) (which it sounds like you might be), I would love to have you use [Thinklab](http://thinklab.com) to aide in development of the proposal. We've built a [really cool system](http://thinklab.com/how-it-works/for-reviewers) for open collaborative peer review of research proposals. Here's a screenshot of the text annotation system:

--------------

![image](http://think-lab.s3.amazonaws.com/s/img/how_reviewers_annotation.png)

--------------

The system allows for inline comments and longer discussions that link to the document. A big reason we're doing this is we want science funders to create grants programs that *require* openly posted proposals. Once people are collaboratively developing their proposal in the open, it's an easy step to just continue their work as an [open research project](http://thinklab.com/projects). Check out @dhimmel's [Thinklab project](http://thinklab.com/p/rephetio). We want everyone to follow the lead of OSM and conduct science in the open!

The ultimate goal is a platform for "massively collaborative" open science that intelligently directs researcher attention to where it's needed. If I'm not mistaken this idea is captured by what @mattodd said in #364:

> We’d be talking about something different that helps you find people who are doing things related to what you’re doing, using passive, behind-the-scenes searching rather than Q&A. More like the ads that appear in Gmail, without that uneasy feeling

Finally, I'd be very interested in joining with OSM (or anyone) to submit an application to the Open Science Prize ourselves. 

And regardless of the prize, I'd love to work with OSM to develop a platform that you guys will love using, while at the same time helping bring more of your peers into your way of doing science.

Cheers,

Jesse

**Comment by mattodd** [comment]
Thanks for this Jesse. We took a shot at the prize and missed, so I'm closing this for now.
