### ISSUE TITLE
Michael Pollastri discusses the virtues of open science in neglected tropical disease drug discovery

### ISSUE THREAD

**Issue by drc007** [OpenSourceMalaria/OSM_To_Do_List#370]
An interesting read.

https://www.medchemnet.com/users/2876-hannah-coaker/posts/4576-interview-with-professor-michel-pollastri

**Comment by mattodd** [comment]
Thanks. Mike's a talented guy, running a hybrid model that uses a partly open structure. He spoke at Pacifichem on the use of human kinase inhibitors to find leads for NTDs, e.g. [this](http://pubs.acs.org/doi/abs/10.1021/acsinfecdis.5b00136).
