### ISSUE TITLE
Image for Open Science Prize Application

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#373]
Further to initial sketches ([here](https://twitter.com/MatToddChem/status/697980034359754753) and [here](https://twitter.com/MatToddChem/status/698018563580252160)), @MedChemProf sourced a [more professional-looking version](https://twitter.com/MedChemProf/status/698519620081344512), which is great.
This Issue is to allow commenting/suggestions on this image, so is a sub-conversation of #371 . Feel free to add things below (assuming this is OK, Chase?)
We need an image to get across the idea of what SCINDR is, at a glance, and also to break up what is otherwise uninterrupted text.

**Comment by mattodd** [comment]
My first two cents on this *excellent* first shot. It is rather better than mine.

i) Two researchers would be enough, rather than three, if there's a space issue.
ii) Real peoples' faces are I think more impactful than the "Faceless" cartoons.
iii) The molecule stuff in the "southeast" area is nonsense - we ought not to make bonding errors... Could one of the researchers have something biological behind them, like a cell?
iv) I'm not a fan of the red and green scrolls up top and down bottom, and I don't like the font used - is that comic sans, in fact? *shudders
v) I like the idea that SCINDR is actually looking at the researchers' work, rather than at us. Is there a way to convey that? I don't know. 
vi) Can "SCINDR" be on, or nearer, the robot?
vii) Unlike @alintheopen I don't mind the cocktails and cheese at the bottom, but perhaps we're overdoing the booze with wine glasses up top too. I know alcohol is an integral part of high quality research methods the world over, but people might think SCINDR is trying to achieve something else.

**Comment by drc007** [comment]
This looks excellent.

Would it be better if scientists wore lab coats etc.?

Most common colour blindness is red/green so avoid red text of green background

I’d make the world map a little darker

Since this is a software application perhaps have a molecule displayed on a computer screen?

Do you need to spell out what the acronym SCINDR stands for?

Can we make the cogs at the top right connect to something?

Instead of the rings bottom right how about using Artemisinin (https://en.wikipedia.org/wiki/Artemisinin <https://en.wikipedia.org/wiki/Artemisinin>)

**Comment by MedChemProf** [comment]
@mattodd @drc007 I simplified the drawing by removing one of the scientists and also the background. I think the white background will make it easier to paste into the proposal in the end. The new scientists are not actual pictures, but they do have lab coats on. I think the clipart images fit better with the infographic theme than real pictures.
     I made the map a little darker and removed the red/green text complication. I added the SCINDR and Mutual Intro to the center circle (I will need to work on the curvature to better match.)
     I removed the original clipart molecules and replaced them with one of the Type 4 structures that were actually working on between the two labs. I thought the two should be the same to emphasize the role of SCINDR. I also added the smaller image into the robot as suggested.
![scindredit](https://cloud.githubusercontent.com/assets/14179120/13034651/56756510-d309-11e5-9aaf-d73c6810d623.jpg)

**Comment by MedChemProf** [comment]
@mattodd @drc007 I simplified the drawing by removing one of the scientists and also the background. I think the white background will make it easier to paste into the proposal in the end. The new scientists are not actual pictures, but they do have lab coats on. I think the clipart images fit better with the infographic theme than real pictures.
     I made the map a little darker and removed the red/green text complication. I added the SCINDR and Mutual Intro to the center circle (I will need to work on the curvature to better match.)
     I removed the original clipart molecules and replaced them with one of the Type 4 structures that were actually working on between the two labs. I thought the two should be the same to emphasize the role of SCINDR. I also added the smaller image into the robot as suggested.
![scindredit](https://cloud.githubusercontent.com/assets/14179120/13034658/8b3584ce-d309-11e5-871c-7cce3148f926.jpg)

**Comment by alintheopen** [comment]
Thanks for the work Chase!

Agree with Chris that we need to spell out SCINDR acronym. 
Still not sure about the fonts or the rocket but I do prefer without alcohol and cocktail food as it confuses message in my opinion.
I like the clipart scientists and labcoats to clarify the message and I think two is OK but would be good to maintain some of the cultural diversity in original image.
What about arrows down from both of the scientists showing that they are interacting, on phone or via email and then linking to a new structure that is obviously a hybrid of the two originals?

**Comment by MedChemProf** [comment]
I did not have more than those two images with people in lab coats to choose from so I went with some new ones that show more diversity (but lost the lab coats). The middle is still a little busy, but tried to show the group coming together. Added larger workflow arrows to show things coming together through SCINDR. Removed rocket. Just let me know which fonts people prefer since I do not know what might work best. If anyone has an image of a better robot that might help.
![1455553817](https://cloud.githubusercontent.com/assets/14179120/13054739/5e4d2586-d3d9-11e5-8f7d-a6052ebedefa.jpg)

**Comment by mattodd** [comment]
You know, I think this is looking really nice. Other people inside the Circle of Collaboration is a nice touch. Still need, somehow, the words "Science Introduction Robot" somewhere, e.g. "I'm the Science Introduction Robot". If we can drop the Comic Sans font on the molecule atom letters, I'd be happy. Can discuss more in the hangout.

**Comment by MedChemProf** [comment]
@mattodd @alintheopen Please have a look at the latest version. I tried to add the requested text, but the center seemed to be too busy. So I removed the central circles and used the text to wrap SCINDR.
![osm_scindr](https://cloud.githubusercontent.com/assets/14179120/13098061/aef246f8-d4f4-11e5-8d49-dec2366a383e.jpg)

**Comment by alintheopen** [comment]
Yes! I like this - nice work Chase

**Comment by mattodd** [comment]
Yep, that's great Chase. I'm going to add it to the proposal for circulation.

**Comment by drc007** [comment]
This is brilliant

Chris

**Comment by MedChemProf** [comment]
@mattodd I spoke with Mike Pollastri from Northeastern Univ. earlier this morning about their Collaborative NTD Drug Discovery program. I also mentioned our proposal regarding SCINDR. He was interested and agreed to have a look at the proposal that you are circulating to possibly interested groups. He also indicated that a letter of support should be possible. Would you be able to send him a copy of the draft submission that you are circulating? Thanks.

**Comment by mattodd** [comment]
Hi @MedChemProf - OK, the [proposal](https://docs.google.com/document/d/1VPcpOaAK4OSdVB-qv1mN5l_cj74TKB55RuoP37MOC4s/edit?usp=sharing) ready to be viewed, apart from some technical comments that are needed from @lpatiny . Could you point him in the proposal's direction? A letter of support saying "This would be useful for health research" would be very good. 
The alternative, dragging ourselves into the 21st Century, is to ask for Tweets of support... @alintheopen ?
Either way, comments from people who might like to use this would be useful to show that it'd be a great thing to develop.

**Comment by alintheopen** [comment]
I've done some Twitter and FB shares. Let's see how we go.

**Comment by alintheopen** [comment]
Prize has been submitted, so closing. Other related discussions #372 are ongoing.
