### ISSUE TITLE
UN STI Forum Call

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#380]
There's [this call out for a UN-based event trying to help develop innovations relevant to the SDGs](http://stisolutions4sdgs.globalinnovationexchange.org/). As it says:

" Each year, the United Nations will host a Multi-stakeholder Forum on Science, Technology and Innovation for the SDGs (STI Forum). As part of the first annual STI Forum 2016 the UN, in collaboration with the Global Innovation Exchange, is launching a Call to Action for innovators, scientists, and entrepreneurs worldwide to submit their innovations as workable solutions for sustainable development.

The purpose of this Call to Action is to help to support these solutions by creating networks and communities among people who are developing technological and scientific innovations, those who can support or scale up such innovations, and those who need such innovations in order to implement the SDGs.

Worldwide, stakeholders are already leading the way towards the achievement of the SDGs by creating and scaling up ambitious and innovative ideas, technologies and practices. Help us to show what it takes to make sustainable development a reality for all!   Innovations should be already delivering solutions to the SDGs, and are welcomed from diverse backgrounds, including women, youth, Indigenous peoples, and open collaborative networks."

I might submit something on behalf of OSM if nobody objects, to see if we can obtain: 1) $ (clearly), 2) better access to researcher collaborators in developing nations and 3) better advocacy with governments and potential funders. Ultimately this is related to what needs to happen in the longer term with OSM, which is a scale-up to encompass parallel series.

Deadline end of April, pretty clear application form within the website. Am asking Sydney Uni research office for any back story, in case I'm misreading the intention of the call.

**Comment by drc007** [comment]
Sounds good

**Comment by MedChemProf** [comment]
@mattodd Let me know what you need for help and I will assist. I am available for a Google Hangouts meeting also if you feel needed.

**Comment by MFernflower** [comment]
Sounds like a great thing for this project to be involved in!

**Comment by mattodd** [comment]
A terrible set of deadlines in the last week meant I quickly loosed off an entry to this [here](http://stisolutions4sdgs.globalinnovationexchange.org/innovations/open-source-malaria) - sorry I didn't have time to consult with anyone. Obviously happy to hear any suggestions for improvements. There's a twofold request - for resources on the current Series and for potential partners on OSM scale-up. I'll let everyone know if we're selected. The OSM approach is a remarkably good fit to [SDG3](http://www.un.org/sustainabledevelopment/health/) I now realise.

**Comment by MedChemProf** [comment]
@mattodd Looks very good to me. MCPHS wasn't listed as contributor, but we are still trying. ;)

**Comment by mattodd** [comment]
Oh, sorry @MedChemProf that wasn't intentional - my bad.

**Comment by mattodd** [comment]
"Dear Participant,

Thank you for submitting your remarkable idea to the Call for Innovations for the SDGs!

The response to this Call for Innovations was outstanding, in terms of number and quality of innovations, from all over the world. We received over 270 applications, and all were examined by the members of the review committee which narrowed the field to 12 selected innovations. The choice was difficult, as many of the innovations showed exceptional promise as solutions for the SDGs and the overall quality was very high. Those selected were chosen as illustrations of the broad and inspiring range of sectors, countries and sources of innovation in solving different challenges raised by sustainable development. The selected innovations, who will showcase their innovations at the Multi-stakeholder Forum on Science, Technology and Innovation for the SDGs, (United Nations Headquarters, New York, on June 6 and 7, 2016) are as follows:

- Adaptive Learning Program
- Agriworks Mobile Irrigation System
- Clean Fuel from Agricultural Waste and Energy-Saving Cookstoves
- Dispensers from Safe Water
- JANMA Clean Birth Kit
- LAWIN Forest and Biodiversity Protection System
- Lumkani Fire Detection
- Naya Jeevan
- Reducing Milk Spoilage Through Solar Powered Milk Chilling in Rural India
- Social Register of Mauritius
-​ Surehatch Incubators
- Women Originated Media Entrepreneurship Network (WOMEN)

As a contributor to the Call for Innovations, you are also warmly invited to attend the Multi-stakeholder Forum. Participation is open to all interested stakeholders, free of charge, and registration is open until Sunday, May 22, at https://sustainabledevelopment.un.org/TFM/STIForum/Registration

We are pleased to share with you that, after reviewing your innovation, while not chosen to be showcased at the Multi-stakeholder Forum, you have been activated for full access to the Global Innovation Exchange. This will allow your innovation to be seen by donors and other investors as well as entities looking to identify and recognize great innovation. The Exchange will allow you to access funding opportunities and will help you find other resources to support your innovation. It will help show you other innovators working in the same or related fields, your competitors or potential partners, as well as funding you might want to apply for, and you can use it to gather comments, feedback, and other interactions around your innovation. Through the Exchange, you can join a community of like-minded innovators from around the world. Log in at: http://www.globalinnovationexchange.org/user/login

We encourage you to log onto the Exchange, ensure your profile is up-to-date, and start to access your dashboard to support your future activities. If you have questions about optimizing the Exchange, please email info@globalinnovationexchange.org

Thank you once again for sharing your ideas, products and innovative technologies with us - we are impressed, and encouraged by the extraordinary community of global innovators such as yourselves who are making the difference to those most in need around the world.

With kind regards,"

Never mind - OSM is at least on the exchange. People should feel free to use the arguments there if they are useful. Closing, but this Issue can obviously still be found on search.
