### ISSUE TITLE
Aldehyde Oxidase

### ISSUE THREAD

**Issue by drc007** [OpenSourceMalaria/OSM_To_Do_List#381]
I have updated the drug discovery resources page on [Aldehyde Oxidase](http://www.cambridgemedchemconsulting.com/resources/ADME/aldehyde_oxidase.html). In particular I have included more detail on the species differences and added the recent X-ray structure of AOX1 with substrate and inhibitor bound. Given that this may be an important route for the metabolism of series 4 I thought you might find it useful. 

Can we add an ADME label?

**Comment by mattodd** [comment]
That's very nice, Chris. Useful for us all. A reminder of our [current AO data](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Aldehyde_Oxidase_Assay) on Series 4. We can acquire more.
ADME label: will add, yes. Closing this Issue.
