### ISSUE TITLE
Compounds Shipped to Syngene May 2016

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#384]
These compounds were shipped this week to Syngene for potency evaluation. (Strings and files are on the [ELN](http://malaria.ourexperiment.org/biological_data/14124/Compounds_Shipped_to_Syngene_May_2016.html)) The compounds arose from a design process in #358 , but please append any comments on these compounds below. Obviously once we’ve data back we’ll try to incorporate the data in a fresh design round and close out both Issues.

![submitted compounds may 2016 abbr](https://cloud.githubusercontent.com/assets/4386101/15033359/278eebe8-12ad-11e6-98c3-11418a262289.png)

A homologous thioether/sulfoxide/sulfone series (extra methylene between S and pendant Ph) is [being synthesized at the moment by Ed](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/MTYzLjh8MTUwOS8xMjYvVHJlZU5vZGUvMjUxNDEwNDEwOHw0MTUuOA==) (see the "longer sulfide linker" folder, as is the compound with the triazole ring the other way around (alkynyl-triazolpyrazine used to couple with a pendant azide). Alice is working on a few other outstanding compounds from the previous list in #358 . Chase is working on the important [reversed amide](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/358#issuecomment-211377213). We still have no takers for compounds like The Burns or the AZ idea, and I'm sure we'll pick up some new designs this month. We’re hoping to receive data back from Syngene in time for the next online meeting, which is a special webinar/summary event organized by Mark Gardner (#386), for which there will be a follow-up meeting to gather together inputs from the community.

**Comment by MFernflower** [comment]
Looking good!

**Comment by MFernflower** [comment]
Greetings again Dr.Todd! Ed and I also talked about a sulfonamide that may be in the works. (see issue #382) Other ideas I have thought up include replacement of the phenyl on the end of the ether chain with pyridine or imidazole and the rightside cubane that I talked a bit with you about.

**Comment by MFernflower** [comment]
@mattodd Ed and I also talked about a few sulfonamides that may be in the works Other ideas I have thought up include replacement of the phenyl on the end of the ether chain with pyridine or imidazole and the rightside cubane that Craig Williams is willing to help OSM produce

**Comment by MFernflower** [comment]
@mattodd Ed and I also talked about a few sulfonamides that may be in the works - Other ideas I have thought up include replacement of the phenyl on the end of the ether chain with pyridine or imidazole (might improve LogP)

**Comment by mattodd** [comment]
To update everyone - there was a small delay in assaying these compounds at Syngene, and we're still waiting on data. Any day now hopefully!

**Comment by alintheopen** [comment]
Data reported here: http://malaria.ourexperiment.org/uri/8e1 so closing.
