### ISSUE TITLE
Anyone ever use XenoSite?

### ISSUE THREAD

**Issue by MFernflower** [OpenSourceMalaria/OSM_To_Do_List#387]
I do not know if anyone on the team has used this freely available on-line program known as Xenosite (http://swami.wustl.edu/xenosite) but it seems quite useful. It is unique as it does not only predict cytochrome mediated degradation like smartcyp and related, but can flag sites of epoxidation and quinone formation (not a big concern for the series 4 compounds but still very useful) - A more important feature of this service is that it can also preform predictions about how a drug will interact with UDP transferase.

I do not know if this was the right place to post this information but I want everyone to know about this free tool as the UDP transferase predictor seems extremely useful!

**Comment by willow-yll** [comment]
Does this software have open source code? If you know please provide a link, thank you very very very very very very very very much !!!!

**Comment by drc007** [comment]
There is a comparison of a variety of metabolism prediction tools here https://www.cambridgemedchemconsulting.com/resources/ADME/predicting_metabolism.html

**Comment by drc007** [comment]
@willow-yll > Does this software have open source code? If you know please provide a link, thank you very very very very very very very very much !!!!

XenoSite is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. But I can't find source code however I note it also utilises the OpenEye OEChem software (http://eyesopen.com) which I don't think is open-source.

**Comment by willow-yll** [comment]
> @willow-yll > Does this software have open source code? If you know please provide a link, thank you very very very very very very very very much !!!!
> 
> XenoSite is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. But I can't find source code however I note it also utilises the OpenEye OEChem software (http://eyesopen.com) which I don't think is open-source.

thanks for  your reply ~~
