### ISSUE TITLE
No Gametocyte Data on Series 4?

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#397]
Taking a step back from the accumulated Series 4 data, I noticed that we have no data on potency _vs._ gametocytes. At least I think that's the case.
As I have now mentioned on the [wiki](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Gametocyte_Stage), the document describing the series inherited by OSM at the start of this project indicated that the series had no/low activity _vs._ gametocytes, but we have no data to back up this statement, which would of course be needed for publication. 
Should we acquire such data (on 2-3 lead compounds), for completeness?

**Comment by MFernflower** [comment]
Is pfatp4 even expressed in gametocytes? Are gametocytes active cells or are the akin to the endospores of bacteria? If they are indeed active cells they should be expression ion channels and whatnot - Would kirk be willing to do the ion assay on gametocytes treated perhaps with the monomethylamine TP?

**Comment by MFernflower** [comment]
http://d-scholarship.pitt.edu/10790/

**Comment by neilfws** [comment]
If I am reading this article correctly, it suggests that PfATP4 is active in gametocytes and that they are susceptible to osmotic perturbation:

http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4559606/

"Gametocytes treated with KAE609 were also reported to became swollen and rounded"
"The data are also consistent with PfATP4 being essential for the survival of sexual-stage gametocytes"

**Comment by MFernflower** [comment]
Throw the most potent TP we got at some gametocytes and do an ion assay? Anyone know if kirk has a github account?

**Comment by mattodd** [comment]
Interesting suggestions/points. So it looks like the Novartis and Vaidya compounds are active. How about the [Guy](http://www.pnas.org/content/111/50/E5455) and [Winzeler](http://pubs.acs.org/doi/10.1021/cb500616x) compounds? I think @alintheopen is checking. Kiaran's not on Github, but by chance he's coming through Sydney next week and this will form some lunchtime conversation.

![screen shot 2016-06-03 at 11 16 52 am](https://cloud.githubusercontent.com/assets/4386101/15765854/c167a710-297c-11e6-8050-7b160949427a.png)

**Comment by alintheopen** [comment]
![github atp4 chemotypes](https://cloud.githubusercontent.com/assets/2626599/15860984/83ccbcac-2d0e-11e6-95c0-d0527d8e0748.png)

**Novartis** http://dx.doi.org/10.1016/j.ijpddr.2015.07.001
_"KAE609 also inhibits gametocyte development (in an in vitro growth assay) and oocyst development in mosquitoes."_
and
_"Gametocytes treated with KAE609 were also reported to became swollen and rounded (van Pelt-Koops et al., 2012), again consistent with a disruption of osmotic stability. Many cells have the capacity to regulate their volume in response to osmotic perturbation. The ability of the parasite to do so is unknown."_

**Winzeler** dx.doi.org/10.1021/cb500616x
Only refernce refers to spiroindolone compounds.
_"Van Pelt Koops et al. demonstrated that the spiroindolones are capable of blocking transmission to mosquitoes."_ Ref: van Pelt-Koops, J., Pett, H., Graumans, W., van der VegteBolmer, M., van Gemert, G., Rottmann, M., Yeung, B., Diagana, T., and Sauerwein, R. (2012) The spiroindolone drug candidate
NITD609 potently inhibits gametocytogenesis and blocks Plasmodium falciparum transmission to Anopheles mosquito vector. Antimicrob.Agents Chemother. 56, 3544−3548. (33) Blagborough, A. M., Delves, M. J., Ramakrishnan, C., Lal, K

**Guy** www.pnas.org/cgi/doi/10.1073/pnas.1414221111
No mention of gametocytes. Comment on efficacy in asexual and sexual blood stages:
_"...(+)-SJ733 is highly potent, efficacious against both asexual and sexual blood stages, safe, and highly orally bioavailable."_

**Vaidya** DOI: 10.1038/ncomms6521
_"The functional viability of P. falciparum mature Stage V male and female gametocytes as manifested by their ability to form male and female gametes, respectively, was inhibited when exposed to PA21A092 with an EC50 of 39 and 74 nM, respectively, indicating its potential to act also as a transmission-blocking drug."_

and

"The lead compound, PA21A092 (Fig. 2E), like the spiroindolone KAE609, also inhibited gametocyte development, with reduced conversion of gametocytes to gametes." http://dx.doi.org/10.1016/j.ijpddr.2015.07.001

**Comment by mattodd** [comment]
This useful discussion is now linked in the [wiki](https://github.com/OpenSourceMalaria/Series4/wiki/Gametocyte-Stage), in the S4 paper, and a discussion of possible samples to send has been [started](https://github.com/OpenSourceMalaria/Series4/issues/5). Closing.
