### ISSUE TITLE
Remake MNR116

### ISSUE THREAD

**Issue by murrayfold** [OpenSourceMalaria/OSM_To_Do_List#4]
![mnr116_scheme](https://f.cloud.github.com/assets/2679002/481912/1c2d67a4-b87c-11e2-8741-ffc85a545352.png)

**Comment by mattodd** [comment]
Closing. Unclear what this is for. Added URL to Master List. (this compound type with large north amine substituent likely has different MoA from rest of Series 3. Compound above is OSM-S-449. Linked in #33
