### ISSUE TITLE
The 6 -- proposed synthesis Haverford College

### ISSUE THREAD

**Issue by rbroadrup-HC** [OpenSourceMalaria/OSM_To_Do_List#401]
Proposed synthetic routes have been developed in collaboration with students as part of an organic chemistry class I teach at Haverford College. The molecules are seen as being desirable targets as per #390. This Issue has been created for community feedback on the routes, which can then be attempted in the lab by us or others.

![the 6 rev 1](https://cloud.githubusercontent.com/assets/19805430/16125537/186c6e66-33c2-11e6-9d4b-50364ed576dd.png)

FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC(C)=C(OCC(O)C4=CC=CC=C4)N32
InChI=1S/C21H18F2N4O3/c1-13-20(29-12-17(28)14-5-3-2-4-6-14)27-18(11-24-13)25-26-19(27)15-7-9-16(10-8-15)30-21(22)23/h2-11,17,21,28H,12H2,1H3
ZYFKQWHTACKGJR-UHFFFAOYSA-N

**Comment by MFernflower** [comment]
May want to forgo the hydroxyl group - benzyl ethers are potent

**Comment by MFernflower** [comment]
:+1:

**Comment by alintheopen** [comment]
Looks interesting. Alcohol certainly interesting and perhaps Me and/or CF3 ether if possible. :)

**Comment by MFernflower** [comment]
@alintheopen maybe a dimethylamine?  :smile:

**Comment by rbroadrup-HC** [comment]
Updated reaction scheme reference.

**Comment by mattodd** [comment]
Closing since taken on to #428
