### ISSUE TITLE
The 8 -- proposed synthesis Haverford College

### ISSUE THREAD

**Issue by rbroadrup-HC** [OpenSourceMalaria/OSM_To_Do_List#402]
Proposed synthetic routes have been developed in collaboration with students as part of an organic chemistry class I teach at Haverford College. The molecules are seen as being desirable targets as per #390. This Issue has been created for community feedback on the routes, which can then be attempted in the lab by us or others.

![the 8 rev 2](https://cloud.githubusercontent.com/assets/19805430/16123178/19df4796-33b8-11e6-9f7b-ed5d67869fda.png)

CC1=NC=C(OCC(O)C2=CC=CC=C2)N3C1=NN=C3C4=CC=C(OC(F)F)C=C4
InChI=1S/C21H18F2N4O3/c1-13-19-25-26-20(15-7-9-16(10-8-15)30-21(22)23)27(19)18(11-24-13)29-12-17(28)14-5-3-2-4-6-14/h2-11,17,21,28H,12H2,1H3
ASWYMQOLUDKKDJ-UHFFFAOYSA-N

**Comment by drc007** [comment]
I presume there is a deprotonation first before alkylation in the first step?

**Comment by MFernflower** [comment]
:+1:

**Comment by rbroadrup-HC** [comment]
Scheme corrected to include base in first step and to update reference.

**Comment by MFernflower** [comment]
@rbroadrup-HC I am wondering if the 8 and 6 compounds could be dimethylamines instead of alcohols? the synth scheme seems easy - treat pure L-Phenylalanine with DIBAL and couple the resulting alcohol to the TP core, purify the resulting compound and then preform clarke reaction on it?

**Comment by MFernflower** [comment]
@rbroadrup-HC Perhaps if it is easy enough to synthesize  - Could try 8,6 dimethyl on TP core? 

![dimethyl](https://cloud.githubusercontent.com/assets/3164942/16593842/58aac6ce-42b5-11e6-9048-5f74115a749f.png)

**Comment by MFernflower** [comment]
@rbroadrup-HC Looks like anything but halogens or hydrogen in the 8 position causes issues: 

http://openwetware.org/wiki/Image:Pyrazine_Substitution_Mods.png

**Comment by MFernflower** [comment]
@rbroadrup-HC Looks like anything but halogens or hydrogen in the 8 position causes issues - Might want to shelve this one? 

![800px-pyrazine_substitution_mods](https://cloud.githubusercontent.com/assets/3164942/17467153/2e413370-5ce9-11e6-9c83-1a4dcbae60e1.png)

**Comment by mattodd** [comment]
No, this was factored in - we need ways to access this compound. It'd be useful to measure metabolic stability, particularly in the Aldehyde Oxidase assay, where blocking groups next to aromatic N might be useful. And if we can put a methyl there we might be able to adapt the chemistry to put other things there too. One possibility is that if the potency is reasonable then perhaps we could use the chemistry to put a biotin there for pull-down.

**Comment by MFernflower** [comment]
That is very very interesting. Is there any computational way to access aldehyde oxidase stability? As for ideas that have not be tried for the 8 position - difluromethoxy or trifluoromethyl  perhaps? @mattodd

**Comment by drc007** [comment]
I'm not aware of computational studies but I've written a summary here http://www.cambridgemedchemconsulting.com/resources/ADME/aldehyde_oxidase.html

Typically electron-deficient N-heterocycles are a potential flag.

**Comment by mattodd** [comment]
Closing since taken on to #429
