### ISSUE TITLE
The Alkyl -- proposed synthesis Haverford College

### ISSUE THREAD

**Issue by rbroadrup-HC** [OpenSourceMalaria/OSM_To_Do_List#403]
Proposed synthetic routes have been developed in collaboration with students as part of an organic chemistry class I teach at Haverford College. The molecules are seen as being desirable targets as per #390. This Issue has been created for community feedback on the routes, which can then be attempted in the lab by us or others.

Revised proposed synthetic plan based on comments below:
![the alkyl rev 1](https://cloud.githubusercontent.com/assets/19805430/16127130/18ef996a-33c9-11e6-883c-bc2202f9d56f.png)

![the alkyl](https://cloud.githubusercontent.com/assets/19805430/15871720/0f300b32-2cc4-11e6-8ac9-2a935ff7be3d.png)

FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(CCC4=CC=CC=C4)N32
InChI=1S/C20H16F2N4O/c21-20(22)27-17-10-7-15(8-11-17)19-25-24-18-13-23-12-16(26(18)19)9-6-14-4-2-1-3-5-14/h1-5,7-8,10-13,20H,6,9H2
QKTHSIJWBSHMDZ-UHFFFAOYSA-N

**Comment by MFernflower** [comment]
@rbroadrup-HC  Grignard should be really simple: http://www.sigmaaldrich.com/catalog/product/aldrich/b65780?lang=en&region=US

**Comment by MFernflower** [comment]
:+1:

**Comment by drc007** [comment]
Rather than phenethyl Grignard, you could use a Sonogashira coupling with phenyl acetylene. Hydrogenation to alkene, or functionalise the triple bond to make some other interesting linking groups?

**Comment by MFernflower** [comment]
great idea - perhaps we could introduce a double bond somewhere along the
hydrocarbon chain?

**Comment by alintheopen** [comment]
Yes, I like @drc007's idea. We can really think about using the triple bond as a handle for the introduction of some interesting functionality.

**Comment by MFernflower** [comment]
@rbroadrup-HC @alintheopen If one is made with a double bond how to separate cis/trans isomers? cis isomer might be inactive because it distorts the geometry between the two pendant rings

**Comment by alintheopen** [comment]
Sonogashira reaction would give a triple bond. If we choose to generate an alkene we can pick a stereoselective reaction. @drc007 suggested Lindlar reduction, which leads to the syn-addition of H to give the cis isomer. Dissolving metal reductions would favour trans. Although of course sometimes we get a mixture of isomers, chromatographic separation is possible, silver nitrate columns can also be employed in trickier cases. It would be nice to test both geometries of course.

**Comment by MFernflower** [comment]
Could not agree with you more

**Comment by MFernflower** [comment]
@alintheopen This is not my best idea ever - but I was wondering if we could apply some dyestuff chemistry to this and produce an azo compound? 

FC(F)OC1=CC=C(C=C1)C1=NN=C2C=NC=C(\N=N\C3=CC=CC=C3)N12

**Comment by rbroadrup-HC** [comment]
I revised the synthetic plan to incorporate the Sonogashira suggested by @drc007.  If the group agrees, I can fully reduce some of acetylene and also attempt to produce the cis-alkene with Lindlar.

**Comment by drc007** [comment]
The unsaturation in the chain would also allow for further functionalisation, for example oxygenation.

**Comment by alintheopen** [comment]
I agree with @drc007's suggestion for this ne @rbroadrup-HC :)

**Comment by mattodd** [comment]
+1 Sonogashira

**Comment by MFernflower** [comment]
Did some ClogP calculations - Some of the compounds are quite greasy but I feel they should *all* be sent to syngene - What do you all think?

alkyl: 3.27
olefin cis: 3.28
parent alkyne: 3.26
olefin trans: 3.28

**Comment by MFernflower** [comment]
@rbroadrup-HC  @mattodd  I searched the wiki and found this interesting tidbit: 
![untitled](https://cloud.githubusercontent.com/assets/3164942/16441469/ba387b6a-3d98-11e6-9f7f-65cd52b98fb6.png)

**Comment by mattodd** [comment]
Closing since taken on to #424
