### ISSUE TITLE
The Burns -- proposed synthesis Haverford College

### ISSUE THREAD

**Issue by rbroadrup-HC** [OpenSourceMalaria/OSM_To_Do_List#404]
Proposed synthetic routes have been developed in collaboration with students as part of an organic chemistry class I teach at Haverford College. The molecules are seen as being desirable targets as per #390. This Issue has been created for community feedback on the routes, which can then be attempted in the lab by us or others.

![the burns](https://cloud.githubusercontent.com/assets/19805430/15871784/5b91493c-2cc4-11e6-8205-7fe9128204be.png)

FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(C(NCC4=CC=CC=C4)C(F)(F)F)N32
InChI=1S/C21H16F5N5O/c22-20(23)32-15-8-6-14(7-9-15)19-30-29-17-12-27-11-16(31(17)19)18(21(24,25)26)28-10-13-4-2-1-3-5-13/h1-9,11-12,18,20,28H,10H2
NYRGMZUFRGWPBF-UHFFFAOYSA-N

**Comment by mattodd** [comment]
Closing since taken on to #422
