### ISSUE TITLE
The hERG Evador -- proposed synthesis Haverford College

### ISSUE THREAD

**Issue by rbroadrup-HC** [OpenSourceMalaria/OSM_To_Do_List#405]
Proposed synthetic routes have been developed in collaboration with students as part of an organic chemistry class I teach at Haverford College. The molecules are seen as being desirable targets as per #390. This Issue has been created for community feedback on the routes, which can then be attempted in the lab by us or others.

![the herg evador](https://cloud.githubusercontent.com/assets/19805430/15871838/7f9c7716-2cc4-11e6-83c8-3eaea6bff1a8.png)

FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC(C(O)=O)C4=CC=CC=C4)N32
InChI=1S/C21H16F2N4O4/c22-21(23)31-15-8-6-14(7-9-15)19-26-25-17-10-24-11-18(27(17)19)30-12-16(20(28)29)13-4-2-1-3-5-13/h1-11,16,21H,12H2,(H,28,29)
FICNFVPYGUTYFV-UHFFFAOYSA-N

**Comment by MFernflower** [comment]
A carboxylic acid seems like a good idea @mattodd @drc007

**Comment by MFernflower** [comment]
@rbroadrup-HC Why not join the protected alcohol to the 2-chloro-6-hydrazinylpyrazine fragment, couple the resulting molecule with the usual aldehyde, deprotect the alcohol and then oxidize the whole lot with DMP - that way the ring closure and alcohol to acid conversion could be done in one step

**Comment by alintheopen** [comment]
Yes, this molecule is already planned. :)

**Comment by MFernflower** [comment]
@alintheopen Perhaps we could make isopropyl ester of the drug aswell?

**Comment by MFernflower** [comment]
@rbroadrup-HC @alintheopen This is the synthesis scheme I came up with (sorry for the poor graphics quality) 


![dhdhdhd](https://cloud.githubusercontent.com/assets/3164942/16253373/228c85de-3804-11e6-8d3b-d31eb9fe3e68.png)

**Comment by mattodd** [comment]
Closing since taken on to #427
