### ISSUE TITLE
The Hetero Oxadiazole -- proposed synthesis Haverford College

### ISSUE THREAD

**Issue by rbroadrup-HC** [OpenSourceMalaria/OSM_To_Do_List#406]
Proposed synthetic routes have been developed in collaboration with students as part of an organic chemistry class I teach at Haverford College. The molecules are seen as being desirable targets as per #390. This Issue has been created for community feedback on the routes, which can then be attempted in the lab by us or others.

![the hetero oxadiazole](https://cloud.githubusercontent.com/assets/19805430/15871887/b1cbee74-2cc4-11e6-9fcc-a8e08a80d4ba.png)

FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(C4=NC(C5=CC=CC=C5)=NO4)N32
InChI=1S/C20H12F2N6O2/c21-20(22)29-14-8-6-13(7-9-14)18-26-25-16-11-23-10-15(28(16)18)19-24-17(27-30-19)12-4-2-1-3-5-12/h1-11,20H
HFPKPTYSFARKAA-UHFFFAOYSA-N

**Comment by MFernflower** [comment]
Interesting to note that triazole was inactive

 http://malaria.ourexperiment.org/biological_data

@rbroadrup-HC

**Comment by mattodd** [comment]
@rbroadrup-HC am I right in thinking this is not being pursued experimentally in the Superlab? If so we should close this Issue for now but retain this compound (and this Issue) on a list of potential targets on the Series wiki.

**Comment by mattodd** [comment]
Link installed in [DCNYS](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Desirable_Compounds_Not_Yet_Synthesised) section of wiki, and synthesis of this compound now taken on to #463.
Closing.
