### ISSUE TITLE
The Hetero Oxazole -- proposed synthesis Haverford College

### ISSUE THREAD

**Issue by rbroadrup-HC** [OpenSourceMalaria/OSM_To_Do_List#407]
Proposed synthetic routes have been developed in collaboration with students as part of an organic chemistry class I teach at Haverford College. The molecules are seen as being desirable targets as per #390. This Issue has been created for community feedback on the routes, which can then be attempted in the lab by us or others.

![the hetero oxazole](https://cloud.githubusercontent.com/assets/19805430/15871916/dccde50a-2cc4-11e6-98f3-187d9d2e4778.png)

FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(C4=CN=C(C5=CC=CC=C5)O4)N32
InChI=1S/C21H13F2N5O2/c22-21(23)29-15-8-6-13(7-9-15)19-27-26-18-12-24-10-16(28(18)19)17-11-25-20(30-17)14-4-2-1-3-5-14/h1-12,21H
FBTBZFMQUBZDSN-UHFFFAOYSA-N

**Comment by MFernflower** [comment]
@rbroadrup-HC Why not do the halogen exchange on the chlorohydrazinylpyrazine instead of on the core?

**Comment by mattodd** [comment]
@rbroadrup-HC am I right in thinking this is not being pursued experimentally in the Superlab? If so we should close this Issue for now but retain this compound (and this Issue) on a list of potential targets on the Series wiki.

**Comment by mattodd** [comment]
Taken on to #462 and link installed in [DCNYS](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Desirable_Compounds_Not_Yet_Synthesised) section of wiki, so closing.
