### ISSUE TITLE
The Ketone -- proposed synthesis Haverford College

### ISSUE THREAD

**Issue by rbroadrup-HC** [OpenSourceMalaria/OSM_To_Do_List#408]
Proposed synthetic routes have been developed in collaboration with students as part of an organic chemistry class I teach at Haverford College. The molecules are seen as being desirable targets as per #390. This Issue has been created for community feedback on the routes, which can then be attempted in the lab by us or others.

![the ketone](https://cloud.githubusercontent.com/assets/19805430/15871941/fedff0de-2cc4-11e6-9899-1cd00e2d4b49.png)

O=C(CC1=CC=CC=C1)C2=CN=CC3=NN=C(C4=CC=C(OC(F)F)C=C4)N32
InChI=1S/C20H14F2N4O2/c21-20(22)28-15-8-6-14(7-9-15)19-25-24-18-12-23-11-16(26(18)19)17(27)10-13-4-2-1-3-5-13/h1-9,11-12,20H,10H2
KALFSUSYOZTBSP-UHFFFAOYSA-N

**Comment by drc007** [comment]
Why use a different route to methyl 6‐chloropyrazine‐2‐carboxylate in oxadiazole/oxazole synthesis?

**Comment by MFernflower** [comment]
@rbroadrup-HC There is a way to produce a ketone from the unreduced form of the alkyl - problem is it uses mercury: 
![organic-chemistry-1-alkynes-addition-reactions-image-9 jpg](https://cloud.githubusercontent.com/assets/3164942/16891519/ddc02faa-4ac8-11e6-9d3a-7891e354dbe1.gif)

**Comment by MFernflower** [comment]
@rbroadrup-HC Easy way to produce the ketone: http://www.organic-chemistry.org/abstracts/lit4/591.shtm

**Comment by mattodd** [comment]
Closing. Taken on to #425
