### ISSUE TITLE
The Nemesis -- proposed synthesis Haverford College

### ISSUE THREAD

**Issue by rbroadrup-HC** [OpenSourceMalaria/OSM_To_Do_List#409]
Proposed synthetic routes have been developed in collaboration with students as part of an organic chemistry class I teach at Haverford College. The molecules are seen as being desirable targets as per #390. This Issue has been created for community feedback on the routes, which can then be attempted in the lab by us or others.

![the nemesis](https://cloud.githubusercontent.com/assets/19805430/15871976/28afdfa0-2cc5-11e6-8de3-cce5123470b5.png)

OC(C1=CC=CC=C1)COC2=CN=CC3=NN=C(C4CNCCC4)N32
InChI=1S/C18H21N5O2/c24-15(13-5-2-1-3-6-13)12-25-17-11-20-10-16-21-22-18(23(16)17)14-7-4-8-19-9-14/h1-3,5-6,10-11,14-15,19,24H,4,7-9,12H2
SNDLBGDEOQPBOQ-UHFFFAOYSA-N

**Comment by drc007** [comment]
Will AcOH in second step remove Boc group?

**Comment by MFernflower** [comment]
The route I found uses dioxane and HCL
![boc-am1](https://cloud.githubusercontent.com/assets/3164942/15881065/0bcc5f80-2d01-11e6-9427-0b444a061ebb.GIF)

**Comment by MFernflower** [comment]
http://www.sciencedirect.com/science/article/pii/S0040403903028703

Might this route work?

**Comment by MFernflower** [comment]
@rbroadrup-HC @drc007  Looks like glacial acetic step will tear off the boc - http://www.ccsenet.org/journal/index.php/ijc/article/viewFile/14875/11684

**Comment by MFernflower** [comment]
@rbroadrup-HC N-formyl morpholine is buyable: https://www.alfa.com/en/catalog/B23315/

**Comment by MFernflower** [comment]
@mattodd Thanks for the information!!!! - Do you know of any resource (preferably free) where I can learn about synthetic mechanisms so that I could contribute more to your amazing effort?

**Comment by MFernflower** [comment]
Had to look through my old highschool chemistry homework to jog my memory -
In this reaction you are not useing acetic acid as a proton source but
instead as an electron acceptor?

**Comment by mattodd** [comment]
Closing. Taken on to #430
