### ISSUE TITLE
Welcoming Haochuan Mao to Open Source Malaria

### ISSUE THREAD

**Issue by alintheopen** [OpenSourceMalaria/OSM_To_Do_List#413]
Haochuan Mao @mhc1994 is an exchange student from Nanjing University in China. He will be working within the Sydney Uni part of OSM for the next 8 weeks and tackling some synthesis. Details of Haochuan's projetc will be posted under this issue.

Key links: http://opensourcemalaria.org/
http://malaria.ourexperiment.org/triazolopyrazine_se

**First Tasks for 070716**
follow instructions in the following blog posts:
1. [How To: GitHub](http://malaria.ourexperiment.org/osm_logos_and_templ/8074/Signing_up_to_and_using_GitHub__a_beginners_guide.html)
2. [How To: Set up an ELN](http://malaria.ourexperiment.org/osm_logos_and_templ/8488/Joining_the_OSM_Team_as_a_Chemist.html)
3. Read through Tianyi's @tyzhengsydney [summary](http://malaria.ourexperiment.org/the_osm_blog/8478/Summary_of_my_exchange_in_Mats_group.html) and [introduction](http://malaria.ourexperiment.org/the_osm_blog/8915/Introduction_to_my_project.html) blogs and also his [reports](http://malaria.ourexperiment.org/osdd_malaria_shared/14181/Reports_from_Tiany_Zheng.html)
4. Read/dip in and out of @tscmacdonald [Honours Thesis
](https://figshare.com/articles/Developments_of_Routes_to_Access_and_Functionalise_1_2_4_Triazolo_4_3_a_pyrazine_Amides_as_New_Antimalarials/1301073/1) and on ELN [here](http://malaria.ourexperiment.org/osdd_malaria_shared/14184/Honours_Thesis_Thomas_MacDonald_The_University_of_Sydney_2014.html)

**Comment by MFernflower** [comment]
What compounds will he be synthesizing? 

@alintheopen

**Comment by alintheopen** [comment]
patience dear @MFernflower! Updates coming but we have lots to do today!

**Comment by MFernflower** [comment]
I'm always in a bit of a high octane mood - I find this project to be quite exciting :-)  - I posted an idea I had to lower logp on twitter - might want to check it out when you can - But take your time indeed - we are doing something that was never really done before (an opensource chemistry project)

**Comment by alintheopen** [comment]
Yes and that's great, I love your enthusiasm and the chemistry pun! I saw the Twitter idea just have lots on in the lab with two awesome new students. It's good if we can all try to keep the ideas in one spot so that they are easy to find, so better to post to GH for all to see. This also means that the community can mull over and critique structures - also better if you can try to post multiple ideas in a single post so that we are not overwhelmed with notifications.

Soon we will refine ideas for new synthesis and we will have a total of  5 university classes(!) including @rbroadrup-HC and @MedChemProf of course! We will publish details once we have the green light and it will be amazing to have so many people working on new molecules....but at the moment @edwintse and I need to focus on the task at hand - resynthesising the front runners. 

If you have some time on your hands and if you are interested/willing there's a really useful LogP task that @edwintse was looking at yesterday (using DataWarrior as suggested by @drc007), so we can send some info on that when we get a chance? @edwintse will start a new issue when he gets a moment and then if you are interested you can sign up!
In a few hours I will delete the comments below this post so that we don't clog up this issue with other discussion!

Hope all is very well with you - we are freezing in Sydney (something that I would never have believed before I moved over from the UK) 

Alice :)

**Comment by MFernflower** [comment]
I am going to open up a GHI acting as a central point for all of my
scattered ideas to come together

**Comment by mattodd** [comment]
OK but remember that these Issues are intended for things that can be resolved - i.e. closed, once something has happened/been achieved. We have lots of open issues at present, but they are close-able. What you're describing sounds more like a blog or a lab notebook, Mandrake, which remains open and is added to. Or possibly a wiki page that accumulates ideas.

**Comment by MFernflower** [comment]
I understand  - I will not open the issue - How would I go about opening up
a lab notebook just for my computational work?

**Comment by alintheopen** [comment]
I think the best idea is to open a new ELN notebook using the following [guide](http://malaria.ourexperiment.org/osm_logos_and_templ/7773/Creating_a_General_Blog_Entry_on_the_Open_Source_Malaria_Electronic_Lab_Notebook_OSM_ELN.html). You could call this Mandrake's Blog and use it as a place to store your computational work. You have the freedom to label your entries as different types of contribution i.e. molecule ideas, PfATP4 modelling, Docking Studies etc.

**Comment by MFernflower** [comment]
Just got my ELN up and running - I posted 2 proposed molecules, tommrow i
will make a list of what part of sj253 interacts with what amino acid in
the channel

**Comment by alintheopen** [comment]
OK great, maybe you could collate your compound ideas there too? You can
always edit your entry when you have new ideas, maybe most recent at the
top of each blog post so that people can see them there?

**Comment by MFernflower** [comment]
I have been making a seperate entry for eatch proposed molecule - all entries of that sort are tagged as "Proposed Molecule" and eatch title has a number i.e "Proposed Molecule MX-0002"

**Comment by alintheopen** [comment]
An update on Haochuan's project. The first step has been successful, so now Haochuan will be developing the bromination whilst trying to improve the yield of the cyclisation. 
![haochuan chemistry](https://cloud.githubusercontent.com/assets/2626599/16899313/dadd4e3c-4c42-11e6-9f07-1a4f74bd398c.png)

++Below this line will be deleted later on++
p.s 

Hi @MFernflower, as I mentioned earlier I have deleted our conversation with @mattodd to keep this thread focused on Haochuan's work, but feel free to start a new issue if you want to direct people to your ELN. 

your text above was:

"I have been making a separate entry for each proposed molecule - all entries of that sort are tagged as "Proposed Molecule" and each title has a number i.e "Proposed Molecule MX-0002"

You can check out my ELN at http://malaria.ourexperiment.org/mfcompuchem @mattodd @alintheopen as I will now be posting molecule ideas and modeling studies to my ELN instead of github"

So feel free to cut and paste :) so we can comment elsewhere, hope you are having a good weekend. Alice

**Comment by MFernflower** [comment]
Feel free to delete that text

**Comment by mattodd** [comment]
Closing. [Core successfully synthesised](http://malaria.ourexperiment.org/triazolopyrazine_se/14562/Crystal_Structure_Files_for_HM_32_the_bromochloroTP_core.html). Resources in this Issue linked to in [the relevant synthesis branch](http://openwetware.org/wiki/OpenSourceMalaria:Synthesis_Branches) OSM-Branch-BrCl. Chemistry also being looked at by @pennypresident in #433
