### ISSUE TITLE
Competition: A Predictive Model for Series 4

### ISSUE THREAD

**Issue by alintheopen** [OpenSourceMalaria/OSM_To_Do_List#417]
**Today OSM are launching a competition to build a predictive model for the most promising current compound set: Series 4. The competition is based on existing open data, and the winning entry will be the one that best predicts the activity of test datasets. Key links can be found in the project [wiki](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_Series_Mechanism_of_Action) (please feel free to edit as well as use)**

**Outline**  **_We need a predictive model for PfATP4._**
PfATP4 is a sodium pump found in the membrane of the malaria parasite. A number of promising antimalarial compounds, with distinct and diverse chemical structures, have been found to be active in an ion regulation assay, which was developed by Kiaran Kirk's lab at the ANU. A number of publications have indicated that this pump is an important new target for malaria medicines. It seems that PfATP4 active compounds disrupt the pump and cause the rapid influx of Na+ into the parasite, leading to its demise. The structure of PfATP4 is not known. Simulations, based on docking of PfATP4 actives, have used a [homology model](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4273362/) developed by Joseph DeRisi's laboratory. The OSM consortium needs a predictive model for (potency vs PfATP4 activity) to assist in the design and synthesis of new Series 4 compounds and of course to help others working on other compound series.

**The first attempt**
@murrayfold had a quick, informal attempt ([here](http://malaria.ourexperiment.org/uri/800) and [here](http://malaria.ourexperiment.org/uri/801)) at the development of a pharmacophore model using known actives and inactives from the MMV Malaria Box. At the time Kiaran Kirk's [paper](http://onlinelibrary.wiley.com/doi/10.1111/mmi.12765/abstract) was under embargo but Murray has since written up his work. This initial attempt was unsuccessful (i.e. not predictive - see image below, where the "P Model predictions" correlate poorly with what was found in the ion regulation assay) possibly because the model did not allow for overlapping binding sites or take into consideration compound chirality.

![compounds sent to kirk and fidock](https://cloud.githubusercontent.com/assets/2626599/16288770/cb2a0fde-3932-11e6-8bb0-73a2f634f7f5.png)

**The Competition**
We need a predictive _in silico_ model. The best model will win the prize.

**How will it work?**
_OSM will provide:_
- [Files](http://malaria.ourexperiment.org/uri/930) containing details of actives and inactive compounds  **NB** This list is more substantial than the original dataset used by Murray. So you could also use the new data as a 'test set' for any model developed.
- The [Master Chemical List](https://docs.google.com/spreadsheets/d/1Rvy6OiM291d1GN_cyT6eSw_C3lSuJ1jaR7AJa8hgGsc/edit#gid=510297618) which contains activity data for **all OSM compounds, so Series 1-4** Test Set A (column Y) includes both Series One (all inactive against PfATP4) and Series Four compounds.
- Jeremy Horst's Homology Model: 
[PfATP4-PNAS2014.pdb.txt](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/404842/PfATP4-PNAS2014.pdb.txt)
- details of the [relevant mutations](http://malaria.ourexperiment.org/biological_data/11448/Evaluation_of_Series_4_Compounds_vs_ATP4Resistant_Mutants.html) known to be associated with resistance. 

_Submission Rules_
- all entries to be submitted to GitHub and shared openly
- entrants can work individually or in teams (no limit to team size)
- entrants must work openly _during_ the competition. This doesn't necessarily mean that inputs have to be logged in real time (although that is strongly encouraged), but entries that have not openly deposited working data on a regular basis prior to the deadline will not be accepted.
Open Electronic Notebooks (ELN) such as [Labtrove](http://malaria.ourexperiment.org/) or [LabArchives](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/MzA5LjR8MTUwOS8yMzgvVHJlZU5vZGUvMjE0NTczNDgxOHw3ODUuNA==) can be useful places to post data and work collaboratively. For example, Ho Leung Ng's ELN can be viewed and commented on [here](http://malaria.ourexperiment.org/pfatpase4_modeling). _Please note that LabTrove authors are not alerted when a comment is added to an entry so GitHub is a useful place to tag others._
- entrants must agree to their work's incorporation into a future OSM journal publication(s)
- competition winner(s) will be authors on any relevant future paper(s)
- any valid* entries will at least be acknowledged on any relevant future paper(s) and if the contribution is significant may lead to authorship.

**How will entries be assessed?**
- The model will be evaluated using three 'test sets' of molecules:

1. 'The Frontrunners' #400 [Test Set B (column Y) in [Master Chemical List](https://docs.google.com/spreadsheets/d/1Rvy6OiM291d1GN_cyT6eSw_C3lSuJ1jaR7AJa8hgGsc/edit#gid=510297618)]
2. @edwintse's new compounds #420 [Test Set C (column Y) in [Master Chemical List](https://docs.google.com/spreadsheets/d/1Rvy6OiM291d1GN_cyT6eSw_C3lSuJ1jaR7AJa8hgGsc/edit#gid=510297618)
3. A closed dataset of compounds (not available in Master Chemical List)
**NB the 'closed dataset' of compounds may not be publicly available when the winner is announced. All models will be tested against this 'closed dataset' and all details, including the source of this 'closed dataset' will be revealed as soon as the data has been published.**

- Entrants will predict the activities of compounds against PfATP4 in each of the test sets
- The winner will be decided by two currently-active members of OSM and two external experts

**What's the prize**
$500
...and the opportunity to contribute to our understanding of a new class of antimalarials
...and authorship on a resulting peer-reviewed publication arising from the OSM consortium

**What if none of the models are any good?**
Good question. If none of the models prove to be predictive, then it may not be possible to announce a 'winner'. All data will be collated and published at least in the form of a blog, if not a paper...and then we will try again.

**Deadline for Entries**
30th October 2016, 23:59:59 AEST (Sydney Time)
 
*A 'valid' entry is one that stands up to the rigour expected from published _in silico_ models. Judges are entitled to use discretion in the case of unconventional entrants, for example those from people with no formal training such as high school students.

An open consultation on how best to run this competition was conducted in Issue #412

**Comment by neilfws** [comment]
Potentially useful article (not freely-available sadly):

http://bib.oxfordjournals.org/content/17/4/696.short

**Comment by mattodd** [comment]
Cheminformatics experts: is there a way of determining a "best model" here? i.e. deciding the winner algorithmically, given the test set data that will be revealed later in the year? Or will the judgement always be a little subjective? We currently have "Using a statistical test the judges will find the winning model" in the above, but ought to firm this up and get things going.

**Comment by neilfws** [comment]
Model validation certainly needs to be defined precisely. I guess my answer would be: poke around the pharmacophore prediction literature, see what other people do. For example:

http://www.sciencedirect.com/science/article/pii/S1110093113000367

They use their model to predict the activities of a test set and then simply calculate correlation coefficients using predicted versus measured activity. So "best R-squared" might be one measure.

**Comment by MFernflower** [comment]
@neilfws Quite a good method for such a rough looking drug - Problem is we still do not have any data on what part of the PFATP4 pump the TP drugs bind to

**Comment by mattodd** [comment]
@MFernflower no, that's the point. A pharmacophore model can be developed without knowledge of the binding location. It asks what are the important features of the molecule in order to achieve activity. This is the reason we originally separated out the development of such a model from any docking studies (that require either a protein structure or a homology model) in the competition, but we've come round to adopting both approaches at the same time, because why not. The approaches remain methodologically distinct, however.

**Comment by MFernflower** [comment]
Sorry, had a bit of a brainfart

**Comment by alintheopen** [comment]
Closing and launching competition here: #421
