### ISSUE TITLE
Synthesis of the Alkyl: 3-(4-(difluoromethoxy)phenyl)-5-phenethyl-[1,2,4]triazolo[4,3-a]pyrazine 

### ISSUE THREAD

**Issue by bstudnit** [OpenSourceMalaria/OSM_To_Do_List#418]
We have started synthesis of  3-(4-(difluoromethoxy)phenyl)-5-phenethyl-[1,2,4]triazolo[4,3-a]pyrazine at Haverford College.

Synthetic Scheme:

![scheme](https://cloud.githubusercontent.com/assets/20305372/16878988/997ba64a-4a7c-11e6-8f6a-fe89542bd028.png)
Lab Notebook can be accessed [here](http://malaria.ourexperiment.org/synthesis_of_the_al).

FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(CCC4=CC=CC=C4)N32
InChI=1S/C20H16F2N4O/c21-20(22)27-17-10-7-15(8-11-17)19-25-24-18-13-23-12-16(26(18)19)9-6-14-4-2-1-3-5-14/h1-5,7-8,10-13,20H,6,9H2
QKTHSIJWBSHMDZ-UHFFFAOYSA-N

**Comment by MFernflower** [comment]
Looks like the link broke: 
malaria.ourexperiment.org/synthesis_of_the_al

**Comment by alintheopen** [comment]
thanks Mandrake!

**Comment by alintheopen** [comment]
Hi @bstudnit I took a look at the NMR for BS 1-1 and it looks good although I compared to our data in d-DMSO so slightly different shifts. Literature data found here if you want to double check: 

Bradac J, Furek Z, Janezic D, Molan S, Smerkolj I, Stanovnik B, Tisler M, Vercek B (1977) Telesubstitution and other transformations of imidazo[1,2-a]- and s-triazolo[4,3-a]pyrazines. J. Org. Chem., 42:4197–4201. (10.1021/jo00862a005) 

It's really strange that the condensation doesn't seem to work. We have used absolute ethanol too, ours isn't anhydrous and we don't need to conduct the reaction under an inert gas. Typically (and certainly for the reaction you describe) we see the SM going into a brown/orange solution and then after a little while (5-20 mins) the product crashes out as a yellow/orange solid that can be filtered on a large scale and used directly in the PIDA cyclisation reaction.

**Comment by MFernflower** [comment]
Looking at ed's notebook - A part of me thinks that atmospheric oxygen has something to do with catalyzing this reaction - Perhaps try to copy the conditions that ed used?

https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/Mjg4LjZ8MTUwOS8yMjIvVHJlZU5vZGUvOTMxNzQxNXw3MzIuNg==

**Comment by mattodd** [comment]
Hi @bstudnit - I'd check the NMR spectrum of the aldehyde if you've not done that already, and then eliminate the possibility that the TLC is not giving you the full picture by checking with a different stain and doing a crude 1H. No conversion is odd for this reaction. The remaining possibility is that your S/M hydrazine (the thing you made: OSM-H-1) is actually a "dimeric" compound of the form Ar-NH-NH-Ar. Might give a similar looking NMR spectrum but would not participate in the coupling with the aldehyde well. We ever isolate that @alintheopen ?

**Comment by MFernflower** [comment]
Quick question - did you guys use the monohydrate,

**Comment by MFernflower** [comment]
Did you make sure to use hydrazine monohydrate? @bstudnit

**Comment by MedChemProf** [comment]
@bstudnit We have been running the reaction in acetonitrile with a 1:1:1 ratio of 2-Chloro-6-hydrazinylpyrazine : Aldehyde : Glacial Acetic Acid. Only a filtration and quick wash with acetonitrile gives product.

**Comment by bstudnit** [comment]
Thank you everyone for your feedback/advice!  
@mattodd We don't believe we have the dimer, since GC-MS indicates a single, pure product with  m/z that corresponds to the SM hydrazinyl monomer.  Also, the aldehyde we used was from an unopened bottle recently purchased from a supplier. As of today, our NMR machine is up and running again, so we will get a spectra of the aldehyde.  

@MFernflower We used 98% hydrazine (anhydrous) from sigma aldrich. 

@MedChemProf Thanks for your input! We will definitely consider those reaction conditions when we re-attempt the condensation.

**Comment by MFernflower** [comment]
Perhaps add a small amount of water to the reaction since you are useing
anhydrous hydrazine?

**Comment by mattodd** [comment]
Hi @bstudnit - I was idly wondering if you're still pursuing this target, since your last reaction was a couple months back? Happy to leave this Issue open if you are.

**Comment by bstudnit** [comment]
So at the moment the alkyl is currently being pursued by students in the open malaria superlab course at Haverford, and they have more time in their schedule to work on it right now than I do.  (My focus is currently on a different synthesis.)  So although I am not currently working on the alkyl, if it is not synthesized within the time of the lab course and after this current synthesis, I may re-focus on the alkyl.

**Comment by mattodd** [comment]
Added this to [DCNYS](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Desirable_Compounds_Not_Yet_Synthesised) section of wiki. Closing.
