### ISSUE TITLE
Quick update on the compounds I've made and those I'm making

### ISSUE THREAD

**Issue by edwintse** [OpenSourceMalaria/OSM_To_Do_List#420]
Alongside some of the frontrunner resynthesis (#400), I have also been working on some other compounds for the next batch of samples to send to Syngene. (Note: CLogP values were calculated using DataWarrior (#385))

![untitled wiley-2](https://cloud.githubusercontent.com/assets/18062981/17508598/0ab95c54-5e59-11e6-80fc-7c5fb9c4a60b.jpg)

**Compounds ready to ship** (green box)
- OSM-S-363, -364 and -365 were synthesised as part of the hypothetical compounds (#358) in addition to those already synthesised and evaluated (#384). These serve as a better comparison to the previous thioether compound (mentioned in #377). OSM-S-368 and -369 were also synthesised to provide direct comparison with the two thioether compounds.
- OSM-S-370, -371 and -375 were synthesised following the discussion of using cubane bioisosteres (#379). The three cubanes were generously provided by Craig Williams at UQ.
- OSM-S-372, -373 and -374 were synthesised as a suggestion following the potency discussion at the last online meeting (#390).

**Compounds in progress** (orange box)
_(from left to right)_
- As an amide comparison with OSM-S-375 above
- In order to prevent potential inherent cytotoxicity of OSM-S-374
- To reduce size of the substituent on the triazole
- As a comparison with OSM-S-373
- The azide is at hand and the compound may lower the CLogP

**SMILES**
_(from left to right, top to bottom)_
- FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(SCCC4=CC=CC=C4)N32
- FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(S(CCC4=CC=CC=C4)=O)N32
- FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(S(CCC4=CC=CC=C4)(=O)=O)N32
- FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC4=CC=CC=C4)N32
- FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCCC4=CC=CC=C4)N32
- FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCCCC45C6C7C4C8C5C6C87)N32
- FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCCC45C6C7C4C8C5C6C78)N32
- IC12C(C3C1C4C52)C5C34C6=NN=C7C=NC=C(OCCC8=CC(F)=C(F)C=C8)N76
- FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC4=CN(CC5=CC=CC=C5)N=N4)N32
- FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC4=CN(C5=CC=CC=C5)N=N4)N32
- FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC4=CN(C5=NC(Cl)=CN=C5)N=N4)N32
- IC12C(C3C1C4C52)C5C34C6=NN=C7C=NC=C(C(NC8=CC=NC(C(F)(F)F)=C8)=O)N76
- FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC4=CN(C5=NC(OC)=CN=C5)N=N4)N32
- FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC4=CN(C(C)(C)C)N=N4)N32
- FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC4=CN(C5=NC=CC=C5)N=N4)N32
- FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC4=CN(S(C5=CC=C(NC(C)=O)C=C5)(=O)=O)N=N4)N32

**Comment by MFernflower** [comment]
@edwintse Fantastic work!!! I'm very curious if you could produce an organosilicon by doing a click reaction on EGT 87 with TMS azide - Another idea I had was to dehydrate MMV669848 with DDQ to produce an isoindole

**Comment by edwintse** [comment]
Potency data for the final set of compounds has been written up [here](http://malaria.ourexperiment.org/biological_data/15741/Biological_Data_from_Dundee__November_2016_Compounds.html).
