### ISSUE TITLE
Starting Attempted Synthesis of the Burns (Haverford College)

### ISSUE THREAD

**Issue by evonkrusenstiern** [OpenSourceMalaria/OSM_To_Do_List#422]
@claudianguyen95 and I will be attempting to synthesize "the Burns". We will be recording our work in this lab notebook. 

http://malaria.ourexperiment.org/the_burns 

<img width="157" alt="screen shot 2016-09-01 at 2 07 31 pm" src="https://cloud.githubusercontent.com/assets/21690013/18178760/a21993d8-704d-11e6-80a8-e1288a4c9735.png">

N-benzyl-1-(3-(4-(difluoromethoxy)phenyl)-[1,2,4]triazolo[4,3-a]pyrazin-5-yl)-2,2,2-trifluoroethan-1-amine

[N]/C=C(C(NCC1=CC=CC=C1)C(F)(F)F)\N2C=NN=C2C3=CC=C(OC(F)F)C=C3

InChI=1S/C20H16F5N5O/c21-19(22)31-15-8-6-14(7-9-15)18-29-28-12-30(18)16(10-26)17(20(23,24)25)27-11-13-4-2-1-3-5-13/h1-10,12,17,19,27H,11H2/b16-10-

**Comment by MFernflower** [comment]
@evonkrusenstiern Going to be synthesized as enantiopure or racemate?

**Comment by mattodd** [comment]
Great @evonkrusenstiern .
Always racemate first @MFernflower to confirm some activity

**Comment by claudianguyen95** [comment]
Just as a reference, we will be using the reaction scheme outlined in #404 as a starting point. 

![image](https://cloud.githubusercontent.com/assets/21690279/18190337/1343f598-7090-11e6-9645-a53bbd8caaf5.png)

FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(C(NCC4=CC=CC=C4)C(F)(F)F)N32
InChI=1S/C21H16F5N5O/c22-20(23)32-15-8-6-14(7-9-15)19-30-29-17-12-27-11-16(31(17)19)18(21(24,25)26)28-10-13-4-2-1-3-5-13/h1-9,11-12,18,20,28H,10H2
NYRGMZUFRGWPBF-UHFFFAOYSA-N

**Comment by mattodd** [comment]
Closing for now. Links installed on [DCNYS section of wiki](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Desirable_Compounds_Not_Yet_Synthesised), and taken on further to #459
