### ISSUE TITLE
Synthesis of internal alkyne

### ISSUE THREAD

**Issue by anna-schrecengost** [OpenSourceMalaria/OSM_To_Do_List#423]
Sebastian Dilones and I are going to be working on the synthesis of the internal alkyne version of "The Alkyl" at Haverford College:

![the alkyl internal alkyne](https://cloud.githubusercontent.com/assets/21691962/18258733/5760c370-73a9-11e6-923d-d648a3a08284.png)

FC(F)OC1=CC=C(C2=NN=C3C=NC=C(C#CC4=CC=CC=C4)N32)C=C1
InChI=1S/C20H12F2N4O/c21-20(22)27-17-10-7-15(8-11-17)19-25-24-18-13-23-12-16(26(18)19)9-6-14-4-2-1-3-5-14/h1-5,7-8,10-13,20H

Our synthetic scheme will draw from the scheme proposed in #403. We will be working closely with #424 and #431. Here is a link to the working lab notebook:
(http://malaria.ourexperiment.org/internal_alkyl)

**Comment by mattodd** [comment]
Great. How is this different from #424 ?

**Comment by anna-schrecengost** [comment]
Hi @mattodd --

Our mistake, the original issue has been fixed, thank you!

**Comment by MFernflower** [comment]
Minor nitpick, shouldnt this say internal alkyne?

**Comment by mattodd** [comment]
Hi @anna-schrecengost looks from the [ELN](http://malaria.ourexperiment.org/internal_alkyl) as though you're trying the crucial Sonogashira reaction, which is great! Are you having trouble with the picture files for the reaction schemes - having those there makes browsing the ELN much easier, obviously. And are you OK uploading data for the previous steps. When we come to publish the work, we're going to need all the primary NMR data etc.

**Comment by anna-schrecengost** [comment]
Hi @mattodd, we are in the process of cleaning up the NMRs to upload on the ELN and have uploaded the reaction schemes! have begun analysis of the sonogashira product and there is definitely something there - expect some github posts as we make sense of the spectra!

**Comment by mattodd** [comment]
I'm too excited.

**Comment by alintheopen** [comment]
Me too! 

For reaction schemes, if you follow the 'inserting an image' instructions in this [post](http://malaria.ourexperiment.org/osm_logos_and_templ/7773/Creating_a_General_Blog_Entry_on_the_Open_Source_Malaria_Electronic_Lab_Notebook_OSM_ELN.html) then you should be able to make the schemes larger so that they are easy to read as soon as the ELN page is opened :)

**Comment by anna-schrecengost** [comment]
Hi everyone, thank you for the comments. Here's an update on how the reaction went:

http://malaria.ourexperiment.org/internal_alkyl/15091/Fourth_step_in_synthesis_second_attempt_synthesis_of_34difluoromethoxyphenyl5phenylethynyl124triazolo43apyrazine.html

While we haven't yet been able to characterize the crude product at all, and TLC indicated the presence of a lot of starting material, we did see bright blue product spots visible in all of our TLC plates. Discussions with other students also attempting to synthesize this internal alkyne confirmed that they also observed the appearance of a bright blue spot that they think to be the product due to the extended conjugated system in the alkyne. Sebastian will be taking on characterization of this product this weekend/next week, time permitting. 

A couple of questions:

We had some issues filtering out all of the Pd/C - we filtered it through Celite, wetting it with water, but after several filtrations there was still a good bit of Pd/C left in the reaction mixture. Any suggestions for this, or does it just take more repetition? Also, how robust is the bright blue spot in the TLC as evidence for at least partial conversion to the product? We are going to test this hypothesis soon with characterization via NMR and mass spec, but want to make sure that we aren't taking any shots in the dark. Additionally, we observed the formation of clear crystals while we were filtering on top of the Celite and were wondering what the identity of these might be/what could have caused that.

**Comment by mattodd** [comment]
Hi @anna-schrecengost @sdilones - any updates on the NMR characterisation? A few notes:
1) I would say Celite filtration is the way to go. It might take a couple of goes/more celite.
2) Blue TLC spots - maybe evidence, given the new conjugation of the product. But separation/characterisation is the way to go.
3) I've added this compound to the [DCNYS](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Desirable_Compounds_Not_Yet_Synthesised) section of the wiki, so am closing this issue for now.
...but is anyone taking this on to try to solve that final coupling reaction? So close!
