### ISSUE TITLE
Beginning attempted synthesis of 'The Alkyl'

### ISSUE THREAD

**Issue by aamilder** [OpenSourceMalaria/OSM_To_Do_List#424]
Alexandra Morrison and I (Alexander Milder) are starting to work on the synthesis of the 3-(4-(difluoromethoxy)phenyl)-5-phenethyl-[1,2,4]triazolo[4,3-a]pyrazine or 'The Alkyl.' We will be following the proposed synthesis outlined in issue #403. Your can follow our progress and learn about our process with our Electronic Lab Notebook found [here](http://malaria.ourexperiment.org/morrison_and_milder)

(![image](https://cloud.githubusercontent.com/assets/21690169/18179510/b6e8eb3a-7050-11e6-85c1-3db1a9080709.png))

FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(CCC4=CC=CC=C4)N32
InChI=1S/C20H16F2N4O/c21-20(22)27-17-10-7-15(8-11-17)19-25-24-18-13-23-12-16(26(18)19)9-6-14-4-2-1-3-5-14/h1-5,7-8,10-13,20H,6,9H2
QKTHSIJWBSHMDZ-UHFFFAOYSA-N

**Comment by mattodd** [comment]
Great that you're starting this @aamilder . Steps up to the chlorinated core are all pretty well-established. The Grignard (likely cuprate needed) addition is definitely part of the discovery phase here! I do wonder whether this alkyl compound might serve as the starting material for an attempt at the ketone #425 via oxidation. i.e. the reverse of your lowest scheme. One for the future.

**Comment by MFernflower** [comment]
@aamilder @mattodd @rbroadrup-HC In theory one could exchange the chlorine for a iodine to bolster reactivity and yields (and possibly allow for use of the phenethyl Grignard) - main disadvantage is that many iodine compounds are photosensitive

**Comment by aamilder** [comment]
We have decided to proceed utilizing the reaction of a phenethyl Grignard with the chlorinated core. While we are not quite sure yet if the reaction will succeed, it will allow us to eliminate the extra step that would be needed if we used a Sonagashira instead.

**Comment by MFernflower** [comment]
If for whatever reason it fails you could always try a cl-i exchange on the tp core and do the reaction in the dark? @aamilder

**Comment by mattodd** [comment]
OK, great @aamilder - could you please add a link to the post at the top of this Issue that goes to the lab notebook that we ought to be following for this synthesis?

**Comment by aemorrison** [comment]
@aamilder and I have been successfully working on this synthesis, our lab notebook can be found [here](http://malaria.ourexperiment.org/morrison_and_milder).

**Comment by aamilder** [comment]
@mattodd Done. Let us know if there is anything else we can do to make our data and information more accessible.

**Comment by aamilder** [comment]
@MFernflower Switching out the Cl for I is a great idea. Unfortunately we are limited by time and will probably only have time to try the regular Gringard addition to the chlorinated core as outlined. However, if that fails (which it hopefully won't) we have the option to either trying swapping out the Cl for I as you suggested or trying an organocopper reagent. If we are successful, however, future groups working on this project could try these pathways anyways to see if they can boost yield.

**Comment by mattodd** [comment]
Looks good @aamilder - hopefully that condensation worked. You asked about what else you can do - the only crucial thing to remember is to upload all the raw data for your experiments, so when we come to publish, it's all there already. Very nice that you're including photos of reactions, and links to the precedents you're following. Really looking forward to seeing if this cuprate reaction's going to work.

**Comment by mattodd** [comment]
So - @aamilder @aemorrison - [that last coupling from Oct 27th](http://malaria.ourexperiment.org/morrison_and_milder/15115/Synthesis_of_34difluoromethoxyphenyl5phenylethynyl124triazolo43apyrazine_AAMAEM_4.html) - what did you get from the purification? 
I've added this post to the [DCNYS](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Desirable_Compounds_Not_Yet_Synthesised) section of the wiki, so we can close this Issue if you're done. But is anyone following you?

**Comment by mattodd** [comment]
Wiki up to date. Closing since I think this target is parked for the moment. Future work should be based on investigating the key cross-coupling reaction.
