### ISSUE TITLE
Starting Synthesis of "The Ketone"

### ISSUE THREAD

**Issue by jhalifax** [OpenSourceMalaria/OSM_To_Do_List#425]
Steph Terrell and I will be attempting to synthesize "the ketone" according to the reaction scheme below borrowed from #408. 
![the ketone](https://cloud.githubusercontent.com/assets/21691747/18189733/5ef65882-708b-11e6-921f-082d833cd6b7.png)

The lab notebook can be found here: http://malaria.ourexperiment.org/ketone_synthesis

**Comment by mattodd** [comment]
Great news @jhalifax . @edwintse can fill you in on his experiences to date with this route.

**Comment by edwintse** [comment]
Hi guys,
The literature reference for the procedures in 31-1 and 33-1 are [here](http://pubs.acs.org/doi/abs/10.1021/jo802650s). The displacement with hydrazine, condensation and cyclisation are procedures that are well established from the CRO.

**Comment by jhalifax** [comment]
Having looked more in depth at the scheme from #408, Steph and I were worried that the third step may prove problematic, as it was for @edwintse . Our thinking is that the enolate, since it is a bulky nucleophile, will prefer to attack the site with the Cl rather than the ester as the ester is more sterically hindered. If this indeed occurs we won't get the desired intermediate and the Cl will not be present to serve as a leaving group in the next step. 

With this in mind we have come up with a second scheme to synthesize "the ketone," which can be seen below:

![the ketone 2nd scheme](https://cloud.githubusercontent.com/assets/21691747/18232426/48b6f0f4-729d-11e6-9fb2-8e76dcdbdab4.png)

In this scheme we switched a few steps around in an attempt to avoid this problem. We will use the nucleophilic enolate before the Cl is attached to avoid this problem. This change in sequence necessitates adding a protective group to the ketone to avoid a baeyer villiger reaction when the mCPBA is added. We have chosen to use ethylene glycol as the protective group, but welcome feedback if others have different ideas.

**Comment by mattodd** [comment]
It's a good idea to rethink based on what @edwintse found. Clearly this new route is steppy. I've been meaning to ask: what about reacting the core chloride () with an acyl anion equivalent, i.e.
![acyl anion equivs](https://cloud.githubusercontent.com/assets/4386101/18246782/40dd327a-73b1-11e6-8def-e8b69a362350.jpg)
Dithianes are the obvious possibility, but maybe there are [others](http://onlinelibrary.wiley.com/doi/10.1002/anie.200301702/abstract) better known to react with the kind of electrophile we have here. My gut tells me we'd need to make the anion "soft" to make it react well, but I've not done a lit search.

**Comment by mattodd** [comment]
Hi John - I see from the [ELN](http://malaria.ourexperiment.org/ketone_synthesis) that you think you've made the decarboxylated material? Is that right, but that it just needs purification? Is there any chance you could include some more structure drawings in your ELN write-ups, just so we're clear which structures you're referring to? And maybe correlate these to compound codes in your scheme above, somehow? A way that many of us are using to refer to compounds is using a scheme I wrote down [here](http://openwetware.org/wiki/Todd:Guidelines#Reaction_Numbering) (ignoring the old-fashioned reference to page numbers...), in which case the decarboxylation might be JH-2-1 since it's the first attempt at your second reaction?

**Comment by jhalifax** [comment]
@mattodd We indeed think we have the decarboxylated material (JH-2-2-1). We performed flash chromatography on it using biotage and according to GC-MS we successfully isolated it. We are currently running an NMR to double check, as we suspect there may still be some impurities present even after the flash chromatography. I will go back and edit the ELN to add more structures to make it clearer. I will also use your reference system but with a slight tweak; as we were running two schemes simultaneously to keep track of which reactions belonged to each scheme we labeled our reactions as follows: scheme #-reaction#-attempt# (so what you called JH-2-1 in your comment we have called JHST-2-2-1).

**Comment by jhalifax** [comment]
Due to the inability to produce sufficient pure product from JHST-1-1-2, (first scheme, first reaction, second attempt) Steph and I have stopped working on the first scheme for now. This scheme was closely based on Ed's attempt to synthesize "the ketone," and while the problems we had were earlier in the scheme than he had, we believed in the limited time we had we could get further following scheme 2. We have so far been able to reach the second step of the second scheme (getting product for JHST-2-2-1) after some difficulty with the first step.

**Comment by mattodd** [comment]
Fingers crossed for the NMR of the carboxylated material! Yes, please use any numbering system you like, just so long as you use it consistently and liberally, so that we all know which structures in schemes you're referring to, plus links to experiment write-ups on the ELN.

**Comment by mattodd** [comment]
Hi @jhalifax - any update/summary here? If this part of the project has been parked, you can go ahead and close this issue. It'd be great if there were any compounds that are pure that could be given to other students working on this target (Haverford or elsewhere).
Links have been installed for The Ketone on the [DCNYS section of the wiki](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Desirable_Compounds_Not_Yet_Synthesised).
