### ISSUE TITLE
Start Synthesis of "the hERG Evador"

### ISSUE THREAD

**Issue by RosalindXu** [OpenSourceMalaria/OSM_To_Do_List#427]
Cicy and I have adopted "the hERG Evador" for our Chem Superlab at Haverford College, using the synthetic scheme below. 
![the herg evador](https://cloud.githubusercontent.com/assets/21690009/18193034/afb0c03e-70a7-11e6-88f1-cdac9f058276.png)

FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC(C(O)=O)[Ar])N32

**Comment by mattodd** [comment]
Lab book is [here](http://malaria.ourexperiment.org/chem_301_fall_2016_a) @RosalindXu ?

**Comment by RosalindXu** [comment]
Yes, that is our lab book! I will add the link. 
**Haverford College Superlab: Synthesis of The hERG Evador**
http://malaria.ourexperiment.org/chem_301_fall_2016_a

**Comment by mattodd** [comment]
Hi @RosalindXu - you have lots of entries in the [ELN](http://malaria.ourexperiment.org/chem_301_fall_2016_a), but with nothing in them? Is that because you're using a paper lab book first and transcribing? I think that doubles your work - what about putting the data straight onto the ELN first? Might make it easier... We'd all love to know how you're getting on with this compound!

**Comment by RosalindXu** [comment]
Hi @mattodd : All experiments with entries in ELN have been conducted; we are currently filling it out from records in our paper notebook. I would totally agree---it should have made things easier should we use ELN first!

Currently, we have made a lot of attempts to add tropic acid dianion directly on to the triazopyrazine core. We have explored LDA and NaH as bases to deprotonate tropic acid. We do observe reaction happening, and the product appears to be an acid; but a recent NMR spectrum (came out yesterday night) suggests that the product seems to come from the decomposition of the chloropyrazine moiety, when treated with a very strong base (like LDA and NaH), followed by basic hydrolysis of a cyanide moiety when quenching the reaction with water...we should have a better idea what is going on after we take a COSY spectrum of the product.

Our next step is probably to try adding tropic acid using the KOH/18-crown-6 protocol. We are not sure how the nucleophile being a dianion is going to affect the addition, but it probably worths a try. If this does not work out, we will probably advise the group taking over our project to add the nucleophile with THP protection group first, then oxidize it to form the acid. We will have some triazopyrazine precursor to pass over to them.

**Comment by RosalindXu** [comment]
Final updates on our compound:

The scheme below summarizes the progress we have made so far, and suggestion for future steps. Arrow indicated successful reactions; dotted arrow indicated planned reactions; arrows with a cross indicate failed reactions. 
![the herg evador current](https://cloud.githubusercontent.com/assets/21690009/19746218/5d8c2db2-9ba3-11e6-8bb3-2a2059853041.png)
In Step 4, we made a phenol instead. However, the phenol may serve as a starting point for future synthesis: first replace -OH on tropic acid by -Cl, then use a SN1 type reaction to link it to the pyrazine ring. [This reference](http://www.sciencedirect.com/science/article/pii/S0960894X15301505) shows a similar reaction that worked; details can be found in their supplemental information section. In this is to be pursued, the phenol probably can be synthesized via NaOH/H2O, instead of using tropic acid/NaH...

Alternatively, we can try:
![the herg evador recommended](https://cloud.githubusercontent.com/assets/21690009/19746348/07a83aa2-9ba4-11e6-884b-5b375998393f.png)
All steps besides the last in this scheme have been successful. The last step involves an oxidation. However, there seems to be concern that t[he core may be oxidized in physiological conditions](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Aldehyde_Oxidase_Assay), so the oxidative environment in the last step might do something bad--but it might not.

**Comment by mattodd** [comment]
Hi @RosalindXu - by "final" you mean you're finishing in the lab?

**Comment by RosalindXu** [comment]
Hi @mattodd: Unfortunately, our Superlab this year is divided into two quarters...we definitely hoped that we could have more time working on this! Hopefully our project will be transferred to another group taking this class next quarter.

**Comment by mattodd** [comment]
Added this to [DCNYS](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Desirable_Compounds_Not_Yet_Synthesised) section of wiki. Closing. @RosalindXu is another team taking this on, or is this target being parked by Haverford now?

**Comment by RosalindXu** [comment]
@mattodd I am afraid the synthesis is halted right now--We do not have as many students in this session in the second quarter of Superlab as in the first quarter, so not all targets were taken over.
