### ISSUE TITLE
Starting Synthesis of "The Nemesis"

### ISSUE THREAD

**Issue by pennypresident** [OpenSourceMalaria/OSM_To_Do_List#430]
Marco Rivas (@GeneralGrivas) and myself, Lincoln Satterthwaite, are going to work on synthesizing "The Nemesis" as shown below, picture from #409. The lab notebook can be found here: http://malaria.ourexperiment.org/hcnemesis16

![image](https://cloud.githubusercontent.com/assets/21691808/18213147/b7034556-7114-11e6-85be-f0f1118a0767.png)

OC(C1=CC=CC=C1)COC2=CN=CC3=NN=C(C4CNCCC4)N32
InChI=1S/C18H21N5O2/c24-15(13-5-2-1-3-6-13)12-25-17-11-20-10-16-21-22-18(23(16)17)14-7-4-8-19-9-14/h1-3,5-6,10-11,14-15,19,24H,4,7-9,12H2
SNDLBGDEOQPBOQ-UHFFFAOYSA-N

**Comment by pennypresident** [comment]
We've completed the first reaction with hydrazine, which we first did on a 1g scale and then upped to a 2g scale for further use. Currently waiting for the NMR to run proton and 13C on the second experiment. We did take NMR data on the first run, but the product didn't dissolve very well in CDCl3 so the spectrum is pretty terrible. We've got the key aromatic peaks though, so it's promising. TLC implies that we did indeed synthesize the same compound in both experiments.

**Comment by GeneralGrivas** [comment]
Just an update:
We are currently working on synthesizing the pyrazine substituent (MRLS [8-1](http://malaria.ourexperiment.org/hcnemesis16/14824/Synthesis_of_2phenyl2tetrahydro2Hpyran2yloxyethan1ol_MRLS_81.html)) for the above scheme (2-phenyl-2-((tetrahydro-2H-pyran-2-yl)oxy)ethan-1-ol). We followed the procedure outlined in [AEW 221-2](http://malaria.ourexperiment.org/triazolopyrazine_se/10895/Synthesis_of_2phenyl2tetrahydro2Hpyran2yloxyethan1ol_AEW_2212.html) .

We have isolated two fractions, and have taken NMRs of both. However, I'm having a little trouble assigning peaks--there are a couple notable differences between the proton spectra for the two fractions. For instance, there is a triplet near 4.9 ppm and a doublet of doublets (?) near 4.75 in fraction 2. These peaks are also faintly in the proton NMR for fraction 1, but in addition to 2 clusters of peaks (dd) at 4.8 ppm and 4.5 ppm. There is also a broad peak at 3 ppm in fraction 1, but not fraction 2. There is, however, a broad peak at 2.2 ppm in fraction 2 (which MestReNova thinks is a water impurity), but a sharp peak near 2.2 ppm in fraction 1. The 13C NMR look mostly identical.  All these spectra are attached to the lab notebook entry linked above.

I'm wondering if I could get any opinions regarding these spectra. Does it look like the right stuff could be in either of these fractions? What are the structural differences (if any) between the fractions?

**Comment by GeneralGrivas** [comment]
@mattodd @alintheopen 
My partner @pennypresident and I have been working hard to synthesize the above compound, and we're making good progress! (see [our lab notebook here](http://malaria.ourexperiment.org/hcnemesis16))

We would like to have a better understanding of the compound, particularly in regards to how it relates to the broader goals of the Series 4 project. We have seen the Nemesis mentioned briefly in past issues (#358 ) and we are wondering if you two could help elucidate the origins of the molecule. For instance, what about this molecule is desirable in terms of solubility, potency, and metabolic stability?
It would also be super helpful if you could direct us to any resources that would help us learn more about our molecule. 

Thanks,
Marco R
Sent from my rotary phone

**Comment by MedChemProf** [comment]
@pennypresident @GeneralGrivas In answer to your previous question regarding your isolation of two fractions that both appear to be product, you must consider the stereochemistry of the THP protecting group. Your starting material in the reaction (the THP protected Mandelic Acid ester) is actually a mixture of 4 stereoisomers where one of the stereoisomers is on the Mandelic Acid and one is on the anomeric center of the tetrahydropyran ring. Two of the sets of stereoisomers are mirror images of each other and are known as Enantiomers and the other sets of non-mirror images are known as Diastereomers. The Enantiomers cannot be differentiated in this case by NMR (without taking additional steps) and the Enantiomers would behave exactly the same on your silica gel column (although a chiral solid phase column may allow you to separate.) The two fractions you have isolated look to be Diastereomers of one another. Diastereomers would have slightly different NMR spectrum and also would behave differently on a column. The THP protecting group is very useful, but it does introduce this wrinkle with introducing a stereocenter. Often, it is not possible to separate the Diastereomers and the NMR is of the complex mixture. This is a nice case where they can be separated. 
![stereoisomers](https://cloud.githubusercontent.com/assets/14179120/19436454/2f963d4c-943e-11e6-964c-2e3df08542ef.jpg)

**Comment by GeneralGrivas** [comment]
@MedChemProf 
Thanks so much! That was incredibly helpful--totally forgot about the stereocenter on the THP group.

**Comment by mattodd** [comment]
Hi there - the Nemesis originated from a desire to deplanarise the molecules - to reduce the number of planar Ar rings as part of a general approach to improving solubility. [Cyclohexane and tetrahydropyran as substituents give inactives in this position](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Modification_of_the_Triazole_Substitution). So piperidine seemed like a good choice, providing complementary functionality (H bond donor).

**Comment by pennypresident** [comment]
Okie doke, @GeneralGrivas and I have stepped back from this project to hand it off to the next quarter of superlab here at Haverford. We (well, mostly Marco for this route of synthesis) made what we think to be pretty good progress, with some success and lots of failure along the way. Here's the overview: 
![nemesis primary scheme](https://cloud.githubusercontent.com/assets/21691808/19793971/0fe4139a-9c9d-11e6-97e7-592edef8e16f.PNG)


Not bad. Some of the products were a little sketchy and kind of impure, but lots of them were usable. Electronic lab notebook is fully up to date with the reactions that we did. 


Our last reaction, MRLS [9-1,](http://malaria.ourexperiment.org/hcnemesis16/14971/Synthesis_of_tertbutyl_352phenyl2tetrahydro2Hpyran2yloxyethoxy124triazolo43apyrazin3ylpiperidine1carboxylate_MRLS_91.html) has yet to be purified. It is difficult to know whether the reaction was successful through crude NMR, as it’s rather messy (it is on the ELN though, if you would like to look at it). It’s worth purifying to see if we can get a cleaner spectra. If we’re lucky and the reaction worked, then we’ll only have the deprotection step left.

**Comment by mattodd** [comment]
Fantastic work, here @pennypresident @GeneralGrivas . Taken on to #466 . Links installed on [DCNYS section of wiki](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Desirable_Compounds_Not_Yet_Synthesised), so closing this issue for now.
