### ISSUE TITLE
Starting synthesis on a partially reduced version of "The Alkyl"

### ISSUE THREAD

**Issue by aschankler** [OpenSourceMalaria/OSM_To_Do_List#431]
Owen Janson, George O'Hara and I (@OHaraJansonSchankler) will begin synthesis of a version of "The Alkyl" with an internal cis-alkene as discussed in #403. Our lab notebook can be found at http://malaria.ourexperiment.org/reduced_alkyl. We plan to follow the synthetic scheme outlined below:

![reducedalkyl](https://cloud.githubusercontent.com/assets/19557496/18209308/3769465a-7101-11e6-9b1b-926dcca741b8.png)

(SMILES)
FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(/C=C\C4=CC=CC=C4)N32
InChI=1S/C20H14F2N4O/c21-20(22)27-17-10-7-15(8-11-17)19-25-24-18-13-23-12-16(26(18)19)9-6-14-4-2-1-3-5-14/h1-13,20H/b9-6-

**Comment by mattodd** [comment]
Lots of progress on the [ELN](http://malaria.ourexperiment.org/reduced_alkyl) for this target, and what you found is obviously relevant to the alkyl (#424) and internal alkyne (#423) projects. But are you able to summarise briefly where you're up to here @aschankler @OHaraJansonSchankler? Looks like the final coupling was a problem? 
If you've finished, is another group pursuing this target?
Added in any event to the [DCNYS](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Desirable_Compounds_Not_Yet_Synthesised) section of the wiki.

**Comment by aschankler** [comment]
We got the first three reactions working and got reasonable spectra of the first two intermediates. The product of the third reaction will need to be purified and run with different NMR parameters as discussed in #454.

The Sonogashira coupling did give us trouble. We first tried a reaction catalyzed by indium chloride, but it didn't produce any product. Our second try of the indium catalyzed reaction was run 20 degrees hotter than the original reference indicated and we still saw no reaction, so we think that this reaction does not work for our substrate. We also tried a palladium catalyzed coupling and the TLC looks promising, but the product is still awaiting further analysis.

Our group is no longer actively working on this target, and I don't believe that anyone is currently working on this at Haverford. @rbroadrup-HC, is a group planning to pick up this target?

**Comment by mattodd** [comment]
OK, closing for now, but the wiki is up to date. It seems like that coupling reaction is the key reaction to go after if this target is continued. If you have any intermediates available in quantity, then I guess there is always the chance you could pass on to the next team, or even mail to teams based elsewhere who might want to have a go at the cross-coupling.
