### ISSUE TITLE
Troubles with the synthesis of MMV670437 (dimethylamine) for the Frontrunners

### ISSUE THREAD

**Issue by edwintse** [OpenSourceMalaria/OSM_To_Do_List#435]
As part of the Frontrunners resynthesis (#400), we require the dimethylamine compound shown below.

![untitled wiley-1](https://cloud.githubusercontent.com/assets/18062981/18536515/360bf830-7b41-11e6-95ed-2e32e15454f5.jpg)

As of now, we have been unsuccessful in resynthesising this compound. @alintheopen has been successful in the synthesis of the hydroxymethylester using the route below.

![untitled wiley-1](https://cloud.githubusercontent.com/assets/18062981/18536368/1d69e0a4-7b40-11e6-95a7-5f317b8b5ca6.jpg)

The plan was then to mesylate the hydroxy group, subsequently displace it with dimethylamine, reduce the ester and couple to the core. Mesylation appears to proceed with no problems ([here](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/NDE4LjZ8MTUwOS8zMjIvVHJlZU5vZGUvMTQ5NjI3NDAzMXwxMDYyLjY=
), [here](http://malaria.ourexperiment.org/triazolopyrazine_se/14422/Synthesis_of_methyl_234difluorophenyl2methylsulfonyloxyacetate_AEW_3081.html)), however displacement doesn't appear to give significant yields of the desired product ([here](http://malaria.ourexperiment.org/triazolopyrazine_se/14464/Synthesis_of_methyl_234difluorophenyl2dimethylaminoacetate_AEW_3101.html), [here](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/NDIzLjh8MTUwOS8zMjYvVHJlZU5vZGUvMjMyNzY4ODg1fDEwNzUuOA==
)).

![untitled wiley-1](https://cloud.githubusercontent.com/assets/18062981/18536377/31a95568-7b40-11e6-8211-a8fb032e1452.jpg)

A Mitsunobu reaction was also attempted directly on the hydroxymethylester ([here](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/NDI2LjR8MTUwOS8zMjgvVHJlZU5vZGUvNTYxMzkxNjQ5fDEwODIuNA==
)) which appeared to give the desired product, however attempted reduction of the ester appears to have been unsuccessful ([here](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/NDM5LjR8MTUwOS8zMzgvVHJlZU5vZGUvNzExNzE3OTU3fDExMTUuNA==
))

![untitled wiley-1](https://cloud.githubusercontent.com/assets/18062981/18536729/e2c5be8e-7b42-11e6-9c6c-e54fd3927b5b.jpg)

Mitsunobu was also attempted on MMV672687 shown below. The reaction appeared to have been successful ([here](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/NDM2Ljh8MTUwOS8zMzYvVHJlZU5vZGUvMTc2ODEwNTIyMXwxMTA4Ljg=
)), however attempts at separating the PPh3O byproduct by crystallising it out from ether was successful only to an extent. Prep TLC was successful at removing a majority of the PPh3O but NMR indicates it is still present.

![untitled wiley-1](https://cloud.githubusercontent.com/assets/18062981/18536562/774ad15e-7b41-11e6-8148-4714efefe043.jpg)

Another alternative approach shown below is currently being investigated. At this stage, oxidation with DMP doesn't appear to be proceeding ([here](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/NDQzLjN8MTUwOS8zNDEvVHJlZU5vZGUvMzcxNzg1Mzg3OXwxMTI1LjM=
)).

![untitled wiley-1](https://cloud.githubusercontent.com/assets/18062981/18536661/4ec114f4-7b42-11e6-9b9a-6c194bea2e16.jpg)

A final approach has been suggested of oxidising the hydroxymethylester to the ketomethylester then selective reductive amination. From surveying the literature, oxidation of the hydroxy group can be done with MnO2 ([patent](https://www.google.com.au/patents/WO2012138590A1?cl=en&dq=WO+2012138590+A1&hl=en&sa=X&ved=0ahUKEwjasMzcsZDPAhWr3YMKHU22DQYQ6AEIGzAA)). Most methods then proceed through the formation of an oxime then reaction with a Grignard reagent ([DOI](/10.1016/j.tetlet.2012.08.091)). It doesn't appear to work with MeMgBr. One method that may work to give the dimethylamine involves treatment with sodium triacetoxyborohydride ([patent](https://www.google.com.au/patents/WO2008124848A1?cl=en&dq=WO+2008124848+A1&hl=en&sa=X&ved=0ahUKEwjIw6CMspDPAhWh7YMKHaBWCjEQ6AEIHTAA))

![untitled wiley-1](https://cloud.githubusercontent.com/assets/18062981/18537072/114bd65a-7b46-11e6-9cf3-b971f2fce777.jpg)

Any suggestions on what to do next would be greatly appreciated.

**Comment by drc007** [comment]
In the mitsunobu it is possible you have triphenylphosphine carried over, which is then oxidising.  You can try to add CuCl to the solution of your crude product in acetone. CuClxTPP complex is insoluble in this solvent.
An alternative to DMP might be the old school MnO2

**Comment by MedChemProf** [comment]
@edwintse I have never been a big fan of MnO2. It works well in particular cases, but I have also observed it not always acting as a general oxidant (even though the benzyl alcohol situation is one in which it should work.) I would actually opt to using TPAP which I have found to always be dependable. It might also be a good idea to look at a variation of your original path and re-try the ester (or acid) reduction. My gut feeling is that there must have been either something wrong with the starting material or reducing agent to prevent that reaction from running properly. Maybe making the amino ester through alternate route below would confirm compound identity and be scalable.
![suggestion](https://cloud.githubusercontent.com/assets/14179120/18550049/0e1ba5a8-7b20-11e6-8983-26fb3b2840be.png)

**Comment by MFernflower** [comment]
I agree fully with @MedChemProf - @edwintse if you can produce the ketomethylester drug it would be nice to see some of it sent off for testing!

**Comment by MFernflower** [comment]
@edwintse @MedChemProf Nice paper detailing the process to use TPAP: http://www.mdpi.org/molecules/papers/50100082.pdf

**Comment by mattodd** [comment]
@edwintse @MedChemProf @alintheopen obv the attraction of the alternative proposed by Chase here is eliminating the need for cyanide in the first place. Ed maybe a quick SciFinder assessment of precedence of the route's first two steps (bromination and displacement, but looks simple) then availability of the S/M? Can't compromise on the 3,4-di-F.

**Comment by MFernflower** [comment]
@mattodd cant seem to find ethyl 2‐(3,4‐difluorophenyl)acetate for sale anywhere

**Comment by mattodd** [comment]
Doesn't need to be the ethyl ester, given that that part is ultimately removed. Methyl, e.g.

**Comment by MFernflower** [comment]
@mattodd could not find the methyl ester either.. The free acid is easy to find on the usual suspects so we could make an ester of it with ethanol or isopropanol?

**Comment by alintheopen** [comment]
free acid would be perfect!

**Comment by MFernflower** [comment]
Sigma is selling 3,4-Difluorophenylacetic acid  for $188 usd for 5 grams -
dont know if that's in your price range? @alintheopen

**Comment by mrwns** [comment]
MacMillan has published a nice way to make the alpha-amines directly from the phenyl acetic acid ester with CuBr and air. I was able to reproduce it with Propiophenone and Morpholine. The scope has more amines.

![macmillan](https://cloud.githubusercontent.com/assets/13124103/18581408/5d1c3d74-7bf8-11e6-963b-db1034b9b35e.png)

http://pubs.acs.org/doi/abs/10.1021/ja4096472

**Comment by MFernflower** [comment]
@mrwns Do you think this reaction with work with dimethylamine and methyl 3,4-difluorophenylacetate ?

**Comment by mrwns** [comment]
@MFernflower In the paper, the most related amine used was diethylamine, so it might work with dimethylamine too. The reaction is supposed to proceed via the α-brominated ester.

otherwise, this Hartwig-α-arylation could be tried:
![hartwig](https://cloud.githubusercontent.com/assets/13124103/18594094/39c69cf0-7c36-11e6-9a59-1ab9bf74b8db.png)


http://www.sciencedirect.com/science/article/pii/S0968089614004738
smiles:
BrC1=CC=CC=C1.O=C(CN(C)C)OCC>>CN(C(C(OCC)=O)C2=CC=CC=C2)C

**Comment by edwintse** [comment]
After a month of working towards this compound, I'm happy to announce that the dimethylamine Frontrunner compound has been made (as confirmed by NMR and MS). The route used is shown below (big thanks to @MedChemProf for the suggestion). The relevant experimental entries are in my ELN.

![dimethylamine](https://cloud.githubusercontent.com/assets/18062981/19753869/20814450-9c54-11e6-961c-2b69ea5bd4c7.jpg)

With this final compound now done, we will be able to send off the Frontrunners and my new analogues to both Syngene and the Kirk lab for screening against _P. falciparum_ and PfATP4 respectively. The relevant issues (#400, #420) will be updated when the compounds are in the air.

Once again, thanks to everyone for the great suggestions!!

**Comment by alintheopen** [comment]
https://www.youtube.com/watch?v=koJlIGDImiU

**Comment by MFernflower** [comment]
I thought the day would never come but it did! Thanks again @edwintse for putting some of my ideas into action!
