### ISSUE TITLE
OSM poster presented at the ICTMM 2016

### ISSUE THREAD

**Issue by edwintse** [OpenSourceMalaria/OSM_To_Do_List#437]
Downloadable pdf and powerpoint version of the poster presented at the 2016 International Congress for Tropical Medicine and Malaria.

![ictmm poster_2016 copy 2](https://cloud.githubusercontent.com/assets/18062981/18807120/ba1f5962-8282-11e6-8e48-b67e8fdd13fe.jpg)

[ICTMM Poster_2016.pdf](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/491028/ICTMM.Poster_2016.pdf)

[ICTMM Poster_2016.pptx](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/492953/ICTMM.Poster_2016.pptx)

**Comment by alintheopen** [comment]
lovely work @edwintse

**Comment by mattodd** [comment]
Yes, great @edwintse . Could you upload the Powerpoint file? @MalBinns might be able to make use of it for a poster he wants to make. I will also upload these to Labtrove as an extra archive location.

**Comment by edwintse** [comment]
Updated with download link for Powerpoint file.

**Comment by mattodd** [comment]
Backed up to [ELN](http://malaria.ourexperiment.org/osdd_malaria_shared/14912/OSM_Poster_Presented_by_Ed_Tse_at_the_ICTMM_Conference_in_Brisbane_in_Sept_2016.html). Content licence as always CC-BY. Closing.
