### ISSUE TITLE
Advice on Impurities in NMR and Moving Forward with synthesis of "The Burns"

### ISSUE THREAD

**Issue by evonkrusenstiern** [OpenSourceMalaria/OSM_To_Do_List#438]
@claudianguyen95 and I are making progress on our attempt to synthesize the Burns (cross ref to #422). 

1) We just finished synthesizing 1-(6-chloropyrazin-2-yl)-2,2,2-trifluoroethan-1-one (smiles: ClC1=CN=CC(C(C(F)(F)F)=O)=N1) (image of structure attached). Based on our NMR and GCMS data for our product, we are fairly certain that we successfully made it, but we have some confusing impurities in our NMR spectra, and we were curious if anyone had any idea what they could be. The spectra are in the latest entry in our ELN, found here: http://malaria.ourexperiment.org/the_burns 

2) For our next step, we are performing a reductive amination to replace the ketone with a benzylamine to make N-benzyl-1-(6-chloropyrazin-2-yl)-2,2,2-trifluoroethan-1-amine (smiles: ClC1=CN=CC(C(NCC2=CC=CC=C2)C(F)(F)F)=N1) (image of structure attached). We are currently running this reaction using sodium cyanoborohydride and titanium tetrachloride to activate the ketone. We are concerned, though, that the chlorine on our compound has a risk of reacting as well. In the next step of our proposed synthesis, we hope to replace the chlorine with a diamine, and we have considered doing this prior to the reductive amination, but we're not sure if that would be any better. We'd love any ideas or advice on how to prevent both sites from reacting at the same time!!

<img width="343" alt="screen shot 2016-10-06 at 2 38 06 pm" src="https://cloud.githubusercontent.com/assets/21690013/19165889/917a7b90-8bd3-11e6-8c96-8ddd7d8543ce.png">
<img width="304" alt="screen shot 2016-10-06 at 2 32 07 pm" src="https://cloud.githubusercontent.com/assets/21690013/19165888/917a85ea-8bd3-11e6-9a82-046d088dd944.png">

**Comment by MedChemProf** [comment]
@evonkrusenstiern @claudianguyen95 - I only had a chance to quickly look over your data, but it looks like the major product from your reaction is 2-(6-chloropyrazin-2-yl)-1,1,1,3,3,3-hexafluoropropan-2-ol (SMILES: ClC1=CN=CC(C(O)(C(F)(F)F)C(F)(F)F)=N1). Which is the large peak (fractions 2 & 3) in your Biotage Trace and has the m/z 279.9, 281.9.
![majorproduct](https://cloud.githubusercontent.com/assets/14179120/19167220/b0dfd9f8-8bd8-11e6-9028-57c68544b7cf.png)
It looks like there is product in Fractions 6 & 7 as evidenced by the m/z 209.9, 211.9
I could not tell if your 1H NMR was of the crude mixture or of one of the fractions after removal of solvent. If that was the crude, I would focus on Fractions 6 & 7 to isolate the desired product and to possibly re-purify if required. If you are going to repeat, suggest looking at shortening the reaction time, or possibly running at 0C. May also want to reduce the trimethylsilyltrifluoro-methane to 1 equivalent.

**Comment by MFernflower** [comment]
I second the idea of running the reaction at low tempature

**Comment by mattodd** [comment]
Nice analysis @MedChemProf . As for the second reaction, I'd strongly recommend just trying it at first, to see what you get, and then we can adjust accordingly. Definite risk of reaction at both sites, but let's see if that eventuates?

**Comment by mattodd** [comment]
Hi @claudianguyen95 and @evonkrusenstiern - just wondering how that reductive amination went - your [ELN](http://malaria.ourexperiment.org/the_burns) doesn't mention it? In fact if you think that Chase's analysis of your product is correct, and you're continuing with the synthesis, maybe we can close this issue?

**Comment by claudianguyen95** [comment]
Hi @mattodd - @evonkrusenstiern and I just finished the reductive amination and just analyzed the crude product via TLC and NMR yesterday. TLC looked clean, but I have yet to take a look at the NMR results (will do so tomorrow in lab). We appreciate the help and I believe can probably close this issue!

**Comment by mattodd** [comment]
OK, great, looking forward to seeing the data you mention on the ELN! Closing for now.
