### ISSUE TITLE
Advice for alternate Step 1 synthesis of "The 8" impurities/starting material in NMR

### ISSUE THREAD

**Issue by camckeon** [OpenSourceMalaria/OSM_To_Do_List#441]
Raina Fitzpatrick and I, Caroline McKeon, are working on synthesizing "The 8" (see #429) and after a series of unsuccessful attempts to methylate 2,6-dichloropyrazine with our original reaction scheme, we changed our starting material and are going after the monomethylated 2,6 dichloropyrazine from a different angle. See reaction below. 
![screen shot 2016-10-17 at 9 14 42 pm](https://cloud.githubusercontent.com/assets/21690053/19461006/d03f4818-94ae-11e6-8848-7c9bf1487c36.png)
We have completed the first step, and took the NMR before purification. The spectra has a mysterious, strong peaks at 7.25 and 1.65 ppm that we are having a hard time explaining.
We think the 2.5 ppm peak corresponds to the methyl protons and the 7.9 ppm/8.05 ppm doublet corresponds to the aromatic protons. 
The paper we are pulling the procedure from was not synthesizing a molecule similar enough to ours that their expected shifts could be of use.  
NMR of starting material (2-methylpyrazine) and product(?) (di-N-oxide) is below. 
[Alt_Meth_SM1.pdf](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/535067/Alt_Meth_SM1.pdf)
[Alt_Meth_S1.pdf](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/535080/Alt_Meth_S1.pdf)

Any NMR insight would be excellent! Thank you!

**Comment by MedChemProf** [comment]
@camckeon The peaks you have labeled 7.25 and 1.65 correspond to CHCl3 (which comprises less than 1% of your CDCl3) and water (which shows up at 1.58.) I do not think your spectrum are referenced correctly, so the shifts are slightly off. If you took a blank NMR of only the CDCl3, you would see both of these peaks. Your first sample of the starting material was too concentrated and so the CHCl3 and water were only very minor peaks. I suggest referencing the spectrum, labeling all of the major peaks and also include integrations.

**Comment by mattodd** [comment]
Agreed. But @camckeon could I urge you to deposit all data in the ELN - i.e. for your unsuccessful attempts, as well as for this latest reaction? It's crucial that we can all see what you've done in detail. Is that first compound known anywhere in the literature beyond your procedure?

**Comment by mattodd** [comment]
Given that Chase resolved the original question, am closing this. Please reopen if you need more.
