### ISSUE TITLE
Statement of progress made so far on hetero oxadiazole synthesis

### ISSUE THREAD

**Issue by audreyjallen1** [OpenSourceMalaria/OSM_To_Do_List#446]
We have successfully completed steps 1-3 of the proposed Hetero oxadiazole synthesis (scheme attached), by replicating the procedure from Nikishkin et al 2013 (steps 1-2) and the subsequent AEW 85-5 step (step 3) in the synthesis of our hetero oxadiazole! We had a low yield on step 3, very low. It is possible that this is due to [a lab accident](http://malaria.ourexperiment.org/haverford_superlab_/14691/09292016_work_up_and_purification_of_4.html). Also, we had been afraid that the ester moiety in [3] could be a competing electrophile in this step, but HNMR and CNMR (attached) both show that the ester was intact in the reaction from [3] to [4]. We are very concerned about the low yield in this step, it will have to be replicated to determine if the low yield is only attributed to our lab accident, or if the low yield is a persistent problem 
![screen shot 2016-10-20 at 1 13 16 pm](https://cloud.githubusercontent.com/assets/21691873/19575281/c55e258e-96db-11e6-852f-79d1c6fb755a.png)
![screen shot 2016-10-20 at 3 10 29 pm](https://cloud.githubusercontent.com/assets/21691873/19575287/cf3bdd6c-96db-11e6-9dfb-6969d15fcf8c.png)
![screen shot 2016-10-20 at 3 10 36 pm](https://cloud.githubusercontent.com/assets/21691873/19575293/d60dd122-96db-11e6-9040-c42dd36248fc.png)
![screen shot 2016-09-29 at 10 30 09 pm](https://cloud.githubusercontent.com/assets/21691873/19575374/3bc18216-96dc-11e6-9644-27af6a6331a7.png)

[[4]big.pdf](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/542732/4.big.pdf)

**Comment by mattodd** [comment]
Wow, looks great - major progress. I see you're asking about that last NMR spectrum in #449 .

**Comment by mattodd** [comment]
Link installed in [DCNYS](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Desirable_Compounds_Not_Yet_Synthesised) section of wiki, and synthesis of this compound now taken on to #463.
Closing.
