### ISSUE TITLE
Problem with step 4 in hetero oxadiazole synthesis

### ISSUE THREAD

**Issue by audreyjallen1** [OpenSourceMalaria/OSM_To_Do_List#447]
Step 4 in our synthesis of the hetero oxadiazole (see scheme below) had a yield of zero, however there is some ambiguity of whether or not this step truly works. Due to our very small amount of staring material [4], 0.06g (.357 mmol), we had a very small scale reaction. In the course of our reaction, it appeared that a precipitate formed, as expected from AEW 204. When we tried vacuum filtration to isolate the precipitate, there was so little that it was not able to be isolated off of the filter paper. We tried washing the paper with DCM to extract the product and [GCMS was performed on the wash](http://malaria.ourexperiment.org/haverford_superlab_/14949/10072016_GC_mass_spec_characterization_of_rxn_from_45.html), however we show none of the expected product isolated. We believe that more work is needed to confirm whether this step works or not. We recommend starting with at least ten times the amount of [4] that we did, and perhaps not using vacuum filtration to capture the solid, though we are not sure what kind of technique would be best used for separation in this case
![screen shot 2016-10-20 at 1 13 16 pm](https://cloud.githubusercontent.com/assets/21691873/19575585/5e39c7f8-96dd-11e6-8b30-e263f8521f3e.png)

**Comment by mattodd** [comment]
OK, thanks for the status report, linking to #446 and #448. Have provided a link in the wiki. I will close this Issue now, though @alintheopen and @edwintse can still chip in on a closed issue, if they've any further advice for reactions of this type, with which they are very familiar.
@audreyjallen1 can you please install a link to this page on your ELN write-up, to ensure we capture the reasons for abandoning, plus any subsequent comments?
