### ISSUE TITLE
New direction for hetero oxadiazole synthesis

### ISSUE THREAD

**Issue by audreyjallen1** [OpenSourceMalaria/OSM_To_Do_List#448]
Now that we have run out of product to continue studying in the hetero oxadiazole synthesis, it is time to make more. We know that steps 1 and 2 are very time consuming, and while they produce excellent yields, we are curious about other methods to achieve product [4]. We found the paper Foks, H. Polish Journal of Pharmacology and Pharmacy 1974, 26 (5), 537–543, and decided to modify their procedure for going from III to IV+V to VI to VII. We will try to use hydrazine in place of methyl amine, and keep the rest of the procure the same. Shown below is our new alternative synthetic pathway. We tried to predict what products 2.2.1 and 2.2.2 would look like, but since our reagents are different from those in the article, we may have gotten those wrong. Any ideas on how 2.2.1 and 2.2.2 should look? 
We performed step 1.2, and our HNMR of the solid (shown below) indicated that there is most likely a mixture of two things. One possibility for this is that the precipitate is in fact two different products, one with an intact CN group and one that is 2.2.1. We are unsure about this however. Also, the HNMR shows impurities. Foks purified their sample of precipitate by recrystalization in water, we have not yet done that. We could also dry it under high vac to try and get rid of any possible solvent and clean up the HNMR. Even so, the HNMR shows 4 aromatic protons where there should only be 2, so there are likely equal molar quantities of two things. Any ideas on how to modify the [reaction conditions](http://malaria.ourexperiment.org/haverford_superlab_/14962/10616_Trial_Synthesis_of_6hydrazinelypyrazine2carbonitrile_and_from_6_hydrazinelypyrazine2carboximidhydrazide_from_chloropyrazinecarbonitrile.html)  to drive the reaction towards just the two predicted products, or on how to separate the two products evident in the solid? No characterization has yet been done on the liquid product, which we predict is 2.2.2.  
We believe this is an excellent alternative synthesis, because these first steps take a fraction of the time that the initial first steps took
![screen shot 2016-10-20 at 1 53 02 pm](https://cloud.githubusercontent.com/assets/21691873/19575917/e59d5a56-96de-11e6-9e6d-a614b020dfe7.png)
![screen shot 2016-10-20 at 4 12 00 pm](https://cloud.githubusercontent.com/assets/21691873/19576225/2af199cc-96e0-11e6-960a-198ce54448b7.png)

**Comment by mattodd** [comment]
OK, so you're looking for predicted NMR spectra of your structures above labelled 2.2.1 and 2.2.2? Could someone please oblige?

As for the outcome of the reaction, I'd strongly recommend purifying/separating, before we try to work out how to modify conditions. However, if you've used an excess of hydrazine, and if all your S/M has gone, you might want to reduce the amount of that reagent and/or the temperature. But this is advice in the absence of proof that that's the byproduct...
(could you provide a direct link to the paper you found, by editing your original post above? Just saves people a little time. Remember you can also link to here from your ELN post, to direct people to relevant discussions.)

**Comment by JohnATucker** [comment]
Sorry, I don't know the history of this, so maybe jumping in naively. But it seems like this could be simplified a bit by making the oxadiazole ring in the first step by adding a nitrile oxide to the nitrile?

**Comment by MFernflower** [comment]
I wonder how stable this whole molecule is going to be?

**Comment by mattodd** [comment]
Link installed in [DCNYS](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Desirable_Compounds_Not_Yet_Synthesised) section of wiki, and synthesis of this compound now taken on to #463.
Closing.
