### ISSUE TITLE
Strange HNMR

### ISSUE THREAD

**Issue by audreyjallen1** [OpenSourceMalaria/OSM_To_Do_List#449]
In our heterooxadiazole synthesis, one of our HNMR spectra showed 3 aromatic proton peaks where there should only be two. The spectrum is remarkably clean otherwise, but this is very curious. Does anyone have any idea why this could happen? Ever seen something like this happen? See Hd and Hc
![screen shot 2016-10-20 at 4 10 05 pm](https://cloud.githubusercontent.com/assets/21691873/19576098/bd7b62ce-96df-11e6-8826-cbcdf82ae52e.png)

**Comment by mattodd** [comment]
@edwintse and @alintheopen can comment on this better than me, but the NHNH2 should be giving you signals totalling 3? Isn't it just that? Is this one compound that you've purified, so the NMR spectrum is definitely of one thing, not two?

**Comment by audreyjallen1** [comment]
Ah, you are right, that points to another oddity. The two stout peaks at 8.64 and 8.46 are the NHNH2 peaks, indicated by a D2O proton exchange experiment we performed 
![screen shot 2016-10-20 at 8 49 40 pm](https://cloud.githubusercontent.com/assets/21691873/19582951/c646b6c0-9706-11e6-99bd-0315b300fea7.png)
You are right, we should have integration for 3 at those protons, and it looks like we only have integration for two. The peaks in question above do not disappear in this proton exchange experiment, indicating they are not NHNH2, but are in fact the aromatic

This is indeed the product after purification by [this process](http://malaria.ourexperiment.org/haverford_superlab_/14691/09292016_work_up_and_purification_of_4.html), and the fact that we get a expected integration for the methyl ester peak indicates that it is pure

**Comment by mattodd** [comment]
Interesting. Is it just my eyes/the integration, or is the peak with integral 0.87 now smaller, by a little? If no, then we need another structure. If yes, perhaps one proton is exchanging slower?
Any other data on this compounds now? Spectra of the S/M OK? (could you install a link to the relevant ELN entry, pls?)

**Comment by PatrickThomson** [comment]
Internal hydrogen bonding to the nitrogen of the pyridine might split the terminal NH2 of the hydrazine and smear the bridging one out into the baseline much further downfield, although (from memory) I don't think I saw that way back when I worked on series 4 myself. Do the chemical shifts compare to other 2-hydrazinopyrimidines from the project?

**Comment by mattodd** [comment]
Link installed in [DCNYS](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Desirable_Compounds_Not_Yet_Synthesised) section of wiki, and synthesis of this compound now taken on to #463.
Closing.
