### ISSUE TITLE
Confusing NMR results following reductive amination in "The Burns" synthesis

### ISSUE THREAD

**Issue by claudianguyen95** [OpenSourceMalaria/OSM_To_Do_List#450]
@evonkrusenstiern and I have been working on the synthesis of "The Burns" (#422), and have just completed [step 4 - a reductive amination](http://malaria.ourexperiment.org/the_burns/14906/Synthesis_of__Nbenzyl16chloropyrazin2yl222trifluoroethan1amine_EVKCN_14.html) to attempt to produce N-benzyl-1-(6-chloropyrazin-2-yl)-2,2,2-trifluoroethan-1-amine (SMILES: ClC1=CN=CC(C(NCC2=CC=CC=C2)C(F)(F)F)=N1). The rough draft of our step 4 has been posted (13C NMR not yet analyzed).  
![screen shot 2016-10-20 at 8 33 21 pm](https://cloud.githubusercontent.com/assets/21690279/19582680/9f082a96-9704-11e6-835e-42704b694885.png)

We achieved potentially promising results from TLC, although it does indicate an impurity, but we are having difficulty interpreting our 1H-NMR data. The data below is from analysis of our crude product. 

We performed TLC, which indicated complete consumption of the starting material, 1-(6-chloropyrazin-2-yl)-2,2,2-trifluoroethan-1-one (SMILES: ClC1=CN=CC(C(C(F)(F)F)=O)=N1) via UV visualization. 
![step 4 tlc](https://cloud.githubusercontent.com/assets/21690279/19582794/66d8d660-9705-11e6-8134-92105b63e4b8.JPG)
(1:1 EtOAc:Hexanes; silica gel plate; bottom = starting material, center = cospot, top = product)
Rf(SM) = 0.1, Rf(Prod) = 0.3
Although the UV visualizable spot in our product is indicative of an impurity, a ninhydrin stain indicated the presence of an amine in a second component of the product at the bottom of the plate. However, we are concerned that this may be due to residual benzylamine, the reagent used as the amine source. 
![step 4 tlc ninhydrin stain](https://cloud.githubusercontent.com/assets/21690279/19582834/c29407c2-9705-11e6-81f5-19aeccaa3cfd.JPG)

We are having difficulty interpreting our proton NMR (below) as there are many peaks that are likely indicative of the UV-visualizable impurity we saw in TLC. However, we are unsure if we produced any of the desired product. We would love any advice on analysis of our NMR, or insights on what impurities or undesired products we likely created. 
![product 4 4](https://cloud.githubusercontent.com/assets/21690279/19582966/e1bd317c-9706-11e6-80fe-6e6eeda7728e.jpeg)
![product 4 1](https://cloud.githubusercontent.com/assets/21690279/19582964/e1b747d0-9706-11e6-93a4-8f99a0ab5702.jpeg)
![product 4 2](https://cloud.githubusercontent.com/assets/21690279/19582965/e1b78362-9706-11e6-8b70-536e2e46e305.jpeg)
![product 4 3](https://cloud.githubusercontent.com/assets/21690279/19582963/e1b736aa-9706-11e6-99c2-641c1d76f9a5.jpeg)

**Comment by MedChemProf** [comment]
@claudianguyen95 My first thoughts is that there was no incorporation of the benzylamine into your product and what you might have isolated is largely the alcohol from reduction of the ketone. The aromatic peaks also do not have the appearance I normally would have expected for a phenyl ring. It actually looks like you have some para-substituted impurity. My favorite conditions for reductive aminations use sodium triacetoxyborohydride, acetic acid and dichloroethane.

**Comment by MFernflower** [comment]
@MedChemProf @claudianguyen95 If indeed you have produced the secondary alcohol - it should be easy to oxidize it back after purification using something like PCC

**Comment by mattodd** [comment]
Hi @claudianguyen95 I'd agree with @MedChemProf 's suggestion, though to be sure you'd definitely want to purify the compound (away from that baseline material) and find out how much you have of each. The conditions Chase mentioned sound good. I'll close this issue now, but please install a link to this page in the lab notebook for this experiment so we don't orphan this discussion.

**Comment by PatrickThomson** [comment]
Although this issue is closed, I should add some thoughts: Your heteroaromatic CF3 ketone might be a good enough electrophile to react with even cyanoborohydride on its own, so a two-step imine, reduce procedure might be necessary. I had a quick look in the literature and the first few hits on heteroaromatic trifluoroacetophenones were all two-step procedures even when using acetoxyborohydride; I'm inferring that those chemists ran into similar problems. 

I also tried to check conditions for the reduction of the CF3 ketone; even electron-rich non-heteroaromatics will go with borohydride in 2 hours at room temperature, so it's likely that the ketone is just too reactive for these conditions.

**Comment by BrettPogostin** [comment]
Hi @PatrickThomson. We are taking over this project and we should be reattempting this reaction soon. Would it be possible to send over those references you mentioned in your comment? Thank you so much for your input, and if you have any other advice please send it our way! 

> Although this issue is closed, I should add some thoughts: Your heteroaromatic CF3 ketone might be a good enough electrophile to react with even cyanoborohydride on its own, so a two-step imine, reduce procedure might be necessary. I had a quick look in the literature and the first few hits on heteroaromatic trifluoroacetophenones were all two-step procedures even when using acetoxyborohydride; I'm inferring that those chemists ran into similar problems. I also tried to check conditions for the reduction of the CF3 ketone; even electron-rich non-heteroaromatics will go with borohydride in 2 hours at room temperature, so it's likely that the ketone is just too reactive for these conditions.
