### ISSUE TITLE
Really confusing NMR for hERG evador: carboxylic acid proton coupled to a triplet???

### ISSUE THREAD

**Issue by RosalindXu** [OpenSourceMalaria/OSM_To_Do_List#451]
For the past three weeks, we have been trying to synthesize our target, the hERG evador, by adding tropic acid dianion, deprotonated by a strong base, to the triazopyrazine core by SNAr reaction:
![image](https://cloud.githubusercontent.com/assets/21690009/19623974/22459a68-98b0-11e6-8121-b0d4762ac7ac.png)

In four reactions in total, the bases we have tried are LDA and NaH. Both bases yield the same compound, but the identity of the compound really confuses us. Identification of the product will help us understand what really is going on and why this SNAr reaction is not yielding desired product, so that we can move forward. We would appreciate any help!

The compound appears to have no tropic acid moiety (6), so it is from (5) alone. It dissolves completely in water (vs THF) at pH 14 (brown color), and have a higher affinity to THF (vs water) at pH 1 (yellow color). At pH 1, it does not dissolve completely in anything but DMSO. The H1 NMR (pH 1-2) is:
![full](https://cloud.githubusercontent.com/assets/21690009/19624101/d9fd94d6-98b4-11e6-9ec4-36915893c77b.png)

Partial magnification of aromatic region:
![partial](https://cloud.githubusercontent.com/assets/21690009/19624096/cc296c68-98b4-11e6-8974-cca8ce73851a.png)

What really confuses us is that, the acidic proton here (~11.5 ppm) seems to be coupled to a triplet, and the triplet is then coupled to something else. COSY here:
For the acidic proton:
![acid](https://cloud.githubusercontent.com/assets/21690009/19624088/a93a4bb4-98b4-11e6-9c13-a6d1d91e13f2.png)

For the aromatic region:
![aromatic](https://cloud.githubusercontent.com/assets/21690009/19624099/d0f46bf8-98b4-11e6-8a56-704b8730f949.png)

We feel really thrown off by the fact that the acidic proton (~11.5 ppm) is coupled to a triplet (~11.5 ppm), and the triplet is also coupled to an unidentifiable peak in the cluster of 3 protons (the other two are probably those on the benzene ring). We would appreciate any help!

**Comment by mattodd** [comment]
Nice data, good question. First thought - based on some history of us seeing this compound - is it the compound where the Cl has been replaced by an OH? The triplet arising from the proton at position 1 (in your numbering above) that is coupling to the other Ar proton and the OH, where the coupling constants happen to be the same? Not the most convincing explanation, but perhaps the most likely byproduct. @alintheopen @edwintse I think we have NMR data for this compound from @JoannaUbels ? (Jo's experiments are [here](http://malaria.ourexperiment.org/triazolopyrazine_se/byuser/www.google.com-accounts-o8-id-id%3DAItOawljLJX_yLWuMeQi9bUMaw2vehEoQr_yW4Y), though I'm not sure we ever uploaded the thesis, e.g. to Figshare?).

Is this product the major product in call cases? Are you seeing generally good conversion of S/M? Do we think that this nucleophile is just not playing ball (through internal cyclisation @alintheopen ?)

**Comment by mattodd** [comment]
Some input/questions over on Twitter https://twitter.com/MartinStoermer/status/790069666072760321

**Comment by PatrickThomson** [comment]
I had a quick poke around in the literature to see if there were analagous systems we could compare NMR to, but with the exception of [one hydroxypyrazine ](http://pubs.acs.org.proxy.lib.strath.ac.uk/doi/abs/10.1021/jm00080a014) (compound 32, aromatic peaks at 7.72 and 8.08) there was nothing. I checked any potential "keto" form of the hydroxide to no avail

For routes to the proposed hydroxide, the most obvious is traces of moisture in the reaciton mixture, but I also looked for potential decarboxylative routes to the proposed hydroxide plus styrene, (nothing). What did have promise was an internal cyclisation to the 4-membered lactam with the "phenol" as a byproduct, something like: 

![image](https://cloud.githubusercontent.com/assets/4561884/19626037/e787e758-991f-11e6-8401-3ca58ef81e58.png)

There's [literature precedent ](http://www.sciencedirect.com/science/article/pii/S0957416605008335)for a mitsunobu-type reaction generating the lactam efficiently at -78.

I couldn't find any literature precedent for the use of tropic acid dianion as a nucleophile but there must be; it seems unlikely that nobody's come across this before.

**Comment by RosalindXu** [comment]
@PatrickThomson @mattodd Thanks! Internal cyclization could explain why tropic acid is not added to the triazolopyrazine ring. We generated a 1H NMR spectrum for the phenol: 
![screen shot 2016-10-23 at 12 21 58 pm](https://cloud.githubusercontent.com/assets/21690009/19627715/97a07a38-991b-11e6-998c-0bab581961d2.png)

The peak ~ 11.5 ppm appears to match, and the integration of protons is correct! I think this is what we have made. It did not occur to us that 1 H NMR shift of a phenol can be so downfield! 

Nevertheless, we do have doubts why this compound came out as the major product. We carefully dried all glassware in oven prior to reaction; precursor (5) was dried in high vacuum overnight, and (6) does not appear to be hydroscopic (we have 1N NMR of tropic acid with no water peak at all). The solvent was a new bottle of dry THF. Therefore, though it is not impossible that some moisture got inside, but certainly there was not a lot of water in the reaction. However, the phenol appears to be the _only_ product formed (and in rather large quantity), besides precursors (5) and tropic acid. 

Therefore, it occurs to us that the tropic acid nucleophile simply was not working, that it is even less competitive than the traces of water in the SNAr reaction. Internal cyclization---maybe followed by ring opening as I basidified and acidified that reaction in extraction, or maybe not---appears to me as the most possible explanation (we do see peaks matching tropic acid in other fractions of the product, but the lactam should have nearly the same 1H peaks as tropic acid). 

In this light, the logical thing to do is to follow the protocol of [AEW 266-2](http://malaria.ourexperiment.org/triazolopyrazine_se/13895/Synthesis_of_ethyl_3hydroxy2phenylpropanoateAEW_2662.html),[ AEW 281-1 ](http://malaria.ourexperiment.org/triazolopyrazine_se/14039/Synthesis_of_52phenyl2tetrahydro2Hpyran2yloxyethoxy3pyridin2yl124triazolo43apyrazine_AEW_2811.html), and [AEW 287-1](http://malaria.ourexperiment.org/triazolopyrazine_se/14054/Synthesis_of_2phenyl3tetrahydro2Hpyran2yloxypropan1ol_AEW_2871.html) to reduce it and attach the THP protection group first, then add it to the ring and deprotect, then oxidize the alcohol to form acidic function group. Since this is the last week of quarter, we have to hand these steps down to the group taking over our project. But we have some (5) to share with them, so there is a good chance of success!

**Comment by KimberleyRoper** [comment]
If you think that the acid moiety is the major problem then how about performing the esterification from AEW 266-2 and then trying your SNAr reaction? You could then saponify the ester back to the acid using KOH/Krapcho demethylation conditions if you had the methyl ester. You might have the same problem as above as you've have a similar intermediate (but you could maybe avoid this by decreasing the temperature of saponification?) - overall it would save you quite a few steps and can be run in parallel to your route suggested above.

**Comment by RosalindXu** [comment]
@KimberleyRoper Thanks for the suggestion! Indeed this method did occur to us early on, but we found [AEW 267-1](http://malaria.ourexperiment.org/triazolopyrazine_se/13896/Synthesis_of_ethyl_334difluoromethoxyphenyl124triazolo43apyrazin5yloxy2phenylpropanoate_AEW_2671.html), which is exactly the same step---esterification then SNAr. But unlike other reactions of the same type, this one had a really low yield, and we did not see a confirmative NMR of the product attached. At that time, we thought probably tropic acid were forming polymers---stringed together by hydroxyl and carboxylic groups, but with the input from above, it is also possible that an internal cyclization happened with the ester.

**Comment by mattodd** [comment]
Relevant byproduct being formed:
OC1=CN=CC2=NN=C(C3=CC=C(OC(F)F)C=C3)N21
InChI=1S/C12H8F2N4O2/c13-12(14)20-8-3-1-7(2-4-8)11-17-16-9-5-15-6-10(19)18(9)11/h1-6,12,19H
LKGFFHYSCHTNJQ-UHFFFAOYSA-N
Note added in [DCNYS](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Desirable_Compounds_Not_Yet_Synthesised) section of wiki. Closing this Issue, though discussion of this byproduct, and hopefully ways to minimise it, should be made in paper. For that, we'll need to make sure the byproduct is properly characterised @RosalindXu

**Comment by RosalindXu** [comment]
@mattodd: We have H1 NMR, H1 COSY and C13 NMR on this product.
