### ISSUE TITLE
Background question on the hERG evador

### ISSUE THREAD

**Issue by RosalindXu** [OpenSourceMalaria/OSM_To_Do_List#452]
Our taget compound is called the "hERG evador":
![image](https://cloud.githubusercontent.com/assets/21690009/19624120/c406cab6-98b5-11e6-96bb-baa5a0161284.png)
1. We are really curious about where this name came from: is it predicted to affect the functionality of the hERG channel, the potassium ion channel that affects heart beating? If so, how is this prediction made? From [this ](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series) reading, we learnt that hERG assay has been conducted on some of the compounds in triazolopyrazine series, but these compounds were cleared of negative effects. If our compound is predicted to affect hERG, which is undesired, what are the merits of it to be chosen as a target? 
2. In addition, we are curious about the hydrophilicity/hydrophobicity of our target: ChemBio Draw predicts its LogP to be 4.88: is that too high for it to be aqueous soluble?

Thank you!

**Comment by mattodd** [comment]
From [this interesting review](http://pubs.acs.org/doi/abs/10.1021/ci400308z) it seems carboxylic acid-containing drugs are rare but give excellent hERG profiles. This, combined with the generally-OK-but-mixed results from the hERG assay for Series 4 made a CO2H-containing analog an interesting one to try.
For logP, try Datawarrior. It's generally been found to be slightly more predictive of solubility (when vs actually measured values) than Chemdraw. Remember in the case of this compound it's likely it would exist as a zwitterion in polar solvents.

**Comment by MFernflower** [comment]
@mattodd Will the compound be made as the free acid or as the sodium salt?

**Comment by mattodd** [comment]
Whatever works and is easy to handle. Eventually, in the buffered environment of a bioassay, it won't much matter.

**Comment by drc007** [comment]
@RosalindXu Hi, you can read more about HERG on my website http://www.cambridgemedchemconsulting.com/resources/herg_activity.html

**Comment by RosalindXu** [comment]
Thanks! This is really helpful.

**Comment by mattodd** [comment]
Added to [DCNYS](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Desirable_Compounds_Not_Yet_Synthesised) section, so closing.
