### ISSUE TITLE
Background Questions about the "Hetero-Oxadiazole"

### ISSUE THREAD

**Issue by audreyjallen1** [OpenSourceMalaria/OSM_To_Do_List#453]
We think that oxadiazole moiety is being used as an isostere for triazole which was previously shown to be inactive, and that triazole was used as an isostere for amide to improve (lower) lipophilicity. Is our analysis here correct? Why was amide initially looked at?

Also, why does the hetero oxadiazole have no fluorines on the aromatic ring on the left side of the molecule? We think it could just be to improve synthesis ease, but is there something else?

Thanks so much - GitHub has been of tremendous use to us!

**Comment by mattodd** [comment]
The oxadiazole is being used as an isostere for an amide, sure - these compounds were a big part of the [original inherited dataset](http://malaria.ourexperiment.org/uri/404#) for the series.
Fluorines - we're pretty sure we understand that these help potency. But analogs with those Fs there are typically more expensive to make (just in terms of the S/M cost). So if we're making new compounds it's sometimes easier to target the non-F compounds, and then when we have established the chemical methodology we can always go back and make the fluorinated versions if the compounds show promise.

**Comment by mattodd** [comment]
Link installed in [DCNYS](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Desirable_Compounds_Not_Yet_Synthesised) section of wiki, and synthesis of this compound now taken on to #463.
Closing.
