### ISSUE TITLE
Background Information for the “The Alkyl”s 

### ISSUE THREAD

**Issue by OHaraJansonSchankler** [OpenSourceMalaria/OSM_To_Do_List#457]
Hello everyone,

We were hoping some of you could shed some light on the group of series-four molecules currently being synthesized by @OharaJansonSchankler, @aamilder, @aschankler, @anna-schrecengost, @sdilones:

![alkylfamily](https://cloud.githubusercontent.com/assets/21692047/19791285/9ffdc3dc-9c8d-11e6-84f4-59a2a176ca0f.png)

In the initial discussion in #403 it was suggested that the triple bond would serve as a site for functionalizing the side chain. It was also suggested that the cis bond on the alkene side chain might deactivate the molecule due to its geometry.

The MMV briefing document also said that when testing modifications to the NW side chain: “It soon became evident that changing the length of the side-chain to anything other than 3 atoms severely lowers potency”.  However, it was also decided that they should all be tested, despite their ClogP calculations indicating low hydrophilicity.

From what we have gathered, these molecules seem unlikely to be effective as drugs themselves, so besides providing a handle for further functionalization, what additional information will "The Alkyl"s provide?

**Comment by MFernflower** [comment]
Well, While I cannot answer the first two questions I can tell you that the fully reduced compound was made in CRO and tested and found to be pretty good (MMV669304)   @OHaraJansonSchankler

**Comment by OHaraJansonSchankler** [comment]
I believe that MMV669304 has 3 carbons on its NW side arm, which is consistent with the "3 atom" idea mentioned in the briefing document,  while the fully reduced alkyl being synthesized by @aamilder & co. has only 2 carbons on this side arm.

**Comment by mattodd** [comment]
Hi - just a clarification on terms here to make sure we're on the same page. The compounds above are alkyne, alkene and alkyl (or, if you like, alkane). Some general points on your good questions, @OHaraJansonSchankler :

1) OSM inherited some data and some analysis of the data, but not a complete set. Thus we have guidance but, in some cases, not evidence. Re-making compounds that may not be active is not therefore a terrible idea, if we can secure primary data that makes us more confident of those conclusions. Certainly looks like 3 atoms is needed, but most of the data we have on that involves O-containing linkers.

2) Making compounds that are suspected of being inactive is, in general, perfectly OK if this boosts the SAR model. 

3) The alkyne and alkene would indeed be useful for introducing other functionality, such as  internal triazoles (reacting the triple bond with an azide?), that would be a challenge using other approaches. One can envisage things like brominations and subsequent displacements quickly installing diverse functionality.

4) In cases like this we need not worry too much about the logP values if we are trying to create new methods that would, downstream, lead to new analogs that satisfy our logP criteria.

5) Those new methods could obviously be used to target compounds with different-length linkers, but I think the structures above represent the best initial targets.

**Comment by OHaraJansonSchankler** [comment]
Thank you for the information, this clears things up quite a bit. We will be posting an update soon about our progress (we believe we have successfully synthesized the alkyne, but we waiting until we obtain spectra).

**Comment by mattodd** [comment]
[This is your latest shot at this](http://malaria.ourexperiment.org/reduced_alkyl/15132/102116_Synthesis_of_34difluoromethoxyphenyl5phenylethynyl23dihydro124triazolo43apyrazine_rxn_42.html) @OHaraJansonSchankler ? Are you able to push it? More equivalents of acetylene or indium, more time in the microwave? That'd be the standard response to no apparent reaction, right? This is your crucial reaction - I'd guess the reductions will be easier than the alkynylation.
