### ISSUE TITLE
The "No Brainer"

### ISSUE THREAD

**Issue by MFernflower** [OpenSourceMalaria/OSM_To_Do_List#464]
As you may know @edwintse proved  that a methoxy group on the left hand phenyl ring would improve potency in the ether series (OSM-S-383 and OSM-S-384) I think it would be a wise step to produce an amide with a LH ring bearing only a 3 methoxy group..
![methoxyamide](https://cloud.githubusercontent.com/assets/3164942/20362735/990f47da-ac0a-11e6-9c22-8217760aa887.png)

**Comment by alintheopen** [comment]
Hi @MFernflower! Not so sure this is a 'no brainer' just yet :)
We still need to wait for potency data, and crucially tox data on a few. MeO is v useful to know about, but there's a chance it's toxic....

**Comment by MFernflower** [comment]
So the data that was posted by edwin was only just active/inactive? When will we get potency values and tox data?

**Comment by edwintse** [comment]
@MFernflower the data that I obtained was an assay about the suspected mechanism of action (PfATP4 Na+ inhibition). You can see info about this on the wiki page under Mechanism of Action. This is not a direct measure of potency but it's suspected that there is correlation. We have sent the compounds for potency evaluation and are currently awaiting the results. They'll be posted when we get the data back.

**Comment by MFernflower** [comment]
Thanks for explaining what that information that was posted onto twitter meant!!!

**Comment by MFernflower** [comment]
closing this untill we get the tox data back on the LH methoxy
