### ISSUE TITLE
Open Lab Notebook not accessible?

### ISSUE THREAD

**Issue by SamuelMarks** [OpenSourceMalaria/OSM_To_Do_List#465]
On http://opensourcemalaria.org there are a few links to: http://malaria.ourexperiment.org, but that site doesn't resolve. http://ourexperiment.org just gives:
![ourexperiment.org index](http://i.imgur.com/X0za5vs.png)

Has the Open Lab book now moved to Github, or is it located elsewhere?

**Comment by MFernflower** [comment]
Labtrove is back up
