### ISSUE TITLE
Finishing up "The Nemesis"

### ISSUE THREAD

**Issue by BrettPogostin** [OpenSourceMalaria/OSM_To_Do_List#466]
Victoria (@vribeiro3) and myself (Brett Pogostin) will be attempting the last step in the synthesis of "The Nemesis." The previous github issue can be found here ( #430 ). The origonal synthesis proposal can be found here ( #409 ) and the labnotebook can be found here: http://malaria.ourexperiment.org/hcnemesis16

![0fe4139a-9c9d-11e6-97e7-592edef8e16f](https://cloud.githubusercontent.com/assets/23084323/20457910/5f838812-ae64-11e6-99a7-3e88dcc3a0cc.PNG)

(Image taken from Marco and Lincon #430)
OC(C1=CC=CC=C1)COC2=CN=CC3=NN=C(C4CNCCC4)N32
InChI=1S/C18H21N5O2/c24-15(13-5-2-1-3-6-13)12-25-17-11-20-10-16-21-22-18(23(16)17)14-7-4-8-19-9-14/h1-3,5-6,10-11,14-15,19,24H,4,7-9,12H2
SNDLBGDEOQPBOQ-UHFFFAOYSA-N

**Comment by mattodd** [comment]
Looks great, @vribeiro3 @BrettPogostin - it [looks like you're really close,](http://malaria.ourexperiment.org/hcnemesis16/15338/Deprotection_of_tertbutyl_352phenyl2tetrahydro2Hpyran2yloxyethoxy124triazolo43apyrazin3ylpiperidine1carboxylate.html) too. How did the deprotection go? Fingers crossed!

**Comment by BrettPogostin** [comment]
@mattodd Sorry about that typo. We are going to look at the NMR data tomorrow. Also, our GC at Haverford is down, so it might take us some time to confidently say we made the final product. We will keep you posted.

**Comment by BrettPogostin** [comment]
![deprotect](https://cloud.githubusercontent.com/assets/23084323/20681416/83e46802-b571-11e6-8d0a-0fb006d203c9.jpg)


We just got the MS and NMR data back from the deprotection reaction. It appears that we were able to successfully deprotect some of sample and form the correct final product based on mass spec. The NMR and MS data, however, also suggests that some of the BOC protecting groups hung around after the reaction. We are using Ether-HCl to run the deprotection. Our plan is to run the deprotection reaction for longer ( ~ 2 hours) to hopefully give the reaction enough time to complete the deprotection.

**Comment by vribeiro3** [comment]
@mattodd Is there a way to reopen this issue? I notice the reopen and comment button here at the bottom, but I wanted to know if that is sufficient to reopen the whole issue.

**Comment by mattodd** [comment]
That'd be great, @BrettPogostin - fingers crossed and let us know how it goes. [This](http://malaria.ourexperiment.org/hcnemesis16/15338/Deprotection_of_tertbutyl_352phenyl2tetrahydro2Hpyran2yloxyethoxy124triazolo43apyrazin3ylpiperidine1carboxylate.html) is the reaction you did, right? Boc groups can fall off in electrospray MS, so be careful about conclusions derived from that analysis. But LCMS ought to give you the info you need. You'll be going from a very greasy compound to something that is very polar by way of something in between. A challenging reaction to follow.

**Comment by MFernflower** [comment]
@BrettPogostin @mattodd Would PTSA be a better acid for the deprotection?? Just wondering

**Comment by BrettPogostin** [comment]
Hi all,

We ended refluxing HCL dissolved in Dioxane to remove the Boc group. Mass Spec suggests that we were successful, but so far we have been unable to get a good NMR. Progress will be posted here: http://malaria.ourexperiment.org/hcnemesis16

As of now, it looks like the Nemesis has been successfully synthesized.

**Comment by MFernflower** [comment]
@BrettPogostin Congratulations! However I still wonder if for next time PTSA in anhydrous ethanol would have been a better option for deprotection?

**Comment by BrettPogostin** [comment]
We discussed using PTSA with @rbroadrup-HC , and he suggested that we use HCL-Dioxane. I think the reaction needed just a little boost, so I think just increasing the temperature to 102 degrees celsius was sufficient to push the deprotection to completion. In these conditions, the reaction went very quickly and we got a pretty good yield. Maybe future attempts at this deprotection could try to use PTSA, but as far as I can tell, this method worked pretty well.

**Comment by mattodd** [comment]
This is really excellent news. I'll wait for the NMR spectrum before
celebrating, in part so we can be sure of purity before the molecule is
biologically evaluated. Need that spectrum.

**Comment by mcoster** [comment]
Is this issue still open, or was the Nemesis successfully synthesised?

**Comment by AronSchwartzHC** [comment]
We believe that the Nemesis was successfully synthesized but there was not sufficient amount of product to be analyzed. We are redoing the synthesis right now. The following reaction was begun today.

![image](https://user-images.githubusercontent.com/22536346/27457753-df1f45b2-5773-11e7-9c26-796126ef6ba1.png)

We will make this protecting group tomorrow
![image](https://user-images.githubusercontent.com/22536346/27458023-f7894854-5774-11e7-9418-d654c3eb2d67.png)

**Comment by mattodd** [comment]
[Summary of syntheses in progress](http://www.openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_(TP)_Series#Desirable_Compounds_Not_Yet_Synthesised), including Nemesis. Still needed. It was @alintheopen 's nemesis, by the way. Ping @edwintse on the synthesis of that protected alcohol - I believe he nailed it.

**Comment by MFernflower** [comment]
IIRC the reaction was in two parts. THP protecing the free OH on ethyl mandelate and then reducing said protected compound with LiAlH4 @AronSchwartzHC

**Comment by david1597** [comment]
Closing issue. The Nemesis was successfully synthesised in [Apr 2018](https://github.com/OpenSourceMalaria/Series4/issues/38) and found to be [non-potent](https://github.com/OpenSourceMalaria/Series4/issues/39#issuecomment-393355163).
