### ISSUE TITLE
Predicting Sites of Metabolism

### ISSUE THREAD

**Issue by drc007** [OpenSourceMalaria/OSM_To_Do_List#471]
There is a recent publication http://jcheminf.springeropen.com/articles/10.1186/s13321-016-0183-x describing a new tool for predicting sites of metabolism. I thought I'd flag it since the service is accessible via a website, http://www.way2drug.com/RA/

Simply copy and paste the SMILES string from the Google doc (https://docs.google.com/spreadsheets/d/1Rvy6OiM291d1GN_cyT6eSw_C3lSuJ1jaR7AJa8hgGsc/edit#gid=510297618) or use the structure editor to draw novel molecules. Click on the reaction types (e.g. N-oxidation) to see the potential hot spots in the molecule. As with many of these tools I suspect there is a tendency to "over predict", so whilst sites are predicted to be potential sites of metabolism, in reality many will not be significant.

<img width="1013" alt="metabprediction" src="https://cloud.githubusercontent.com/assets/7080516/20746150/80f3d756-b6dc-11e6-9957-0acd40073524.png">

**Comment by MFernflower** [comment]
I'm going to have some fun with this!!

**Comment by MFernflower** [comment]
@drc007 @mattodd There is also a free service called xenosite 

swami.wustl.edu/xenosite

**Comment by mattodd** [comment]
Link installed in [wiki](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Physicochem.2Fmetabolism.2FPK) to prevent orphaning of this Issue.
