### ISSUE TITLE
Changing the work ethic and splitting it between biology work and chemistry work

### ISSUE THREAD

**Issue by rajasgodbole** [OpenSourceMalaria/OSM_To_Do_List#474]
Hi all !
firstly im eager to engage in the work and this awesome collaborative !. However i would like to suggest to distribute the work between biology and chemistry work as there is no clear management and excuse my language the work is spread into mess ! 
A clear line where new chemical leads are analysed for their ADMETX and Biologist pull out bigdata to target specific sites so as to reduce our work volume and make it fast and easy ! 
KUDOS !

**Comment by mattodd** [comment]
Hi @rajasgodbole - Thanks for writing, but I'm not clear what you're asking here. Please, anyone else chime in.

These Github issues are meant for specific things that can be addressed by people (and therefore resolved) and for people to post updates to work that they have done. I'd suggest the following:
1) If you'd like to get involved in what someone else is already doing then browse [existing issues](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues?q=is%3Aopen).
2) If you'd like to do something of your own, to which people can contribute, then set up a lab notebook [here](http://malaria.ourexperiment.org/?allblogs) or on Labarchives or any other site that is publicly available. You could for example make a molecule or perform an assay, or perform some in silico analysis on existing data, etc.
3) If you'd like to discuss things more in a very general way (i.e. unrelated to a single, resolvable issue), then please go ahead on another public site, for example (but not limited to) [here](https://plus.google.com/u/0/b/114702323662314783325/communities/105318249049322037798).
Closing this in the meantime.
