### ISSUE TITLE
Summary of the Kirk PfATP4 data obtained Nov 2016

### ISSUE THREAD

**Issue by edwintse** [OpenSourceMalaria/OSM_To_Do_List#477]
In early Nov 2016, the set of resynthesised Frontrunner compounds (#400) and a new set of Series 4 compounds (#420) were taken to the Kirk lab at the ANU to be tested in their PfATP4 assay. The compounds were tested in the assays measuring Na+ concentration (SBFI) and also pH (BCECF). Compounds were tested at either 1 μM, 5 μM or both concentrations.

Each part of the Triazolopyrazine compound (Left chain, Right chain, Pyridine, Triazole) corresponds to a different assay and is colour coded according to the level of activity. The text below each compound refers to the blood stage potency and is colour coded in the same way in order to easily see any correlation between the assays.

![syngene-kirk](https://cloud.githubusercontent.com/assets/18062981/23196342/1c4ee41c-f90d-11e6-9a14-66f7d88b0167.jpg)

----------------------------------------------------------------------------------------------------

Below is the image of the 3 outliers that don't show correlation between the assays. These compounds are either active in the SBFI assay but inactive _in vitro_ or inactive in the SBFI but active _in vitro_.

![untitled wiley-28](https://cloud.githubusercontent.com/assets/18062981/23242917/ba1ac9d2-f9cf-11e6-8783-ffb2608e771d.jpg)

Raw chemdraw file => [Syngene-Kirk.zip](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/792178/Syngene-Kirk.zip)

**Comment by mattodd** [comment]
Interesting visualisation, @edwintse . So the text below each structure relates to blood stage potency? This allows an easy correlation between assay and potency, and to ID any outsiders. But then does the above image need updating, given that we have such values for the structures on the left of the diagram?

**Comment by edwintse** [comment]
Yes @mattodd, the text colour relates to the blood stage potency. I'll update the image with the new data and legend.

**Comment by mattodd** [comment]
OK, great @edwintse . So this way of presenting the data rather quickly shows:

1) Most compounds' activity tracks well between potency-vs-parasite and activity in the Kirk assay. Green goes with green, red with red. This is what we expected.

2) BUT there are a few compounds where that correlation breaks down, where there might be interesting implications for the predictive model #421 i.e. those compounds where there is a mixture of red and green. Check out MMV670936 for example. Potent vs parasite but inactive in the assay?

**Comment by MedChemProf** [comment]
@edwintse @mattodd Sorry, but I could do with a more thorough explanation of the visualization. A little more discussion of the coding would help me out a lot.

**Comment by edwintse** [comment]
@MedChemProf Each of the 4 parts of the compound represent the results obtained from the two assays at different concentrations.
- Green indicates that the particular compound showed a clear increase in [Na+]/increase in pH at 1 or 5 μM. This indicates that the compound is targeting PfATP4.
- Orange indicates a moderate increase in [Na+] and pH.
- Red indicates no change in [Na+] and pH. This suggests the compound doesn't target PfATP4.

The colour of the text below the compounds indicates the _in vitro_ potency of the compound from the recent Dundee data set [here](http://malaria.ourexperiment.org/biological_data/15747/Biological_Data_from_Dundee__Frontrunner_Compounds.html) and [here](http://malaria.ourexperiment.org/biological_data/15741/Biological_Data_from_Dundee__November_2016_Compounds.html).
- Green indicates <1μM potency.
- Orange indicates >1μM to ~5μM potency.
- Red indicates ~10μM and above potency.

For the most part there is correlation between the Kirk assays and the level of _in vitro_ potency, but there are a couple of compounds where this is not the case.

Hope this helps.

**Comment by drc007** [comment]
Do we have a numerical value for activity at PfATP4? e.g. IC50?

**Comment by edwintse** [comment]
@drc007 Unfortunately not for this run. We only have values for [Na+] and pH which were run against the +ve and -ve controls (KAE609 and DMSO respectively).

**Comment by mattodd** [comment]
Thanks for all the clarification on this @edwintse . It's a good point @drc007 - we have to be careful about the lack of granularity here, in that the highlighted three compounds may just be sitting on a borderline we have defined in what is otherwise a broad spectrum of activity. If they are genuine outliers, then they may have significance for refining the predictive model. If there are no objections I might ask Kiaran, Adele and Adelaide if they could re-test these three compounds alongside our next batch, to verify the activities here.

**Comment by edwintse** [comment]
Image added to Wiki section [here](https://github.com/OpenSourceMalaria/Series4/wiki/Biological-Data-currently-not-incorporated-into-the-main-Wiki-sections).
