### ISSUE TITLE
My next set of compounds

### ISSUE THREAD

**Issue by edwintse** [OpenSourceMalaria/OSM_To_Do_List#481]
The next set of compounds that I'm working to synthesise are as follows:

- It was previously found that the mono-Me amine was inactive compared to the free amine and the di-Me amine.
![amines](https://cloud.githubusercontent.com/assets/18062981/22536493/3bca2728-e956-11e6-8e54-d76e00787859.jpg)
To further investigate any trends in this, the EtMe amine and the di-Et amine will be made.
![untitled wiley-9](https://cloud.githubusercontent.com/assets/18062981/22536703/eeea6da8-e957-11e6-8275-1cd124f0a0d7.jpg)

- To see how the solubility compares with the related OH compounds the ketone and the hydroxylamine will be made.
![untitled wiley-11](https://cloud.githubusercontent.com/assets/18062981/22536736/2cbe61d4-e958-11e6-81ea-7e88993acac7.jpg)

- For investigation into hERG related issues the carboxylic acid and the boronic acid will be made.
![untitled wiley-12](https://cloud.githubusercontent.com/assets/18062981/22536756/67247a84-e958-11e6-8711-15a0a8814b58.jpg)

- Replacement of the OCHF2 group with NO2 was suggested in issue #480 (this compound is lower on the to-do list at the moment)
![untitled wiley-13](https://cloud.githubusercontent.com/assets/18062981/22537003/d73eb274-e95a-11e6-96ca-a4e175ff75b1.jpg)

**Strings**

_**EtMe amine**_
FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC(N(C)CC)C4=CC(F)=C(F)C=C4)N32
InChI=1S/C23H21F4N5O2/c1-3-31(2)19(15-6-9-17(24)18(25)10-15)13-33-21-12-28-11-20-29-30-22(32(20)21)14-4-7-16(8-5-14)34-23(26)27/h4-12,19,23H,3,13H2,1-2H3
XPBTWBXREHLVRP-UHFFFAOYSA-N
_**di-Et amine**_
FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC(N(CC)CC)C4=CC(F)=C(F)C=C4)N32
InChI=1S/C24H23F4N5O2/c1-3-32(4-2)20(16-7-10-18(25)19(26)11-16)14-34-22-13-29-12-21-30-31-23(33(21)22)15-5-8-17(9-6-15)35-24(27)28/h5-13,20,24H,3-4,14H2,1-2H3
FFKUJTSUMDVIQH-UHFFFAOYSA-N
_**ketone**_
FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC(C4=CC(F)=C(F)C=C4)=O)N32
InChI=1S/C20H12F4N4O3/c21-14-6-3-12(7-15(14)22)16(29)10-30-18-9-25-8-17-26-27-19(28(17)18)11-1-4-13(5-2-11)31-20(23)24/h1-9,20H,10H2
OPCIMEMUOABUMK-UHFFFAOYSA-N
_**hydroxylamine**_
FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OC/C(C4=CC(F)=C(F)C=C4)=N/O)N32
InChI=1S/C20H13F4N5O3/c21-14-6-3-12(7-15(14)22)16(28-30)10-31-18-9-25-8-17-26-27-19(29(17)18)11-1-4-13(5-2-11)32-20(23)24/h1-9,20,30H,10H2/b28-16-
YQUNTGXTFALRIH-NTFVMDSBSA-N
_**carboxylic acid**_
FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC(C(O)=O)C4=CC(F)=C(F)C=C4)N32
InChI=1S/C21H14F4N4O4/c22-15-6-3-12(7-16(15)23)14(20(30)31)10-32-18-9-26-8-17-27-28-19(29(17)18)11-1-4-13(5-2-11)33-21(24)25/h1-9,14,21H,10H2,(H,30,31)
VTEIUQIAQALMDK-UHFFFAOYSA-N
_**boronic acid**_
FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC(B(O)O)C4=CC(F)=C(F)C=C4)N32
InChI=1S/C20H15BF4N4O4/c22-15-6-3-12(7-16(15)23)14(21(30)31)10-32-18-9-26-8-17-27-28-19(29(17)18)11-1-4-13(5-2-11)33-20(24)25/h1-9,14,20,30-31H,10H2
OFZNYZMZJNDDAG-UHFFFAOYSA-N
_**nitro**_
FC(C=C1)=C(F)C=C1CCOC2=CN=CC3=NN=C(C4=CC=C([N+]([O-])=O)C=C4)N32
InChI=1S/C19H13F2N5O3/c20-15-6-1-12(9-16(15)21)7-8-29-18-11-22-10-17-23-24-19(25(17)18)13-2-4-14(5-3-13)26(27)28/h1-6,9-11H,7-8H2
ANXKNNLWLQBISN-UHFFFAOYSA-N

**Comment by MFernflower** [comment]
Great stuff. Wondering if sulfonic acid might be good to add to acid series?

**Comment by edwintse** [comment]
@MFernflower I was just thinking about that yesterday :) It appears that there are some drugs out there that contain this group but our worry is that it'll be much too acidic so we'll hold off on this one.

**Comment by MFernflower** [comment]
Tetrazole perhaps? @edwintse

**Comment by MedChemProf** [comment]
@edwintse @mattodd I may have not not searched hard enough, but does the OSM have a site that will text new compounds for antimalarial activity for us? My contact at the Broad Institute is not contacting me back, so I do not have a location to has our new compounds tested. We have finally had some luck with some of our back-logged compounds. Update soon to follow. Thanks.

**Comment by MFernflower** [comment]
@edwintse to lower logp of the nitro idea - it might be better to couple
P-Fluorophenethyl alcohol instead of useing the di-f alcohol

**Comment by mattodd** [comment]
Hi @MedChemProf - sure we can ask MMV to include them in OSM's testing at Dundee. Hopefully OK. How many compounds are you thinking, and are you OK to Fedex them there?

**Comment by mattodd** [comment]
I've a general question about this issue of acidity. Perhaps the fear of the sulfonic acid being "too acidic" is misplaced, given that under any normal biologically-relevant conditions a drug containing such a group would be encountered as the neutral salt or a zwitterion. Is there another reason why we don't often see sulfonic acids (i.e. as anions/salts) in pharmaceuticals? Is it because of a tendency to form toxic byproducts either during synthesis or in vivo? Same question for boronic acids (e.g. [forming unwanted byproducts](https://www.ncbi.nlm.nih.gov/pubmed/23514361)) though there is more precedence there ([Bortezomib](https://en.wikipedia.org/wiki/Bortezomib)).

**Comment by MedChemProf** [comment]
Thank you @mattodd We will have two (2) compounds to be tested by the end of the week. They are the reversed amides that we have been struggling to make. We are planning two additional compounds for the sole purpose of being able to do a matched pair analysis with compounds already tested by the OSM. We will have the additional two in about a month. I have been swamped, but I plan on providing a detailed update to the group within the next week. I will also update the OSM compound tracker at the same time. I will continue to try and get through to the Broad in the interim. Finally, sending the compounds via FEDEX is not a problem. I will just need to figure out which customs forms are required for research samples.

**Comment by MFernflower** [comment]
@mattodd @edwintse perhaps the sodium salt of the sulfonic acid could be
made? Im scared boronic will give PAINS

**Comment by MFernflower** [comment]
@edwintse https://www.alfa.com/en/catalog/H35736/ Another possible replacement for OCF2?

**Comment by mattodd** [comment]
Yes @edwintse we should consider SF5, I think, as @MFernflower suggests. Someone will have a better memory than me on this but I saw this motif in a drug/drug candidate recently, and have seen it in many screening campaigns recently.

**Comment by MFernflower** [comment]
@mattodd I've also seen it in quite a few papers - it's said to be a good replacment for CF3/OCHF2 but only way to find out is to bite the bullet and try it - just like we did with the cubanes - I'd also be curious about TMS as a replacement for the 4-OCHF2 - LogP gets a bit heavy with some of these however so it's best to have the LHS side just be phenylethanol

**Comment by MFernflower** [comment]
@mattodd Did some price checking : 4-(Trimethylsilyl)benzaldehyde can be got for about 44 USD a gram and 4-SF5 benzaldehyde for less than 80 USD

**Comment by MFernflower** [comment]
@mattodd @edwintse I'm also curious about compounds that have been conformationally locked:
![riftihruihiuwee](https://cloud.githubusercontent.com/assets/3164942/23489558/36bc37dc-fec1-11e6-8620-bf868e3e116c.jpg)

**Comment by MFernflower** [comment]
@mattodd Has 2-Cyclohexylethanol been tried for LHS?

**Comment by MFernflower** [comment]
@edwintse I wonder if you can deprotect and oxidize EGT 197 in the same step... H2O2 and HCL in DCM perhaps?

**Comment by MFernflower** [comment]
@edwintse I ran a modification of my para nitro idea past Vito's prediction program and the output is promising
[screenshot at 2017-05-14 00 36 53](https://cloud.githubusercontent.com/assets/3164942/26031343/73e4cfce-383d-11e7-9acf-3484cfba9468.png)
!
