### ISSUE TITLE
Quick Q about simplest way to generate decent logP

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#495]
(Hi all - *lots* of issues here I'm late in dealing with (mainly the Competition), sorry, but a quick question just for today.

I need a recommendation for a logP calculator (from SMILES, InChI) that people can roll up to and use immediately with no pre-install. i.e. in a web browser.

Our Dean is going to be carrying out an hour-long science exercise with a group of school children overseas. @alintheopen and I were asked for an activity they could do. From the master list I've collated all the Series 4 compounds for which we have human microsome data (half life and CLint), which is 34 compounds. I thought the students could plot these data vs calculated logP to see whether our aiming for lower logP helps lower clearance rates (as we hope). This would add to the conversation we started way back in #333 .

So the students would take one of the strings (e.g. SMILES) and paste that into the logP calculator. They would take the number (after noticing the *magic that happened* when the string was converted to a chemical structure) and add it to the communal Google sheet and then our Dean would plot these vs. clearance data. In an hour the class would generate a plot together and see if there is a trend. We'd post the data.

So: what should the students use to calculate logP?

Our very own Cheminfo solution from @lpatiny would be able to calculate these numbers on the fly, obviously, but the current view does not contain MMV numbers (which we'd need for searching since not all the relevant compounds have OSM numbers) and I like the idea (in this case) that there is a little manual effort involved here. None of the students will have DataWarrior, or Chemdraw. Pubchem will not calculate values for molecules not in Pubchem already. Is there a best way of doing this?

**Comment by drc007** [comment]
Have a look at http://www.vcclab.org/

**Comment by mattodd** [comment]
Hi - yes I know about that site, but I just clicked on the link, in both Firefox and Chrome, and I'm looking at a blank page that fails to load. Result: unhappy Dean.

**Comment by lpatiny** [comment]
In 2h I will send you a link where you can draw a list of molecules or paste a list of SMILES and get predictions.

If you want to go further we should discuss (like calculating PCA, …)

If you have a SDF you can already make the calculations and filter the products on:

http://www.cheminfo.org/Chemistry/Parsing_data/SDF_explorer/index.html

In this view you can as well create a correlation between 2 parameters (as a scatter plot)

**Comment by mattodd** [comment]
I knew you'd have a solution! But yes the activity here ideally is that a student pastes a string, sees that this corresponds to a structure, and is able to obtain a predicted logP. For a school student this would in itself be quite interesting. It's a class of students, so doing these one at a time would be OK, since they could all work in parallel in one classroom on separate devices.

**Comment by lpatiny** [comment]
To use with google Chrome to be sure ...

Here is the view:
http://www.cheminfo.org/Chemistry/Parsing_data/Smiles_List_to_molecule_properties/index.html?viewURL=https%3A%2F%2Fcouch.cheminfo.org%2Fcheminfo-public%2Fd4e9182d85ed3902e66744093fd23528%2Fview.json%3Frev%3D15-bc3a1e9381f5c200567454cf62d2bd8a

You may also be interested in predicting properties on the fly using
http://www.cheminfo.org/Chemistry/Parsing_data/Smiles_List_to_molecule_properties/index.html?viewURL=https%3A%2F%2Fcouch.cheminfo.org%2Fcheminfo-public%2Fd9498d0a2ea400ea71efec8840a1273b%2Fview.json&loadversion=true&fillsearch=Property+explorer

**Comment by MedChemProf** [comment]
@mattodd It looks like you have a solution in hand, but these two sites provide LogP calculation as well as several other properties. Molinsiration: http://www.molinspiration.com/cgi-bin/properties and Mcule: https://mcule.com/apps/property-calculator/

**Comment by mattodd** [comment]
Thanks for this useful discussion. I'm struggling with how to close it.
i) Do we just close it and rely on search to find it again, should anyone be interested in how we, as a group, use logP?
ii) Do we try to index things like this in a useful place (In the back of my mind: Geocities being rendered obsolete by Google)
iii) If we indexed is the [Tech Ops page](http://www.openwetware.org/wiki/OpenSourceMalaria:Technical_Operations) something we should reconfigure/expand, to be a kid of FAQ for OSM medchem?

**Comment by mattodd** [comment]
Interim measure: link installed to this conversation on [wiki](http://www.openwetware.org/wiki/OpenSourceMalaria:Technical_Operations#Med_Chem_Relevant_Tech_Ops). Better solution needed in future to assemble best practice in community medchem tools. Closing for now. Thanks again for inputs.
