### ISSUE TITLE
ISTND3 Flyer

### ISSUE THREAD

**Issue by alintheopen** [OpenSourceMalaria/OSM_To_Do_List#496]
**Currently being edited**

Hello to visitors from The International Society for Neglected Tropical Diseases conference on Diagnostics, Drug Discovery & Development ([ISTND3](http://www.isntdd3.com/) for short), taking place in London on May 16th-17th 2017.

<a rel='nofollow' href='http://www.qrcode-generator.de' border='0' style='cursor:default'></a><img src='https://chart.googleapis.com/chart?cht=qr&chl=https%3A%2F%2Fgithub.com%2FOpenSourceMalaria%2FOSM_To_Do_List%2Fissues%2F496&chs=180x180&choe=UTF-8&chld=L|2' alt=''>
The QR code on your flyer (see attached) brought you here so that you can join OSM or find out what we're up to!

You're looking at one of the items on the **OSM To Do list**. To see the other open items, click on "Issues" above, and browse all the currently-open things that need work. To go to the landing page for OSM go [here](http://opensourcemalaria.org/) - there's a "join the team" tab there for ways to contact OSM. A good way to see what's going on is to follow the [Twitter](https://twitter.com/O_S_M) account. If you'd like to see the data associated with Series 4 (mentioned on your flyer) go to the [wiki page](http://www.openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_(TP)_Series) for that series, where you can find more data on the SAR and links to the primary lab notebooks.

[Here](http://pubs.acs.org/doi/full/10.1021/acscentsci.6b00086) is OSM's most recent paper. [Here](https://www.theguardian.com/science/2016/dec/01/australian-students-recreate-martin-shkreli-price-hike-drug-in-school-lab?CMP=twt_a-science_b-gdnscience)'s the story of OSM working with school students. [Here](http://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1002276)'s the bigger Open Source Pharma picture.

**Comment by mattodd** [comment]
To regular OSM'ers. The ISNTDD3 conference have graciously agreed to include an OSM flyer in the conference bag next week, allowing us a presence there. The current powerpoint version is attached to this comment, below. It's meant to be an A5 double sided piece of card that I was going to have printed [here](https://www.advantagemedia.co.uk/product/recycled-flyers/), and sent to the conference organisers before the meeting.

Any comments/suggestions on improving the flyer most welcome. I suggested the broad content, Alice made it look much better and suggested the QR code that would bring people right here.
Preview:
![flyer page 1](https://cloud.githubusercontent.com/assets/4386101/25884878/95058358-3598-11e7-852b-2ed258426052.png)
![flyer page 2](https://cloud.githubusercontent.com/assets/4386101/25884885/9aa69e5a-3598-11e7-87d7-445353085456.png)


[OSM ISNTDD3 Flyer v2.pptx](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/988788/OSM.ISNTDD3.Flyer.v2.pptx)

**Comment by mattodd** [comment]
Link to this Issue installed on [wiki](http://www.openwetware.org/wiki/OpenSourceMalaria:Links#Non-publication.2Fdata_Outputs). We can print flyers for any scientific meeting if we see this as helpful - the flyers could be distributed by anyone. Closing.
