### ISSUE TITLE
Swertiamarin evaluation?

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#497]
A new contributor to OSM, Hemant Bankhede, contacted me by email to offer a sample of a known compound, [swertiamarin](https://pubchem.ncbi.nlm.nih.gov/compound/Swertiamarin), for evaluation for blood stage potency. The compound is known to possess antimalarial activity (e.g. [here](http://thescipub.com/PDF/ajidsp.2009.259.262.pdf)), and is commercially available. Hemant’s fuller description of the compound is below, along with his contact info (by agreement with him). Hemant is willing to ship this compound to an OSM testing lab for evaluation, but I questioned why we would want to test this compound given that it is known to possess activity. Hemant said that the compound may have more potent activity (alone or in combination). I am skeptical of the need to evaluate this compound, but I am posting this here in case anyone would like to chime in one way or another, and to move the conversation off email in order to avoid violation of one of OSM's six laws.

“Swertiamarin is a glycoside which is reported in indian herb Enicostemma Littorate at 7.7 % [1]. In vitro antiplasmodial activity of Swertiamarin was established and study reported IC50 was observed at 12 μg/mL [2]. recently antimalarial effect of swertiamarin was studied where In vitro study on plasmodium falciparum and in vivo study using Swiss albino mice infected with Plasmodium berghei. reported IC 50 of 8.17 ± 0.17 μg/mL and chemosuppressant effects in a dose-dependent manner at 200–280 mg/kg/day [3]. Mechanism of antiplasmodial activity was established using in silico docking study where swertiamarin was binding to Plasmodium Lactate Dehydrogenase [4].

Above literature reported antimalarial activity of swertiamarin, if evaluated further in combination with other new or traditional antimalarial activity synergistic effect may be established, hence it is necessary to evaluate antiplasmodial activity.”

Reference

1. Vishwakarma, S.L et al A rapid method for the isolation of swertiamarin from Enicostemma littorale. Pharm. Biol., 2004; 42: 400-403
2. Soni Sanket, In vitro Anti Plasmodial Activity of Enicostemma littorale. Am. J. Infect. Dis., 2009; 5 (3): 259-262
3. Divya Shitlani et al Ameliorative antimalarial effects of the combination of rutin and swertiamarin on malarial parasites. Asian Pac J Trop Dis 2016; 6(6): 453-459
4. Panchal Hetal K. et al Docking Studies of Components of Tulsi and Mamejavo against Plasmodium Lactate Dehydrogenase Int. Res. J. Biological Sci., 2013; 2 (2): 8-12

Hemant Kumar Bankhede
Independent researcher
Goa, India
Mobile +91-9271280985
Email hemant_16aug@yahoo.co.in

HEYZWPRKKUGDCR-QBXMEVCASA-N
C=CC1C(OC=C2C1(CCOC2=O)O)OC3C(C(C(C(O3)CO)O)O)O

**Comment by hemant16aug** [comment]
Experts comments are welcome

**Comment by MFernflower** [comment]
@mattodd I do not like the way this compound looks! I suspect it to be shredded by CYP enzymes extremely quickly. I also fail to see why this compound needs to be tested further as it has been found to be active. I thank you for the offer @hemant16aug  but there does not seem to be any reason to test the compound any further!

**Comment by MFernflower** [comment]
Attached is the output of toxtree: 
![toxtreescreen](https://cloud.githubusercontent.com/assets/3164942/25934379/79923ad2-35eb-11e7-9663-aa9ef95aa664.png)


(note: I changed the OH to a CH3)

**Comment by hemant16aug** [comment]
What could we interpret from toxfree

**Comment by hemant16aug** [comment]
Toxtree

**Comment by hemant16aug** [comment]
Does it mean Swertiamarin is a  class III substance.... Having significant toxicity...so we can not use as drug for oral adminstration.please comment.

**Comment by mattodd** [comment]
I don't know, but again I think the point really is that swertiamarin has been quite well studied already, and perhaps the literature is the best place to go at this stage vs any evaluations that might be duplicative, e.g. 10.1002/bmc.3099 and 10.1016/j.jchromb.2011.04.003 and https://pubchem.ncbi.nlm.nih.gov/compound/Swertiamarin#section=BioAssay-Results

**Comment by MFernflower** [comment]
Not only that @mattodd - This compound is more than likely a PAINS (as per toxtree)

**Comment by MFernflower** [comment]
@hemant16aug Relevant reading on how PAINS work: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4360378/

**Comment by hemant16aug** [comment]
Thanks..any other way we could asses efficacy as antimalarial for this molecule

**Comment by MFernflower** [comment]
@hemant16aug Seems like this glycoside is a dead end. Thanks for the offer however

**Comment by hemant16aug** [comment]
Thanks for comments @MFernFlower.

**Comment by mattodd** [comment]
Closing this issue. This page is still discoverable, and contains the cheminfo strings to make it googleable should anyone search for this molecule. There's also [a page for suggested targets/series that have not yet been acted upon](http://www.openwetware.org/wiki/OpenSourceMalaria:Other_Possible_Series_and_Targets), should anyone wish to install this there.

**Comment by MFernflower** [comment]
Did you see the phenothazine s oxide singleton i posted? @mattodd -
depending on time ofcourse do you think a school would be able to make it?
Just a thought
