### ISSUE TITLE
Potency data for Series 3 

### ISSUE THREAD

**Issue by spadavec** [OpenSourceMalaria/OSM_To_Do_List#501]
I'm in the middle of a in silico target prediction exercise for Series 3, but I can't seem to find much potency data for them. As far as I can tell, the only place with S3 data is the [master spreadsheet](https://docs.google.com/spreadsheets/d/1Rvy6OiM291d1GN_cyT6eSw_C3lSuJ1jaR7AJa8hgGsc/edit#gid=510297618) which has ~5 datapoints in total for IC50. Do we have any other data for this series I could use?

**Comment by mattodd** [comment]
Yes! The series ossified, but a *new student* has started on this series very recently, so this is a good time for her to go open, since she's just gotten started in the lab. I'll let her respond to this, and to update you on how she's going to add all the Series 3 potency data into the Master List. A prediction exercise for this series would be fantastic, since the MoA is still unknown, despite the initial hit being so promising.

**Comment by MFernflower** [comment]
@mattodd Dont know how helpful this is gonna be but I fed the hit into the swiss program suite and got some interesting results! 
![targetpredictionreport](https://cloud.githubusercontent.com/assets/3164942/26369310/4b480842-3fc2-11e7-893d-48e8b03cd818.jpg)

Looks like the hit is predicted to smack a ton of kinases!

**Comment by mbhebhe** [comment]
@spadavec Hello! I am Mat's new student. Attached are the compiled potency values for the Series 3 compounds. I will update the masterlist some time next week. In the mean time, have a look at this one.

[Series 3 biological tests.docx](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/1028581/Series.3.biological.tests.docx)

**Comment by spadavec** [comment]
@mbhebhe Thank you so much! This should really help out in my work--much appreciated.

**Comment by mbhebhe** [comment]
@spadavec I have updated the Masterlist with the information that I could find. If I find some more, I will let you know

**Comment by mattodd** [comment]
I think this issue has served its purpose, so am closing. @mbhebhe - install any future bioactivity data on Master List. Have installed a link to this Issue on [a section of the wiki](http://www.openwetware.org/wiki/OpenSourceMalaria:GSK_Amino-thienopyrimidine_Series#Mechanism_of_Action) to ensure no orphaning, though wiki is currently out of date.
