### ISSUE TITLE
Benzylic amine compounds update

### ISSUE THREAD

**Issue by edwintse** [OpenSourceMalaria/OSM_To_Do_List#504]
The trend that has been seen with previous benzylic amine compounds (inherited or synthesised) is as follows: primary and tertiary amines are active, secondary amine was inactive

![untitled wiley document-5](https://user-images.githubusercontent.com/18062981/27160157-77da5ad6-51b5-11e7-857a-6587ef8948ad.jpg)

Following on from my previous post on my next set of compounds (#481), a number of these compounds will now be synthesised. Scale up of the key benzylic ketone compound has been done and a number of reductive aminations can be done for diversification.

n.b. the LHS phenyl ring will be used instead of the 3,4-difluorophenyl ring due to ease of access.

![amines](https://user-images.githubusercontent.com/18062981/27159711-7dbc8d96-51b2-11e7-8cff-458fd1d1deac.jpg)

Before further diversification, these compounds will be evaluated first, but if there are any suggestions for other compounds that can be obtained from this ketone, suggest away.

[chemdraw.zip](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/1076264/chemdraw.zip)

**Comment by mattodd** [comment]
I'm speaking at [this conference at Tres Cantos next week](https://www.soci.org/Events/Display-Event?EventCode=FCHEM164), about OSM and all other things open. I'll include this as an example of a "live" question. 

My votes are, in order: 1) hydroxylamine, 2) morpholine, 3) NMeEt.

**Comment by MFernflower** [comment]
@edwintse @mattodd Do you guys have this molecule on hand???? 
![thi](https://user-images.githubusercontent.com/3164942/27192679-3ad32432-51ca-11e7-9f9c-f2bc73cbc096.png)

**Comment by MFernflower** [comment]
Do you guys have this molecule on hand???? Might be fun to try....
![thi](https://user-images.githubusercontent.com/3164942/27192679-3ad32432-51ca-11e7-9f9c-f2bc73cbc096.png)


azetidine and pyrrolidine might also be worth trying

@edwintse

**Comment by MFernflower** [comment]
@edwintse @mattodd Sorry for having to repost but here are a few ideas I came up with:

![benzamine_mods](https://user-images.githubusercontent.com/3164942/27249418-3b48193a-52e3-11e7-8410-0a1d236b661f.png)

**Comment by spadavec** [comment]
Using MMP/Regression approach, I developed 47 different ideas for new compounds which can be found [here](https://docs.google.com/spreadsheets/d/195wDEbA0lClS5oYvI1zJA5pdk2U18oeN40JatAK35xE/edit#gid=0), and the workbook found [here](http://malaria.ourexperiment.org/in_silico_pfatp4_mo/15912/Benzylic_amine_compounds.html) (which is essentially a carbon copy of my previous implementation). 

For the sake of brevity, here are the top 10 most (predicted) potent compounds--some rather silly, but others perhaps not so much






![benz_amine](https://user-images.githubusercontent.com/3453650/27250163-c667c1f8-52db-11e7-8b9a-b97b8cc5d3e8.png)

**Comment by MFernflower** [comment]
@spadavec My votes for synthesis out of that batch is as follows:

END-D074AC
END-BB326D
END-C22BEE

**Comment by mattodd** [comment]
Hi @spadavec - just to clarify. All your suggestions have the oxygen in the side chain transposed. @edwintse 's core has the oxygen directly linked to the triazolopyrazine core? If that's a copy/paste error, could you re-predict on Ed's core? Would be v useful.

**Comment by spadavec** [comment]
@mattodd wow, you're completely right. I initially copied the wrong smiles string and ran this analysis with the wrong seed; I can't believe I didn't catch that! 

Updated predictions found [here](https://docs.google.com/spreadsheets/d/195wDEbA0lClS5oYvI1zJA5pdk2U18oeN40JatAK35xE/edit#gid=789675559), with top 15 shown here (very little change from before): 

![ether](https://user-images.githubusercontent.com/3453650/27296396-8968b8ec-54d5-11e7-8c5b-8bd71e8b0467.png)

Again, a few silly ones, but the trend seems to be for preferring tetrazoles and triazoles substitutions.

**Comment by mattodd** [comment]
Nice @spadavec . In an _ideal world_, we'd not introduce another aromatic ring. Are there any simple analogs that involve e.g. similar ring types, but saturated, e.g. pyrrolidine etc?
@edwintse what do you reckon to the above. Accessible?

**Comment by spadavec** [comment]
@mattodd sadly, all of the substitutions it suggested are aromatic ring derivatives. I'm currently constructing a new tool that does simple organic chemistry rules based enumeration and might be able to have that ready in the next day or two.

**Comment by MFernflower** [comment]
@spadavec would you be able to screen the proposed compounds I posted? I am
away from my linux box at the moment!

On Jun 19, 2017 1:13 PM, "Vito Spadavecchio" <notifications@github.com>
wrote:

@mattodd <https://github.com/mattodd> sadly, all of the substitutions it
suggested are aromatic ring derivatives. I'm currently constructing a new
tool that does simple organic chemistry rules based enumeration and might
be able to have that ready in the next day or two.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/504#issuecomment-309505921>,
or mute the thread

**Comment by holeung** [comment]
I ran @spadavec's molecules through my 3D-QSAR model. Top rated were F3221C, A26A0A, C52B4B, F961EC, B3D09B. I suggest dropping F3221C because it would be deprotonated at physiological pH.

[benzylic_amines_top5.sdf.zip](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/1087732/benzylic_amines_top5.sdf.zip)

**Comment by MFernflower** [comment]
if possible could you run my proposed compounds past your 3d qsar?

**Comment by spadavec** [comment]
@MFernflower I was able to run your ideas, and they are roughly equipotent with each other and the lead compound: 

| Substitution | SMILES | cLogP | EC50 | 
| ----- | ----- | ----- | ------|
|Pyrrole |  FC(F)OC1=CC=C(C=C1)C1=NN=C2C=NC=C(OCC(N3C=CC=C3)C3=CC=CC=C3)N12 | 4.8626 | 0.52 | 
|pyrrolidine| FC(F)OC1=CC=C(C=C1)C1=NN=C2C=NC=C(OCC(N3CCCC3)C3=CC=CC=C3)N12 | 4.6086| 0.61|
|azetidine| FC(F)OC1=CC=C(C=C1)C1=NN=C2C=NC=C(OCC(N3CCC3)C3=CC=CC=C3)N12| 4.2185| 0.63|
|thianedione| FC(F)OC1=CC=C(C=C1)C1=NN=C2C=NC=C(OCC(N3CCS(=O)(=O)CC3)C3=CC=CC=C3)N12| 3.243 |0.70 |

**Comment by mattodd** [comment]
Good stuff. I'm still greatly preferring the non-aromatic analogs like the pyrrolidine/azetidine. Any further insight/predictions in that direction would be very useful. @edwintse will also love you if it's single-step from ketone. I'm thinking NEt2 vs pyrrolidine would be obviously nice.

**Comment by holeung** [comment]
@mattodd: I looked into non-aromatic analogs of @spadavec's molecules, but they scored much lower in my models.

**Comment by MFernflower** [comment]
Some more ideas I came up with: (sorry about having to post the raw CSV - MarvinSketch was not cooperating today!) 


[regression-predictions.csv.txt](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/1106984/regression-predictions.csv.txt)

**Comment by edwintse** [comment]
Three benzylic amines from the original post were synthesised and sent for biological testing. Relevant post [here](https://github.com/OpenSourceMalaria/Series4/issues/8).
