### ISSUE TITLE
Novel replacements for para OCHF2?

### ISSUE THREAD

**Issue by MFernflower** [OpenSourceMalaria/OSM_To_Do_List#516]
As some of you may know @edwintse has produced a compound where the normal para-OCHF2 group has been swapped for a para-SF5 group - I do believe there are some plans in place to replace the difluoromethoxyphenyl with cages like adamantane, cubane etc. I have came up with a few novel replacements for the para OCHF2 on the phenyl ring and I am wondering how synthetically possible some of these ideas are that and if some have already been made and tested:

@drc007 Do you know of any good mimics for the cyano functional group? nitro is the only thing that comes to mind for me sadly. 

![28182505-634b5602-67da-11e7-80f8-90951d12e3c7](https://user-images.githubusercontent.com/3164942/28197948-49679266-6828-11e7-9ffa-78c0c57f3e1c.png)

I apologize for the slightly bad image quality - hopefully everything is readable!!!!!

Update: Aug 1 2017: I understand that several of the compounds in that graphic would be highly unstable and thus the only groups I propose as replacements for OCHF2 are as follows: NO2, TMS, SeF5 and monoethylcarbonate

**Comment by drc007** [comment]
Methyl sulphone perhaps? N-linked 1,2,3- triazole?

**Comment by MFernflower** [comment]
@drc007 Mr.Swain could you draw out some of your proposals to my question when you have some free time and post them here along with respective smiles strings? provided you have some free time that is

**Comment by drc007** [comment]
here you go

C[C@@H](COC1=CN=CC2=NN=C(N12)C1=CC=C(C=C1)S(C)(=O)=O)C1=CC=CC=C1.C[C@@H](COC1=CN=CC2=NN=C(N12)C1=CC=C(C=C1)N1C=CN=N1)C1=CC=CC=C1

![chemlink 144216376](https://user-images.githubusercontent.com/7080516/28245442-a0eb4208-69fe-11e7-8b81-e11f54f49218.png)

**Comment by MFernflower** [comment]
@drc007 I ran the proposed compounds through @spadavec 's program and got the following: 
![output2](https://user-images.githubusercontent.com/3164942/28252804-dc95a59a-6a68-11e7-8e86-a5f37fe4958d.jpg)

regaruding the accuracy of the model - only time will tell

**Comment by spadavec** [comment]
Note that the accuracy of the model is supposedly allowing for ~7x fold changes in potency, so all of the above compounds are basically equivalent in potency.

**Comment by MFernflower** [comment]
@spadavec Thanks for noting that! some of the compounds you tested with your model have been sent to dundee for testing!

**Comment by MFernflower** [comment]
@spadavec In your personal opinion: do you think it is worth for the team at USyd to make the TMS and Tbutoxy compounds respectively?

**Comment by spadavec** [comment]
@MFernflower Given the total lack of data for either substitution in our data (theres are no TMS compounds, and the only t-butyl compound has it on the ether side), I'd say (in my opinion, of course) thats not really worth making them unless testing a specific hypothesis. I know im preaching to the choir, but having an xtal structure here would help _immensely_ :)

**Comment by MFernflower** [comment]
@spadavec Those compounds are quite similar to the para SF5 compound @edwintse made and sent off for testing - I do think we should wait for the test results on the SF5 compound before making any of those however

**Comment by MFernflower** [comment]
@drc007 I saw a very interesting ring system in one of the enamine catalogues: 

![cloudkicker](https://user-images.githubusercontent.com/3164942/29046366-3a93e93a-7b95-11e7-9dba-2c330ac6fb08.jpg)

**Comment by MFernflower** [comment]
closing this issue and reopening a new issue with yet untested ochf2 replacements
