### ISSUE TITLE
Next batch of samples sent for biological evaulation

### ISSUE THREAD

**Issue by edwintse** [OpenSourceMalaria/OSM_To_Do_List#517]
The next batch of compounds from this years work so far (shown below) have now been shipped to Dundee for screening against _P. falciparum_.

**THE RELEVANT POTENCY DATA HAS BEEN RECEIVED AND IS POSTED** [**HERE**](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/NzEyLjR8MTUwOS81NDgvVHJlZU5vZGUvMzU4OTEzMDg4N3wxODA4LjM5OTk5OTk5OTk5OTk=
)
--------------------------------------------------------------------------------------------------
- My new compounds: Things that I've been working on so far (#481, #504, #510)
- Resolved compounds: Key racemic frontrunner compound that was resolved into its two enaniomers by Mark Butler and his team at the University of Queensland (#470)
- SSP 2017 compounds: Compounds synthesised in the 1st year undergraduate Special Studies Program at the University of Sydney (#510, #514)
- Late stage functionalisation compounds: Key precursor compounds to be used for late stage functionalisation as part of @ConorGraham's honours project at the University of Sydney
- Resynthesised Series 3 compound: Key Series 3 compound resynthesised as part of @mbhebhe's PhD project at the University of Sydney (#501)

![dundee compounds 140717](https://user-images.githubusercontent.com/18062981/28208152-bb2f9c3e-68cf-11e7-9073-aceb0ce74281.jpg)
--------------------------------------------------------------------------------------------------
MMV Number | SMILES | InChI | InChI Key
-- | -- | -- | --
MMV1557931 | IC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCCC4=CC(F)=C(F)C=C4)N32 | InChI=1S/C19H13F2IN4O/c20-15-6-1-12(9-16(15)21)7-8-27-18-11-23-10-17-24-25-19(26(17)18)13-2-4-14(22)5-3-13/h1-6,9-11H,7-8H2 | SYOXDOQMLHMQGB-UHFFFAOYSA-N
MMV1557932 | FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC(C4=CC(F)=C(F)C=C4)=O)N32 | InChI=1S/C20H12F4N4O3/c21-14-6-3-12(7-15(14)22)16(29)10-30-18-9-25-8-17-26-27-19(28(17)18)11-1-4-13(5-2-11)31-20(23)24/h1-9,20H,10H2 | OPCIMEMUOABUMK-UHFFFAOYSA-N
MMV1557933 | FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC(OC)(OC)C4=CC(F)=C(F)C=C4)N32 | InChI=1S/C22H18F4N4O4/c1-31-22(32-2,14-5-8-16(23)17(24)9-14)12-33-19-11-27-10-18-28-29-20(30(18)19)13-3-6-15(7-4-13)34-21(25)26/h3-11,21H,12H2,1-2H3 | HFRRKTROCJVLKP-UHFFFAOYSA-N
MMV1557934 | FS(F)(F)(F)(F)C(C=C1)=CC=C1C2=NN=C3C=NC=C(OCCC4=CC=CC=C4)N32 | InChI=1S/C19H15F5N4OS/c20-30(21,22,23,24)16-8-6-15(7-9-16)19-27-26-17-12-25-13-18(28(17)19)29-11-10-14-4-2-1-3-5-14/h1-9,12-13H,10-11H2 | PEMORNCGKKXBCP-UHFFFAOYSA-N
MMV1557935 | FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCCC4(CC5C6)CC6C[C@@H](C5)C4)N32 | InChI=1S/C24H26F2N4O2/c25-23(26)32-19-3-1-18(2-4-19)22-29-28-20-13-27-14-21(30(20)22)31-6-5-24-10-15-7-16(11-24)9-17(8-15)12-24/h1-4,13-17,23H,5-12H2/t15-,16?,17?,24? | BSXLJNOXQMXUOB-CRFYJIHUSA-N
MMV1557936 | FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OC(C)CC4=CC=CC=C4)N32 | InChI=1S/C21H18F2N4O2/c1-14(11-15-5-3-2-4-6-15)28-19-13-24-12-18-25-26-20(27(18)19)16-7-9-17(10-8-16)29-21(22)23/h2-10,12-14,21H,11H2,1H3 | HJOHTEUEFDSADX-UHFFFAOYSA-N
MMV1557937 | FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC45C[C@@H](C[C@@H](C5)C6)C[C@@H]6C4)N32 | InChI=1S/C23H24F2N4O2/c24-22(25)31-18-3-1-17(2-4-18)21-28-27-19-11-26-12-20(29(19)21)30-13-23-8-14-5-15(9-23)7-16(6-14)10-23/h1-4,11-12,14-16,22H,5-10,13H2/t14-,15+,16-,23? | PIOOGPDPQVQAFQ-QUXYOMGYSA-N
MMV1557938 | FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC4C[C@H]5C=C[C@@H]4C5)N32 | InChI=1S/C20H18F2N4O2/c21-20(22)28-16-5-3-13(4-6-16)19-25-24-17-9-23-10-18(26(17)19)27-11-15-8-12-1-2-14(15)7-12/h1-6,9-10,12,14-15,20H,7-8,11H2/t12-,14+,15?/m0/s1 | OMOCZBKUEFTIAC-DJIKBVBFSA-N
MMV1557939 | CC1(C)[C@@H]2C[C@H]1C(CCOC3=CN=CC4=NN=C(C5=CC=C(OC(F)F)C=C5)N43)=CC2 | InChI=1S/C23H24F2N4O2/c1-23(2)16-6-3-14(18(23)11-16)9-10-30-20-13-26-12-19-27-28-21(29(19)20)15-4-7-17(8-5-15)31-22(24)25/h3-5,7-8,12-13,16,18,22H,6,9-11H2,1-2H3/t16-,18-/m0/s1 | PQILDBPUDLGKJU-WMZOPIPTSA-N
MMV1557940 | FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC(C4=CC=CC=C4)=O)N32 | InChI=1S/C20H14F2N4O3/c21-20(22)29-15-8-6-14(7-9-15)19-25-24-17-10-23-11-18(26(17)19)28-12-16(27)13-4-2-1-3-5-13/h1-11,20H,12H2 | MQSMCJANEPVRGE-UHFFFAOYSA-N
MMV1557941 | ClC(C=C1)=CC(Cl)=C1C2=NN=C3C=NC=C(OCC45C[C@@H](C[C@@H](C5)C6)C[C@@H]6C4)N32 | InChI=1S/C22H22Cl2N4O/c23-16-1-2-17(18(24)6-16)21-27-26-19-10-25-11-20(28(19)21)29-12-22-7-13-3-14(8-22)5-15(4-13)9-22/h1-2,6,10-11,13-15H,3-5,7-9,12H2/t13-,14+,15-,22? | XRHQAPBKYTXPOW-HBJUSLLUSA-N
MMV1557942 | ClC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC45C[C@@H](C[C@@H](C5)C6)C[C@@H]6C4)N32 | InChI=1S/C22H23ClN4O/c23-18-3-1-17(2-4-18)21-26-25-19-11-24-12-20(27(19)21)28-13-22-8-14-5-15(9-22)7-16(6-14)10-22/h1-4,11-12,14-16H,5-10,13H2/t14-,15+,16-,22? | MFXXXMMQULKXIX-GGTBJBEQSA-N
MMV1557943 | CC1(C)[C@@H]2C[C@H]1C(CCOC3=CN=CC4=NN=C(C5=C(Cl)C=C(Cl)C=C5)N43)=CC2 | InChI=1S/C22H22Cl2N4O/c1-22(2)14-4-3-13(17(22)9-14)7-8-29-20-12-25-11-19-26-27-21(28(19)20)16-6-5-15(23)10-18(16)24/h3,5-6,10-12,14,17H,4,7-9H2,1-2H3/t14-,17-/m0/s1 | OYFPJLPMJIFAIS-YOEHRIQHSA-N
MMV1557944 | CC1(C)[C@@H]2C[C@H]1C(CCOC3=CN=CC4=NN=C(C5=CC=C(Cl)C=C5)N43)=CC2 | InChI=1S/C22H23ClN4O/c1-22(2)16-6-3-14(18(22)11-16)9-10-28-20-13-24-12-19-25-26-21(27(19)20)15-4-7-17(23)8-5-15/h3-5,7-8,12-13,16,18H,6,9-11H2,1-2H3/t16-,18-/m0/s1 | BDWPPKIAXRRNII-WMZOPIPTSA-N
MMV1557945 | ClC(C=C1)=CC(Cl)=C1C2=NN=C3C=NC=C(OCC4C[C@H]5C=C[C@@H]4C5)N32 | InChI=1S/C19H16Cl2N4O/c20-14-3-4-15(16(21)7-14)19-24-23-17-8-22-9-18(25(17)19)26-10-13-6-11-1-2-12(13)5-11/h1-4,7-9,11-13H,5-6,10H2/t11-,12+,13?/m0/s1 | OLAUIVKJLBCHFE-LAGVYOHYSA-N
MMV1557946 | ClC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC4C[C@H]5C=C[C@@H]4C5)N32 | InChI=1S/C19H17ClN4O/c20-16-5-3-13(4-6-16)19-23-22-17-9-21-10-18(24(17)19)25-11-15-8-12-1-2-14(15)7-12/h1-6,9-10,12,14-15H,7-8,11H2/t12-,14+,15?/m0/s1 | OWTVMOKESSEJOP-DJIKBVBFSA-N
MMV1557948 | O=C(NC1=CC=NC=C1)C2=CN=CC3=NN=C(C4=CC=CC=C4)N32 | InChI=1S/C17H12N6O/c24-17(20-13-6-8-18-9-7-13)14-10-19-11-15-21-22-16(23(14)15)12-4-2-1-3-5-12/h1-11H,(H,18,20,24) | JWMBXLLOVDKXRE-UHFFFAOYSA-N
MMV1557947 | C12=NN=C(C3=CC=NC=C3)N1C(OCCC4=CC=CC=C4)=CN=C2 | InChI=1S/C18H15N5O/c1-2-4-14(5-3-1)8-11-24-17-13-20-12-16-21-22-18(23(16)17)15-6-9-19-10-7-15/h1-7,9-10,12-13H,8,11H2 | BSTOZULDVQMNLS-UHFFFAOYSA-N
MMV1557950 | FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OC/C(C4=CC=CC=C4)=N/O)N32 | InChI=1S/C20H15F2N5O3/c21-20(22)30-15-8-6-14(7-9-15)19-25-24-17-10-23-11-18(27(17)19)29-12-16(26-28)13-4-2-1-3-5-13/h1-11,20,28H,12H2/b26-16- | VJSBQKQNONLQQJ-QQXSKIMKSA-N
MMV1557949 | FC(C=C1)=C(F)C=C1CCOC2=CN=CC3=NN=C(C4=CC=CC=C4)N32 | InChI=1S/C19H14F2N4O/c20-15-7-6-13(10-16(15)21)8-9-26-18-12-22-11-17-23-24-19(25(17)18)14-4-2-1-3-5-14/h1-7,10-12H,8-9H2 | RGEIFMMWUNGFHD-UHFFFAOYSA-N
MMV025100 | NS(C1=CC(C2=CC3=NC=NC(N)=C3S2)=CC=C1)(=O)=O | InChI=1S/C12H10N4O2S2/c13-12-11-9(15-6-16-12)5-10(19-11)7-2-1-3-8(4-7)20(14,17)18/h1-6H,(H2,13,15,16)(H2,14,17,18) | MQMXDJVOZKMSNT-UHFFFAOYSA-N
MMV897709 | FC(C=C1)=C(F)C=C1C(OC)COC2=CN=CC3=NN=C(C4=CC=C(C#N)C=C4)N32 | InChI=1S/C21H15F2N5O2/c1-29-18(15-6-7-16(22)17(23)8-15)12-30-20-11-25-10-19-26-27-21(28(19)20)14-4-2-13(9-24)3-5-14/h2-8,10-11,18H,12H2,1H3 | PERKBMZWWUEZNJ-UHFFFAOYSA-N
MMV1557952 | FC(C=C1)=C(F)C=C1[C@@H](OC)COC2=CN=CC3=NN=C(C4=CC=C(C#N)C=C4)N32 | InChI=1S/C21H15F2N5O2/c1-29-18(15-6-7-16(22)17(23)8-15)12-30-20-11-25-10-19-26-27-21(28(19)20)14-4-2-13(9-24)3-5-14/h2-8,10-11,18H,12H2,1H3/t18-/m0/s1 | PERKBMZWWUEZNJ-SFHVURJKSA-N
MMV1557951 | FC(C=C1)=C(F)C=C1[C@H](OC)COC2=CN=CC3=NN=C(C4=CC=C(C#N)C=C4)N32 | InChI=1S/C21H15F2N5O2/c1-29-18(15-6-7-16(22)17(23)8-15)12-30-20-11-25-10-19-26-27-21(28(19)20)14-4-2-13(9-24)3-5-14/h2-8,10-11,18H,12H2,1H3/t18-/m1/s1 | PERKBMZWWUEZNJ-GOSISDBHSA-N
MMV1557953 | FC(C=C1)=C(F)C=C1C(OC)COC2=CN=CC3=NN=C(C4=CC=C(C#N)C=C4)N32 | InChI=1S/C21H15F2N5O2/c1-29-18(15-6-7-16(22)17(23)8-15)12-30-20-11-25-10-19-26-27-21(28(19)20)14-4-2-13(9-24)3-5-14/h2-8,10-11,18H,12H2,1H3 | PERKBMZWWUEZNJ-UHFFFAOYSA-N
MMV1557962 | C12=NN=C(N3CCCCC3)N1C(OCCC4=CC=CC=C4)=CN=C2 | InChI=1S/C18H21N5O/c1-3-7-15(8-4-1)9-12-24-17-14-19-13-16-20-21-18(23(16)17)22-10-5-2-6-11-22/h1,3-4,7-8,13-14H,2,5-6,9-12H2 | QFNWKXKUHMYRFI-UHFFFAOYSA-N

**Comment by MFernflower** [comment]
It's like a chemical Christmas! @edwintse I came up with some really eccentric ideas over at #516 if you are curious

**Comment by spadavec** [comment]
A lot of the SMILES strings in the table didn't resolve for me, so I re-did them by hand; while I had them, I just ran them through my potency predictor and got the following results (link [[here](https://docs.google.com/spreadsheets/d/1FdUsoNy0lpbIEk0fV7mZ1uuDhGcH1eS-SdN5NgZQvuY/edit?usp=sharing)])--apologies for not putting the table in this post. The formatting kept chopping off half of the SMILES patterns for some reason.

**Comment by mattodd** [comment]
Nice @spadavec . We shall see!

**Comment by edwintse** [comment]
We have just received the 1st run potency data from Dundee (linked in the original post above).

**Comment by MFernflower** [comment]
Just got the notification! Looks like SF5 is a good functional group and it seems like the smaller the cage the more potent the drug is - Therefore I propose this monstrosity 
![structure](https://user-images.githubusercontent.com/3164942/29256473-974bdc68-8078-11e7-8b75-ec84536add02.png)

**Comment by mattodd** [comment]
Nice data, Ed. Thoughts.

OSM-S-391: This was made to compare to the iodocubane. Looks like it was the cubane that was the problem there? Can you just remind us of the comparison compound?

OSM-S-394: So how does SF5 compare to OCHF2?

OSM-S-396: What effect does that Me have on potency? i.e. compare to non-Me (“des-Me”) compound.

OSM-S-415: reinforces idea we need a para-substituent in that position I think.

OSM-S-417: given the result for OSM-S-415 I’d say we look exclusively at Norcross compounds with something in the “para” position @maratsydney @mcoster

Caged compounds: not great activity, but remarkable that some are as active as they are: OSM-S-398 and OSM-S-406 for example.

OSM-S-393 and OSM-S-392 are interesting, in that I had thought they might, _in vivo_, be equivalent to some extent. Clearly not. Was a ketal ever made there? [Don’t think so](https://github.com/OpenSourceMalaria/Series4/wiki/Pyrazine-Side-Chain-Modifications---Ethers). 

OSM-S-409: worth a shot. Again, changes here exert a huge effect.

The resolved compounds: This makes little sense, that the mixed fraction is most potent. Can we re-establish exactly what was in each fraction?

The Late Stage Functionalisation compounds OSM-S-407 and OSM-S-408. Well, @ConorGraham  is going to react these. Things can only get better.

OSM-S-106: good ping @mbhebhe

**Comment by MFernflower** [comment]
@mattodd I think while PhSF5 is about as potent as PhOCHF2 that there are some advantages with the SF5 but they will need to be confirmed experimentally

1. the SF5 compound will not cross the BBB and thus allow it to concentrate in blood and in liver tissue (the two main sites where the parasite lives but will render it useless in cases where it's gone neural) 
2. The PhSF5 functionality will (most likely) not be attacked by any mammalian enzymes, this greatly increasing the half life of the drug (we may get 12 hour half life) 
3. While water solubility takes a hit, I believe this compound will be great in rat tests when given via I.M injection

**Comment by mattodd** [comment]
We need some clarity on the resolved compounds (#470). The HPLC traces were posted [here](http://malaria.ourexperiment.org/triazolopyrazine_se/15765/post.html). The [potency data](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/NzEyLjR8MTUwOS81NDgvVHJlZU5vZGUvMzU4OTEzMDg4N3wxODA4LjM5OTk5OTk5OTk5OTk=) here are confusing. Are we absolutely sure of the correspondence between the samples that were evaluated and the HPLC traces? Obviously under normal circumstances the scalemic compound would not be the most potent.

MMV897709 (OSM-S-218): “HPLC Trace”. Racemic. Retention times (Rt) 17.6 18.5. **Potency** 1.27 uM
MMV1557952 (OSM-S-413) “Isolated P1”. Enantiopure. Rt 17.9 **Potency** >10 uM
MMV1557951 (OSM-S-414) “Isolated P2”. Enantiopure. Rt 16.9 **Potency** 0.94 uM
MMV1557953 (OSM-S-416) “failed separation”. Scalemic P1+P2. **Potency** 0.45 uM

@edwintse and @alintheopen  can you please double-check codes are right, and I'll ping Mark Butler on Twitter.

**Comment by cdsouthan** [comment]
This  aspect was mentioned already in https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/533#issuecomment-321202699 but I have split it out as a new point 9.

**Comment by MFernflower** [comment]
I'm curious: How difficult would it be to do a stereoselective synthesis of the "good" isomer and subsequent rescreen of compound? This would greatly clear up confusion about the purified mixtures that were tested

**Comment by edwintse** [comment]
UPDATE:
The 2nd run potency data has been received. The values in the image on the ELN have been updated. For the most part, the activities are slightly lower, with a few exceptions. (The original image has been moved to the bottom of the page). An export of the data from ScienceCloud has also been uploaded to that page. These values will now be added to the master list.
