### ISSUE TITLE
GU Project 1: Synthesis and reactions of 3-bromo-5-chloro-[1,2,4]triazolo[4,3-a]pyrazine

### ISSUE THREAD

**Issue by mcoster** [OpenSourceMalaria/OSM_To_Do_List#518]
GU Project 1 will focus on optimising the synthesis of 3-bromo-5-chloro-[1,2,4]triazolo[4,3-a]pyrazine and, if time allows, an exploration of the chemistry of this molecule, as outlined below:

![cohan - synthetic plan](https://user-images.githubusercontent.com/28282596/28353429-15a9f16e-6c9f-11e7-8511-25f91abad672.png)

The project is being undertaken by Cohan, who is working in a lab with excellent access to analytical instruments (LC-MS, GC-MS) and variable temperature NMR, but is less well-equipped for organic synthesis. Cohan is interested in analysing reactions in detail with a view to optimising yields, and minimising reaction and purification times.

Links:
[AEW 85-x](http://malaria.ourexperiment.org/triazolopyrazine_se/15880/Synthesis_of_2Chloro6hydrazinylpyrazine_AEW_85x.html)
[EGT 225-1](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/NDIzLjh8MTUwOS8zMjYvVHJlZU5vZGUvMjMyNzY4ODg1fDEwNzUuOA==)
[JT 2-1](https://au-mynotebook.labarchives.com/share/Jasper%2520Tyler%2520OSM%2520Project/MTkuNXwyNTQyNC8xNS9UcmVlTm9kZS8yNDU3NzczODI3fDQ5LjU)
[JT 8-1](https://au-mynotebook.labarchives.com/share/Jasper%2520Tyler%2520OSM%2520Project/MTkuNXwyNTQyNC8xNS9UcmVlTm9kZS8yNDU3NzczODI3fDQ5LjU)
Earlier discussion of Griffith Uni OSM contributions - GHI #508 
Jasper Tyler's halogenation project - GHI #493 
[OSM Synthetic Branches](http://www.openwetware.org/wiki/OpenSourceMalaria:Synthesis_Branches) - [OSM-BrCl](http://tinyurl.com/OSM-Branch-BrCl)

Files:
[Cohan - synthetic plan.zip](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/1158202/Cohan.-.synthetic.plan.zip)

Strings:
3-bromo-5-chloro-[1,2,4]triazolo[4,3-a]pyrazine
InChIKey=UGKMQVWBWSZEBB-UHFFFAOYSA-N
InChI=1S/C5H2BrClN4/c6-5-10-9-4-2-8-1-3(7)11(4)5/h1-2H
ClC1=CN=CC2=NN=C(Br)N12

(edit: added zip, fixed compound name in text, but not in title, fixed scheme - was missing pyrazole N's)
(edit 2: added compound strings)

**Comment by MFernflower** [comment]
Love the use of the microwave! if time permits what would you replace the Br atom with? I would think simple N-linked cycles like morpholine, azetidine, pyrrolidine, etc?  @mcoster

**Comment by mcoster** [comment]
Yes, definitely interested in _N_-linked hetercycles and seeking feedback/suggestions about what to aim for.

**Comment by MFernflower** [comment]
Well if you would ask me what two really i would like it would be the
morpholine and azitedine

**Comment by MFernflower** [comment]
Azetidine and morpholine seem like good choices - @mattodd Got anything else to chime in with?

**Comment by mattodd** [comment]
These are the [Norcross compounds](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/390#issuecomment-223461180). Still high-value, and the primary reason this chemical need was developed. Anything non-aromatic that helps solubility would be good. Aromatic groups in that northeast position need something in the para position for potency. Given that the N-linked groups would have a different positioning, I'd expect the same requirement not to be there for any cyclic aliphatics we include.

**Comment by juliasmith2** [comment]
We are Julia and Guadalupe from the Broadrup Lab at Haverford College. Based on our NMR analysis we believe we have synthesized 3-bromo-5-chloro-[1,2,4]triazolo[4,3-a]pyrazine. If interested, our lab notebook is here: http://malaria.ourexperiment.org/synthesis_of_3_brom 
We are interested in exploring possible chemistry with this intermediate.

**Comment by drc007** [comment]
@juliasmith2 Looking at the NMR it appears to have extra peaks?

**Comment by edwintse** [comment]
@juliasmith2 @drc007 It looks like there's still a lot of NBS (2.96) left which would mean the yield is not as high.

**Comment by edwintse** [comment]
@juliasmith2 @drc007 It looks like there's still a bit of NBS (2.96) left so the yield might not be as high. Also some water, DCM, EtOAc, hexanes/grease and succinimide.

**Comment by MFernflower** [comment]
I wonder if it is worth doing the coupling on the impure product and then dealing with the garbage at a later step?

**Comment by rbroadrup-HC** [comment]
We can look at recrystallization when students return from August research
recess to see if that may quickly remove some of the non-volatile
impurities.

**Comment by mcoster** [comment]
Much belated update. Cohan worked hard at this project during the trimester, putting particular effort into developing chromatographic methods that allow following these early steps and determination of compound purity. As an aside, this experience sets him up well for his chosen Honours project next year, which is in the forensic chemistry area dealing with profiling of organic synthesis routes.

We did not have a chance to look at many of the original aims of the project. In our hands, step 2 - the acid-mediated reaction with triethyl orthoformate, did not give high yields or purity. Some preliminary results suggested that trimethyl orthoformate may be more productive, although this needs to be followed up and verified.

Below are Cohan's research report and poster that he presented for this project. I'll close this issue and any further efforts at Griffith will be reported in mew issues.

[Triazolo Pyrazine Report_1.pdf](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/1525609/Triazolo.Pyrazine.Report_1.pdf)

[Draft Poster 2.pdf](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/1525602/Draft.Poster.2.pdf)

**Comment by mattodd** [comment]
Thanks, great to get the reports @mcoster . We need, I think, a repository of these standalone student reports. I wonder if Figshare or something would be a useful backup? Or a labarchives ELN page? 
If Github itself, then I need to activate a repository for such things - reports, posters, any other docs. Some student reports are linked [here](https://github.com/OpenSourceMalaria/Series4/wiki/Sources-of-Data), and you could add?

Separately, are there any key findings from the reports that could be extracted and added in to the synthetic chemistry section of the S4 wiki, e.g. [here](https://github.com/OpenSourceMalaria/Series4/wiki/Synthesis-of-the-Ether-Linked-Series) or related pages?

**Comment by mcoster** [comment]
@mattodd I think Figshare would be my first choice because I'm hoping to use it for non-OSM things in future, and it would be good for me to get started.

This first stab at contributing to OSM has given us some good experience with the chemistry and how to run this sort of project, but we don't have much to contribute to the actual science thus far. I am planning a post to summarise our findings and discuss our future plans. I'll link back to all these closed "GU Project" issues. Should I put our summary and future plans post up on "Series 4" or "OSM_To_Do_List"?

**Comment by mattodd** [comment]
If all related to Series 4 chemistry then I think on the Series 4 repo issue list. Sounds v good.

**Comment by mattodd** [comment]
One more "loose end" action. If you were able to install some link on the [DKNYS](https://github.com/OpenSourceMalaria/Series4/wiki/Desirable-Compounds-Not-Yet-Synthesised) page of the wiki (if it's not there already) that'd be very good. Just to ensure that none of the relevant effort towards a target is ever orphaned.

**Comment by mcoster** [comment]
Ah, good point!

**Comment by david1597** [comment]
Thanks for updating and closing these points, @mcoster. Great to know the outcomes. I'd been looking back just this morning at all the 'Being Synthesised Now" issues and wondering where each was up to. Thanks!

**Comment by mcoster** [comment]
The DCNYS page of the wiki has now been updated. Thanks for the suggestion.

**Comment by mattodd** [comment]
Since this page itself wasn't in the DCNYS page, because it's methodology, I installed a link in [one of the methodology pages](https://github.com/OpenSourceMalaria/Series4/wiki/Alternative-Routes-to-the-Triazolopyrazine-Core) for now. Also will upload reports to a github repo. Ideally the reports would also be available on the relevant student ELN?
