### ISSUE TITLE
GU Project 2: Bromination of Jasper 3 and functionalisation of that product

### ISSUE THREAD

**Issue by mcoster** [OpenSourceMalaria/OSM_To_Do_List#519]
**Outline**
GU Project 2 will focus on brominating Jasper 3 (#493) and, if time permits, exploring derivatisation of that product:

![lachlan - synthetic plan](https://user-images.githubusercontent.com/28282596/28354602-e0a5a490-6ca3-11e7-8f82-105a6133dd44.png)

The project is being undertaken by Lachlan, who is studying spectroscopy this term, and hence will be putting his new NMR interpretation skills to the test for the first time.

**Links:**
[AEW 85-x](http://malaria.ourexperiment.org/triazolopyrazine_se/15880/Synthesis_of_2Chloro6hydrazinylpyrazine_AEW_85x.html)
[EGT 225-1](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/NDIzLjh8MTUwOS8zMjYvVHJlZU5vZGUvMjMyNzY4ODg1fDEwNzUuOA==)
[JT 2-1, JT 13-2, JT 14-2](https://au-mynotebook.labarchives.com/share/Jasper%2520Tyler%2520OSM%2520Project/MTkuNXwyNTQyNC8xNS9UcmVlTm9kZS8yNDU3NzczODI3fDQ5LjU)
Earlier discussion of Griffith Uni OSM contributions - GHI #508
Jasper Tyler's halogenation project - GHI #493
[OSM Synthetic Branches](http://www.openwetware.org/wiki/OpenSourceMalaria:Synthesis_Branches) - [OSM-BrCl](http://tinyurl.com/OSM-Branch-BrCl)

**Files:**
[Lachlan - synthetic plan.zip](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/1158297/Lachlan.-.synthetic.plan.zip)

**Strings:**
3-bromo-5-(2-phenylethoxy)-[1,2,4]triazolo[4,3-a]pyrazine
InChIKey=TUOSCZBYUFCYTF-UHFFFAOYSA-N
InChI=1S/C13H11BrN4O/c14-13-17-16-11-8-15-9-12(18(11)13)19-7-6-10-4-2-1-3-5-10/h1-5,8-9H,6-7H2
BrC1=NN=C2C=NC=C(OCCC3=CC=CC=C3)N12

**Comment by maratsydney** [comment]
Hello! 
My name is Marat Korsik and I just started my PhD at The University of Sydney School of Chemistry with Matthew Todd.
I am currently working on same topic, with major focus on finding optimal conditions for halogenation of molecules like JT-14. Here the scheme with entry number for reaction referring to my ELN, so we can work together.  
![scheme for github issue 519](https://user-images.githubusercontent.com/29498087/28400292-5ba650d4-6d55-11e7-97d1-40eb8ef01b82.png)

This the link to my ELN http://tinyurl.com/OSM-Marat

**Comment by mcoster** [comment]
Thanks for the post @maratsydney - looks like you and my students, Cohan and Lachlan, should keep each other updated. Good luck!

**Comment by mattodd** [comment]
Right @mcoster - this is an *excellent* test case. Provided everyone maintains their lab notebook online, and occasionally posts updates on important developments, then we as a group should be able to nail this chemistry faster. Complementary, not duplicative reactions, unless someone finds something awesome in which case the other can verify. I'm excited.

**Comment by mcoster** [comment]
Absolutely! It will be interesting to see what comes of these efforts, and as you say, @mattodd, a group effort should make everyone's life better - as soon as positive developments arise, they can be implemented or improved upon further by other OSM people.

@maratsydney love the detail in your ELN - those TLC and reaction mixture photos will be great for others following this work! Re MK002-1, I wasn't sure from your ELN entry - did this reaction give the desired product?

@maratsydney, @mattodd, others...  Re: LabArchives ELN entries - is it possible to copy a URL to a particular entry? I can only seem to get the URL for the whole Notebook.

**Comment by maratsydney** [comment]
@mcoster, in MK002-1 I didn't get **desired** product but synthesised compound will be characterized soon.  

Talking about LabArchives: as far as I know link to the particular entry can be created only by author of ELN.

**Comment by mattodd** [comment]
Hmm, not sure re Labarchives. The way it normally works is to right-click on the ELN entry and explore the "sharing" options, but it might be that that's only available to certain users, yes. One can create a DOI for any given entry, so we could start doing that, but might be annoyingly manual.
I suspect the bromination reaction will be the first reaction where we'll need some intensive back-and-forth optimisation. When we get to that point we could create a new issue and gradually add attempts.

**Comment by LachlanKlein** [comment]
Hey everyone! Im currently undertaking this project. Thank you @mcoster for writing this up. Just thought id keep everyone updated, I will be restarting as the product from the 2nd experiment (Synthesis of 5-chloro-[1,2,4]triazolo[4,3-a]pyrazine) yielded a very low product, about 40mg and couldnt confirm that this was the correct product. I think this was due to not purifying after the first step which I will do this time. 

Some questions that I had. How much of a compound will be needed as a minimum to test its functionalities against malaria? As this experiment is being performed on 10x less scale compared to @jaspert95 experiment, the theoretical yield from experiment 1 should be ~2g. However, halogenation of Jasper 3 has shown very low yields. So I was just wondering how much of the compound will be needed and if this experiment should produce an adequate amount. 

@maratsydney, wonderful work you are currently doing and I look forward to reading more about how you optimise the conditions

If anyone has any suggestions, feel free to let me know.
Here is a link to the [current lab book](book http://malaria.ourexperiment.org/griffith_uni_mcoster
)

**Comment by mattodd** [comment]
Well, 2 mg is enough to see if you're killing the parasite, but you can
screen for methodology on any scale. I think Marat is going to run
halogenations on enough material to give clear outputs by TLC, and maybe to
give a decent crude NMR spectrum, e.g. 10 mg. But let's share and see what
works.

**Comment by mcoster** [comment]
This project came to and end in Octber. Similar to the work by Cohan (GHI #518), Lachlan worked hard, but didn't make it to the later aims of this project. Results are reported in the below report and poster. Closing issue.

[Full Capstone report LK.docx](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/1525616/Full.Capstone.report.LK.docx)

[Capstone poster.pdf](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/1525617/Capstone.poster.pdf)
