### ISSUE TITLE
GU Project 3: Synthesis of the Internal Alkyne, internal Alkene and the Alkyl

### ISSUE THREAD

**Issue by mcoster** [OpenSourceMalaria/OSM_To_Do_List#520]
**Outline**
GU Project 3 will focus on synthesis of "the Internal Alkyne" and, if time permits, conversion to "the Alkyl" and "the internal Alkene":

![yang - synthetic plan](https://user-images.githubusercontent.com/28282596/28397409-ab9ab17c-6d44-11e7-8ae5-c7d7f6bbb1c5.png)

_Note_: we will be getting familiar with the chemistry via the 4-chlorophenyl series (from 4-chlorobenzaldehyde) until our order of 4-(difluoromethoxy)benzaldehyde arrives.

Our plan is heavily based on that proposed in GHI #418. There has been considerable progress and significant effort expended by other students on this molecule, so to avoid possible duplication with work ongoing elsewhere or soon to commence, we will attempt the key Sonogashira coupling via different methods. The reference cited uses fairly standard conditions including copper. If this fails, we will look at other possibilities. Out of curiosity is anyone aware of any attempts to react metalated (eg. Li, MgX, ZnX) phenylacetylene with the chlorotriazolopyrazine directly? Curious since this substrate engages in SNAr with other nucleophiles. Another alternative we may explore is conversion to the aryl iodide then Sonogashira type reactions on that.

The project is being undertaken by Yang, who is completing the fourth year of his degree at Griffith University as part of a collaboration between GU and Nanjing University of Chinese Medicine.

**Links:**
[AEW 85-x](http://malaria.ourexperiment.org/triazolopyrazine_se/15880/Synthesis_of_2Chloro6hydrazinylpyrazine_AEW_85x.html)
[EGT 24-2, EGT 25-6](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/NDIzLjh8MTUwOS8zMjYvVHJlZU5vZGUvMjMyNzY4ODg1fDEwNzUuOA==)
[Haverford Superlab ELN - Pd/C, XPhos Sonogashira attempts](http://malaria.ourexperiment.org/internal_alkyl)
[Haverford Superlab ELN - InCl3 coupling attempts](http://malaria.ourexperiment.org/reduced_alkyl)
Previous synthetic planning - #418, #403 
Earlier discussion of Griffith Uni OSM contributions - GHI #508
[OSM Desirable Compounds Not Yet Synthesised (DC-NYS](http://www.openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_(TP)_Series#Desirable_Compounds_Not_Yet_Synthesised)

**Files:**
[Yang - synthetic plan.zip](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/1160909/Yang.-.synthetic.plan.zip)

**Strings:**
"Internal Alkyne" (R = OCHF2)
InChIKey=KNVACGGMAGPRRW-UHFFFAOYSA-N
InChI=1S/C20H12F2N4O/c21-20(22)27-17-10-7-15(8-11-17)19-25-24-18-13-23-12-16(26(18)19)9-6-14-4-2-1-3-5-14/h1-5,7-8,10-13,20H
FC(F)OC1=CC=C(C=C1)C1=NN=C2C=NC=C(C#CC3=CC=CC=C3)N12

(edit: improved resolution of the reaction scheme)

**Comment by mattodd** [comment]
Don't think anyone's tried organometallic additions to that position, since it had generally been possible to use conventional nucleophiles. [In the inherited data for the series were a few compounds that may have come from this kind of method](http://www.openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_(TP)_Series#Pyrazine_Side_Chain_Modifications_-_Others), but we don't have details of the synthesis to hand. As we write up the Series 4 paper we may have to get more serious about requesting details, but there's no certainty that we can access such details because we'd first need to know whether the compounds were made by Pfizer or the CRO that subsequently looked at this chemistry.

**Comment by MFernflower** [comment]
@mcoster Interesting reaction pertinent for this: http://www.organic-chemistry.org/abstracts/lit3/532.shtm

**Comment by mcoster** [comment]
Yang finished working on this project. He was successfully able to synthesise the substrate for the Sonogashira coupling, however, the one attempt did not deliver the desired product. Closing issue.
