### ISSUE TITLE
GU Project 4: Synthesis of the Heterooxadiazole

### ISSUE THREAD

**Issue by mcoster** [OpenSourceMalaria/OSM_To_Do_List#521]
**Outline**
GU Project 4 will focus on synthesis of "the Heterooxadiazole". I'd prefer to just call it the oxadiazole, but to avoid confusion we'll stick with that name!

![tian - synthetic plan](https://user-images.githubusercontent.com/28282596/28458107-df499c1a-6e4b-11e7-996d-371485f2d4d9.png)

_Note_: we will be getting familiar with the chemistry via the 4-chlorophenyl series (from 4-chlorobenzaldehyde) until our order of 4-(difluoromethoxy)benzaldehyde arrives.

Our plan is heavily based on that proposed for the "Heterooxazole" in GHI #462, involving C-H arylation of the oxa(dia)zole. [This paper](http://onlinelibrary.wiley.com/doi/10.1002/adsc.201600913/abstract) suggests a Pd catalysed, silver-assisted process with the oxadiazole may be feasible. From what we can see, this differs from previous approaches that proposed formation of the oxadiazole by condensation of a triazolopyrazine ester with an amidoxime (GHI #448, #463).

The project is being undertaken by Tian, who is completing the fourth year of his degree at Griffith University as part of a collaboration between GU and Nanjing University of Chinese Medicine.

**Links:**
[AEW 85-x](http://malaria.ourexperiment.org/triazolopyrazine_se/15880/Synthesis_of_2Chloro6hydrazinylpyrazine_AEW_85x.html)
[EGT 24-2, EGT 25-6](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/NDIzLjh8MTUwOS8zMjYvVHJlZU5vZGUvMjMyNzY4ODg1fDEwNzUuOA==)
Synthesis of 3-phenyl-1,2,4-oxadiazole and C-H arylation thereof - [_Adv. Synth. Cat._ **2017**, _359_, 772-778.](http://onlinelibrary.wiley.com/doi/10.1002/adsc.201600913/abstract)
ArCl -> ArI using CiI, KI, DMI: [Patent WO 2011111423](http://www.google.co.in/patents/WO2011111423A1?cl=en)
ArCl -> ArI using NaI, AcOH, H2SO4, MeCN: [_Tetrahedron_ **1998**, _54_, 9701-9710.](http://www.sciencedirect.com/science/article/pii/S0040402098005262)
[Haverford Superlab ELN1](http://malaria.ourexperiment.org/hc_q2_het_oxadiazole)
[Haverford Superlab ELN2](http://malaria.ourexperiment.org/haverford_superlab_)
Previous synthetic planning - #448, #463 
Earlier discussion of Griffith Uni OSM contributions - #508
[OSM Desirable Compounds Not Yet Synthesised (DC-NYS)](http://www.openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_(TP)_Series#Desirable_Compounds_Not_Yet_Synthesised)

**Files:**
[Tian - synthetic plan.zip](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/1165182/Tian.-.synthetic.plan.zip)

**Strings:**
"Heterooxadiazole" (R = OCHF2)
InChIKey=HFPKPTYSFARKAA-UHFFFAOYSA-N
InChI=1S/C20H12F2N6O2/c21-20(22)29-14-8-6-13(7-9-14)18-26-25-16-11-23-10-15(28(16)18)19-24-17(27-30-19)12-4-2-1-3-5-12/h1-11,20H
FC(F)OC1=CC=C(C=C1)C1=NN=C2C=NC=C(N12)C1=NC(=NO1)C1=CC=CC=C1

**Comment by drc007** [comment]
You could make the reverse oxadiazole by displacing the aryl iodide with cyanide, then convert to amide oxime.

**Comment by mcoster** [comment]
Thanks @drc007 - unfortunately oh&s around cyanide use and storage is very prohibitive at my university these days, and will be particularly hard to get the required support for undergrad project students to use it, so we'll leave that approach for another group. Good suggestion though!

**Comment by drc007** [comment]
<rant>Shouldn't undergraduate lab training be about learning how to handle, reactive, air sensitive, toxic chemicals safely? So when they go into a lab they know how to work safely?<rant over>.

**Comment by mcoster** [comment]
Completely agree! I still think it would be possible to do so, just lots of obstacles to jump over. Unfortunately, cyanide use and storage (and even benzene!) here requires a license from Qld Health. We formerly had a license holder within the building, but that lapsed and was not renewed due to lack of use.

**Comment by mattodd** [comment]
Nice route @mcoster and nice lit chemistry there. I'm interested if that works. Even getting to good quantities of the chloro core and the oxadiazole would be important so that you and others can perform the cross-coupling campaign.

**Comment by drc007** [comment]
I agree a stock of the chloro (or iodo) core would be very valuable, perhaps also look at making the boronic acid? Could open up lots of interesting cross-coupling chemistry.

**Comment by mcoster** [comment]
We just had Nicholas Meanwell give an incredibly useful workshop on three topics: i) fluorine in med chem, ii) bioisosteres, and iii) toxicology. During the second topic, he presented some comparisons of different heteroaromatic scaffolds. A takeaway message for me was that 1,3,4-oxadizoles often have better properties than 1,2,4-oxadiazoles. An example he presented showed analogous compounds where the former was more soluble and had lower logP than the latter. Sorry, don't have my notes here with me right now for details.. It does make me wonder whether a 1,3,4-oxadizole should be an even higher priority target than the current 1,2,4-oxadiazole:

![1 2 4-oxadiazole](https://user-images.githubusercontent.com/28282596/28824864-594b6aca-7707-11e7-9633-575267703988.jpg)

Thoughts?

**Comment by mattodd** [comment]
That takes me back. Your comment has triggered a buried memory that @alintheopen had the same thought in the Series 1 project, described [here](http://www.thesynapticleap.org/node/422). Looks good to me!

**Comment by drc007** [comment]
I suspect publication is worth mentioning
http://pubs.rsc.org/en/Content/ArticleLanding/2012/MD/c2md20054f#!divAbstract

**Comment by mcoster** [comment]
Nice paper - here's a few more. I have Nicholas Meanwell's excellent notes in front of me now. On a slide titled "Isosteric Deployment of Heterocycles", he references the following articles:
[TJ Ritchie _et al._ _Drug Discov. Today_, **2009** _14_, 1011-1020](http://csmres.co.uk/cs.public.upd/article-downloads/Most%20downloaded%20article%20Q4%202009_a15573.pdf)
[Ibid, **2011**, _16_, 164-171](http://www.sciencedirect.com/science/article/pii/S1359644610008366)
[TJ Ritchie _et al._ _MedChemComm_ **2012**, _3_, 1062-1069](http://pubs.rsc.org/en/content/articlelanding/2012/md/c2md20111a/unauth#!divAbstract)
[C Wermuth Ibid, **2011**, _2_, 935-941](http://pubs.rsc.org/En/journals/journalissues/md?issueid=md002010&type=current#!issueid=md002010&type=current&issnprint=2040-2503)
[Boström _et al._ _J Med. Chem._ **2012**, _55_, 1817-1830](http://pubs.acs.org/doi/abs/10.1021/jm2013248)

**Comment by MFernflower** [comment]
@drc007 @mcoster It would be epic if we could made and test all three ring systems!

**Comment by mcoster** [comment]
Yang finished working on this project in October. He was able to synthesise the chloro 4-(difluoromethoxy)triazolopyrazine, however, the one attempt to convert this compound to the corresponding iodide was not successful. Issue closed.
