### ISSUE TITLE
GU Project 5: Synthesis of the Heterooxazole

### ISSUE THREAD

**Issue by mcoster** [OpenSourceMalaria/OSM_To_Do_List#522]
**Outline**
GU Project 5 will focus on synthesis of "the Heterooxazole":

![daisy - synthetic plan](https://user-images.githubusercontent.com/28282596/28824039-ad185798-7703-11e7-9605-da6d07043c65.png)

_Note_: we will be getting familiar with the chemistry via the 4-chlorophenyl series (from 4-chlorobenzaldehyde) until our order of 4-(difluoromethoxy)benzaldehyde arrives.

Our plan is basically to follow the route proposed in GHI #462, involving C-H arylation of the oxazole. [This paper](http://onlinelibrary.wiley.com/doi/10.1002/adsc.201600913/abstract) suggests a Pd catalysed, silver-assisted process with the oxazole may be feasible. Other conditions were also suggested in #462, eg. Pd(OAc)<sub>2</sub>, X-Phos or CataCXium A, K<sub>2</sub>CO<sub>3</sub>, pivalic acid - [_Org. Lett._ **2010**, _12_, 3578-3581.](http://pubs.acs.org/doi/10.1021/ol1011778) We will also try a different approach to access the expensive 2-phenyloxazole.

The project is being undertaken by Daisy, who is completing the fourth year of her degree at Griffith University as part of a collaboration between GU and Nanjing University of Chinese Medicine.

**Links:**
[AEW 85-x](http://malaria.ourexperiment.org/triazolopyrazine_se/15880/Synthesis_of_2Chloro6hydrazinylpyrazine_AEW_85x.html)
[EGT 24-2, EGT 25-6](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/NDIzLjh8MTUwOS8zMjYvVHJlZU5vZGUvMjMyNzY4ODg1fDEwNzUuOA==)
C-H arylation of oxadiazoles and other heteroaromatics - [_Adv. Synth. Cat._ **2017**, _359_, 772-778.](http://onlinelibrary.wiley.com/doi/10.1002/adsc.201600913/abstract)
C-H arylation of oxazoles, eg. Pd cat. + X-Phos - [_Org. Lett._ **2010**, _12_, 3578-3581](http://pubs.acs.org/doi/10.1021/ol1011778)
ArCl -> ArI using CiI, KI, DMI: [Patent WO 2011111423](http://www.google.co.in/patents/WO2011111423A1?cl=en)
ArCl -> ArI using NaI, AcOH, H2SO4, MeCN: [_Tetrahedron_ **1998**, _54_, 9701-9710.](http://www.sciencedirect.com/science/article/pii/S0040402098005262)
2-phenyloxazoline from benzonitrile and 2-aminoethanol - [_Open Catalysis Journal_ **2009**, _2_, 163-165](https://benthamopen.com/ABSTRACT/TOCATJ-2-163)
Oxidation of 2-phenyloxazoline to 2-phenyloxazole - [_Org. Lett._ **2010**, _12_, 4686-4689](http://pubs.acs.org/doi/abs/10.1021/ol102078v)
[Haverford Superlab ELN - the Heterooxazole](http://malaria.ourexperiment.org/synthesis_of_hetero)
Previous synthetic planning - #462, #407  
Earlier discussion of Griffith Uni OSM contributions - #508
[OSM Desirable Compounds Not Yet Synthesised (DC-NYS)](http://www.openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_(TP)_Series#Desirable_Compounds_Not_Yet_Synthesised)

**Files:**
[Daisy - synthetic plan.zip](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/1190484/Daisy.-.synthetic.plan.zip)

**Strings:**
"Heterooxazole" (R = OCHF2)
InChIKey=FBTBZFMQUBZDSN-UHFFFAOYSA-N
InChI=1S/C21H13F2N5O2/c22-21(23)29-15-8-6-13(7-9-15)19-27-26-18-12-24-10-16(28(18)19)17-11-25-20(30-17)14-4-2-1-3-5-14/h1-12,21H
FC(F)OC1=CC=C(C=C1)C1=NN=C2C=NC=C(N12)C1=CN=C(O1)C1=CC=CC=C1

Edit (8 Aug 2017): Fixed typo in scheme "Heterooxadiazole" -> "Heterooxazole"

**Comment by mattodd** [comment]
Ditto vs #521. Lovely chemistry and very interested to see how it plays out. Ditto development of reliable routes to the coupling partners as an important thing to promote any future coupling campaigns, should Daisy not quite get there (but let's be optimistic - of course she'll get there!).

Just to clarify - when the lab notebooks are up and running you'll add the link to the above post, right?

**Comment by MFernflower** [comment]
The synthesis plan of the 2-phenyloxazole is simply beautiful

**Comment by drc007** [comment]
Label in scheme should read Heterooxazole not  Heterooxadizole

**Comment by MFernflower** [comment]
If you got extra product will you try to couple 2-phenyloxazoline too? Two
molecules for the price of one! @mcoster

**Comment by mcoster** [comment]
@drc007 - well spotted! Fixed.

@MFernflower - I'm always keen to get two molecules for the price of one, but I suspect these types of C-H activations require heteroaromatics, with C(sp<sup>2</sup>)-H bonds being activated.

**Comment by MFernflower** [comment]
I figured it would work by adding across the C=C bond - I'd be curious as
to see if you could couple to phenylfuran - just a thought

**Comment by mcoster** [comment]
Daisy finished working on this project in October. She was able to synthesise the chloro 4-(difluoromethoxy)triazolopyrazine, however, the one attempt to convert this compound to the corresponding iodide was not successful. Issue closed.
