### ISSUE TITLE
GU Project 6: Synthesis of phenylalaninol ether side-chain

### ISSUE THREAD

**Issue by mcoster** [OpenSourceMalaria/OSM_To_Do_List#523]
**Outline**
GU Project 6 will focus on synthesis of a phenylalaninol ether side-chain:

![morgana - synthetic plan](https://user-images.githubusercontent.com/28282596/28499439-6cfd9242-6ff9-11e7-9d2d-b82af9e4eace.png)

_Note_: we will be getting familiar with the chemistry via the 4-chlorophenyl series (from 4-chlorobenzaldehyde) until our order of 4-(difluoromethoxy)benzaldehyde arrives.

Our plan is to use Boc protection of L-phenylalaninol prior to base-promoted reaction with the chlorotriazolopyrazine. Previous work using unprotected phenylalaninol failed to give the desired product - GHI #254. Out of interest, do these systems tolerate Boc deprotection conditions? Also, more generally, this compound doesn't seem to have been an active target since 2014. It's still listed as a Desirable Compound Not Yet Synthesised, but is there any reason to believe it may not be of as much interest at the present time?

The project is being undertaken by Morgana, who is completing the fourth year of her degree at Griffith University as part of a collaboration between GU and Nanjing University of Chinese Medicine.

**Links:**
[AEW 85-x](http://malaria.ourexperiment.org/triazolopyrazine_se/15880/Synthesis_of_2Chloro6hydrazinylpyrazine_AEW_85x.html)
[EGT 24-2, EGT 25-6](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/NDIzLjh8MTUwOS8zMjYvVHJlZU5vZGUvMjMyNzY4ODg1fDEwNzUuOA==)
[AEW 313-1](http://malaria.ourexperiment.org/triazolopyrazine_se/14500/Synthesis_of_45234difluorophenyl2methoxyethoxy124triazolo43apyrazin3ylbenzonitrile_AEW_3131.html)
Synthesis of Boc-L-phenylalaninol - [_Chem. Eur. J._ **2016**, _22_, 7524-7532](http://onlinelibrary.wiley.com/doi/10.1002/chem.201600214/abstract) & [_Synthesis_ **2014**, _46_, 2191-2200](https://www-thieme-connect-de/products/ejournals/html/10.1055/s-0033-1338636)
[Previous work - Joanna Ubels' ELN](http://malaria.ourexperiment.org/triazolopyrazine_se/10883/Synthesis_of_R134chlorophenyl124triazolo43apyrazin5yloxy3phenylpropan2amine_JU_231.html)
Previous synthetic planning - #254 
Earlier discussion of Griffith Uni OSM contributions - #508
[OSM Desirable Compounds Not Yet Synthesised (DC-NYS)](http://www.openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_(TP)_Series#Desirable_Compounds_Not_Yet_Synthesised)

**Files:**
[Morgana - synthetic plan.zip](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/1168073/Morgana.-.synthetic.plan.zip)

**Strings:**
(_R_)-1-((3-(4-(difluoromethoxy)phenyl)-[1,2,4]triazolo[4,3-a]pyrazin-5-yl)oxy)-3-phenylpropan-2-amine
"The Phenylalaninol ether"
InChIKey=FXPPGJNSMWQGRD-XISACWJONA-N
InChI=1/C21H19F2N5O2/c22-21(23)30-17-8-6-15(7-9-17)20-27-26-18-11-25-12-19(28(18)20)29-13-16(24)10-14-4-2-1-3-5-14/h1-9,11-12,16,21H,10,13,24H2/t16-/s2
N[C@@H](COC1=CN=CC2=NN=C(N12)C1=CC=C(OC(F)F)C=C1)CC1=CC=CC=C1

**Comment by MFernflower** [comment]
@mcoster I wonder if it would be easier to just purchase the alcohol??? https://www.alfa.com/en/catalog/B25019/

**Comment by mcoster** [comment]
@MFernflower Thanks for spotting that! We have such a limited budget that we often need to synthesise things instead of buying them, especially if we have the precursors in our historical inventory. However, it had slipped my attention that Boc-D-phenylalaninol was quite so cheap. We now have some on order.

At the moment, the students are getting lab experience with the p-Cl series until our p-OCHF<sub>2</sub> comes in. We have the p-CN as an alternative. @MFernflower - are you able to link to the issue(s) where @MedChemProf discusses side reactions with p-Cl series in reaction with alkoxide? Thanks!

**Comment by MFernflower** [comment]
don't recall where he had the issue. He should respond in a day or two methinks

**Comment by MFernflower** [comment]
@mcoster https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/487

**Comment by mcoster** [comment]
Thanks. I'd guess that the p-Cl is only problematic in transition metal catalysed cross-couplings, so naked alkoxide reaction via S<sub>N</sub>Ar mechanism should be ok. Nevertheless, we'll focus on p-OCHF<sub>2</sub> once we have access to that.

**Comment by mattodd** [comment]
This'd be a _very_ nice compound to have for the series. Primary, solubilising amine. Benzylic positions available for metabolic oxidation but hindered by the solvated amine. Like Mark I'd expect the chlorophenyl not to compete in terms of reactivity in the substitution.

@edwintse @alintheopen I have a hazy memory of someone trying a coupling like this and getting a byproduct suggesting an intramolecular cyclisation, in other words this as the danger byproduct here 

![nboc byprod](https://user-images.githubusercontent.com/4386101/28529176-38f0b8f0-70d3-11e7-98e7-775b76d505f5.png)

but am I thinking of the protected diol you were using once, Alice?

**Comment by MFernflower** [comment]
Dr.Todd: where would the ketone oxygen come from since they are using
phenylalaninol? Are BOC groups really this prone to forming cycles?

**Comment by mcoster** [comment]
@mattodd That's a really good point, indeed we've seen that type of oxazolidinone formed in other situations with _N_ -Boc compounds with neighbouring alcohols. We might need to have a backup plan at the ready...

@MFernflower The alkoxide can intramolecularly attack the Boc carbonyl to give a tetrahedral intermediate that then loses _tert_-butoxide.

**Comment by MFernflower** [comment]
@mcoster PMB should be a suitable replacement for BOC should the need come but I cannot seem to find a commercial source of PMB protected alcohol

**Comment by drc007** [comment]
@mcoster @mattodd @MFernflower Might be worth trying the displacement with the unprotected amino alcohol. Alkoxide would be less hindered and more nucleophilic?

**Comment by mcoster** [comment]
Thanks for the valuable discussion @drc007. Hmm.. my thinking has gone full circle on this. I saw from Joanna Ubels' ELN that the coupling had been tried with the unprotected amino alcohol and failed, so started thinking of protecting the amine. Yes, I agree, the alkoxide should be less hindered and more nucleophilic, and there's plenty of lit. precedent for this type of reaction with chloroheteroaromatics without protection... I think we'll re-investigate the unprotected phenylalaninol before going down the route of a protected compound.

**Comment by mcoster** [comment]
Side issue - the GU project students have been having trouble with the [OSM LabTrove-based ELN](http://malaria.ourexperiment.org/griffith_uni_mcoster). Recently, one student found that his experiment was posted under another student's name/account while he was signed in under his own account, while others are unable to log in. Have others enountered similar problems?

**Comment by MFernflower** [comment]
Couldn't you use a similar system to what @MedChemProf used?

**Comment by mcoster** [comment]
Morgana finished working on this project in October. She was able to synthesise the chloro 4-(difluoromethoxy)triazolopyrazine, and to do a model nucleohilic aromatic substitution with 2-phenylethanol, however, she did not have enough time to fully purify or characterise that compound. Issue closed.
