### ISSUE TITLE
Synthesis of OSM-S-412

### ISSUE THREAD

**Issue by david1597** [OpenSourceMalaria/OSM_To_Do_List#525]
Hi All,

My name is David Smith and I have joined the project this week, working as a postdoc in Mat Todd's lab at The University of Sydney.

I'm starting with the synthesis of OSM-S-412 (MMV1557865). This was the compound which was previously produced biosynthetically (#513) with potency of 9 nM. We need more of this compound to evaluate further. 

I propose the route below. A negative is that there are a large number of steps. Positives are that we have access to the starting material, and by using the benzyl protecting group twice, only one deprotection step is required at the end.

Any thoughts or comments would be appreciated.
![plan for osm-s-412](https://user-images.githubusercontent.com/30584472/28857995-dc0fabb8-7790-11e7-8699-edafb8adba01.jpg)

**Comment by mcoster** [comment]
Hi @david1597, Nice! Hope it goes well. I was contemplating this the other day. Would you consider _C_-arylation of diethyl malonate as an alternative route to your diethyl 2-arylmalonate, eg. [A General and Mild Copper-Catalyzed Arylation of Diethyl Malonate. Edward J. Hennessy and and Stephen L. Buchwald* Organic Letters 2002 4 (2), 269-272](http://pubs.acs.org/doi/abs/10.1021/ol017038g)

A bit more convergent and maybe more analogue friendly?

Also:
You probably need a stronger reducing agent than NaBH<sub>4</sub> to reduce the esters, eg. LiAlH<sub>4</sub>, LiBH<sub>4</sub>, DIBAL.
It's often hard to get better than 50% yields from mono-benzylation of diols - formation of the benzylidene acetal, followed by redn with DIBAL is an alternative.

**Comment by drc007** [comment]
Do you need to protect the diol? I suspect it would only react once in the displacement?
![image](https://user-images.githubusercontent.com/7080516/28864555-d39b731c-7764-11e7-9621-32a5a519efaa.gif)
Is commercially available

**Comment by MFernflower** [comment]
I wonder if you could (provided you have time) produce a prodrug of this compound? (coupling the phenol functionality via Williamson with ethylchloroformate to form a carbonate?) @david1597

**Comment by david1597** [comment]
Great - thanks everyone! Really useful to have comments so quickly - based on the above I have changed the proposal to the one below.

@mcoster @MFernflower I now plan to use that Cu method, it was also suggested by another postdoc here in our group. Thanks.

@mcoster The benzylidene acetal route looks a lot neater - this is also now incorporated. 

@drc007 I'm not sure on the diol protection...I was following a similar route that @edwintse used to make the parent MMV693155. When I get to that stage, I'll try a small-scale on the diol and see if I can do it directly on the diol. I planned to avoid the commercially available compound you indicated as the removal of the methyl ether group would require more harsh conditions in the final step.

@MFernflower Sure! I can do the prodrug at the end.

![updated plan for osm-s-412](https://user-images.githubusercontent.com/30584472/28901996-8300a9d2-783f-11e7-8978-bc0684603bf0.jpg)

**Comment by MFernflower** [comment]
Chris Swain (@drc007) suggested that we do not use carbonate's for prodrugs and instead use an amino acid based approach (like a glycine ester of the phenolic functionality) to increase solubility

**Comment by MFernflower** [comment]
@david1597 Here is another possible molecule to bring up with Dr.Todd  
![transposedalcohol](https://user-images.githubusercontent.com/3164942/29395981-cfc119ca-82e2-11e7-91e4-15a212c88278.png)

**Comment by david1597** [comment]
Yep, it's a good idea! Coincidentally, @edwintse and @mattodd discussed this just yesterday, and @edwintse has already commenced synthesis of the similar molecule below.

![untitled](https://user-images.githubusercontent.com/30584472/29396679-903bc8ca-835c-11e7-8041-473a26ef3b37.jpg)

**Comment by mattodd** [comment]
Yes. That idea was literally less than 24 hours old, so had not yet made it here. The extended chain in @MFernflower 's suggestion is not so easy to come by as the symmetrical diol. So let's start with that.

**Comment by cdsouthan** [comment]
This all sounds  great.  JFTR, as  mentioned in https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/533 this OSM-S-412 replenishment tasks offer great opportunity to rigourously test reproducability.   At the risk of mentioning the obvious, be careful not to completely "run out" of 412 (do MMV have any left?). This means we then have the chance to compare old-vs-new,  not only for the identical NMR and suchlike but also to assay them both side-by-side.

**Comment by david1597** [comment]
@cdsouthan The SMILES and InChIs are in the master list next to OSM-S-412. Do you mean locating them here or elsewhere? Apologies if I have misunderstood, I'm still relatively new to the various systems we have.

**Comment by david1597** [comment]
This compound was included in the recent shipment to Dundee (OpenSourceMalaria/Series4#10 ). 

I'm currently repeating the final hydrogenation step to get more material to ship for other testing, should it's potency is confirmed. For some reason the yield was really poor from the first benzyl deprotection attempt and a lot of starting material was recovered.

**Comment by mcoster** [comment]
Basic/coordinating nitrogens, such as pyridines and related heterocycles, poison Pd catalysts. Ways to minimise this include:
1. Use hydrogen bonding solvent, eg. EtOH (you probably already are)
2. Use AcOH as solvent or co-solvent
3. Add 1 equiv. HCl

**Comment by david1597** [comment]
@mcoster Thanks for the tips for the Bn deprotection - I never got back to you to say it worked. Already was in EtOH, but as you suggested a 50/50 mix of EtOH and AcOH  worked better. Although the OSM-S-412 has just been made via a different route  (OpenSourceMalaria/Series4#23) I have other compounds ready for debenzylation so will continue with this method. Thanks :)

**Comment by david1597** [comment]
Closing this issue.

OSM-S-412 has been successfully synthesised - see OpenSourceMalaria/Series4#23.
