### ISSUE TITLE
Progress on furan

### ISSUE THREAD

**Issue by mbhebhe** [OpenSourceMalaria/OSM_To_Do_List#539]
Hello everyone! I am Mathamsanqa Bhebhe (Tha), one of Matthew Todd's PhD students working on OSM Series 3. So far I have managed to synthesise OSM-S-106. A large number of different analogues of OSM-S-106 were been previously synthesised by changing the different substituents on the amino thienopyrimidine core and that drastically changed the potency for the worse. I am currently working on the furan version of OSM-S-106. The core is being altered to see if that will worsen or improve the drug's potency.
I've had a few hiccups but I have managed to synthesise the molecules. Currently only 4 steps away from making the target molecule.
Here is my [ELN](https://au-mynotebook.labarchives.com/share/Tha%2520OSM%2520Series%25203/MjAuOHwyNzA2OS8xNi9UcmVlTm9kZS8zNTExOTk0NjU0fDUyLjg=)

![image](https://user-images.githubusercontent.com/26862286/30470837-b4ed88f4-9a39-11e7-8ae3-f713c1270dc3.png)

**Comment by MFernflower** [comment]
Link to your eln?

**Comment by edwintse** [comment]
Hey @mbhebhe, I'm not sure if you've come across the route I've drawn out below, but it might be a more efficient way of getting to your key furo[3,2-_d_]pyrimidine core (saves 2 steps) and could be easier to do. The only no so great reagent is H2S (g) but you might be able to use other reducing conditions. The final cyclisation was done on a substrate that contained the group of interest so it should work. Then it would just be bromination and Suzuki coupling

![tha furan](https://user-images.githubusercontent.com/18062981/30526306-1ec37a30-9c5c-11e7-8717-3df7c4301406.jpg)

**Comment by mbhebhe** [comment]
@MFernflower link to ELN is now on there.
@edwintse hadn't come across this route before. Should be able to use other reducing conditions. Don't know about brominating with the amine already there because I think Ryan is struggling with doing that on the thiophene ring. But it will be worth a try though, thanks!

**Comment by MFernflower** [comment]
Interesting paper detailing selective conversion of azides to amines: https://www.researchgate.net/publication/240859013_Selective_Reduction_of_Anomeric_Azides_to_Amines_with_Tetrathiomolybdate_Synthesis_of_b-D-Glycosylamines

@edwintse

**Comment by mbhebhe** [comment]
Last year I tried reducing an azide to an amine on one of my sugars and I failed, but I can try again using SnCl2:  https://doi.org/10.1016/S0040-4039(00)84275-6

**Comment by MFernflower** [comment]
Looks great! - The only thing I would do different from that paper would be to use isopropanol instead of methanol as the solvent @mbhebhe

**Comment by mbhebhe** [comment]
Hi all, I have been having trouble with purifying MNB14, I have made it but my attempts at purifying it gives low yields. I need this reaction to give me more product as I am still a few steps away from the target molecule. The problem is that MNB14 is polar and dissolves in water and in formamide (reagent/solvent). So doing an aqueous-organic partitioning during workup does not help. 
Formamide and ammonium formate have been used to cyclize the thiophene analogue and the product precipitates out overnight, and is also insoluble in water.
Purifying by flash chromatography does not separate MNB14 from the formamide. Triturating with dichloromethane gives pure product but gives a low yield.

- The product and formamide are both miscible in acetonitrile, water, methanol, THF (ammonium formate crashes out), acetic acid and ethyl acetate
- The product and formamide are immiscible in dichloromethane, diethyl ether and dioxane
- product does not dissolve but formamide does in acetone and IPA (only works for pure product and does not work or works slightly for the reaction mixture)
- I tried applying the azeotropes for DMF on formamide: 1) heptane and DMF, formamide is immiscible in heptane. 2) 26% acetic acid in DMF, formamide is miscible in acetic acid but mixture won't come off the rotavap

[Link](https://au-mynotebook.labarchives.com/share/Tha%2520OSM%2520Series%25203/MTEwLjV8MjcwNjkvODUvVHJlZU5vZGUvMjU2MzQwMTk0fDI4MC41
) to my attempts
[Link](https://au-mynotebook.labarchives.com/share/Tha%2520OSM%2520Series%25203/MTI2LjEwMDAwMDAwMDAwMDAxfDI3MDY5Lzk3L1RyZWVOb2RlLzMzMDc2MzY3Njh8MzIwLjA5OTk5OTk5OTk5OTk3
) to my characterisation (just waiting on 13C and HRMS)

Anyone ever worked with formamide before? How can I remove it? How do I overcome this problem?
If this does not work, I can make the furan analogue by using the route suggested above. But we don't know if the bromination will be successful, might need to protect the amine.

Thanks

**Comment by mcoster** [comment]
Volatility is your best differentiator. Do you have access to a good, eg. below 0.1 mmHg, vacuum pump? You could stir under vacuum, even with some heat. Alternatively, do you have access to a freeze drier? Direct freeze drying or freeze dry from water.

**Comment by drc007** [comment]
There is a page of workup tricks here http://chem.rochester.edu/~nvd/pages/solvents.php?page=solvent_workup

**Comment by mcoster** [comment]
I don't think any liquid-liquid extraction will cut it in this case. Find yourself a good freeze dryer!

**Comment by PBCranwell** [comment]
Have you tried scavenging the formamide out using a resin of some sort? I would suggest doing your work-up as usual, to get the crude material in EtOAc/DCM (DCM may be better but it depends on solubility) then add some polymer-supported amine resin (PS-BZA is good; https://www.sigmaaldrich.com/content/dam/sigma-aldrich/docs/Aldrich/Brochure/al_chemfile_v4_no1.pdf). What you really need to trial it is to find a group who do flow chemistry (I know some people at Melbourne who may be able to help...Alice is also well-connected). 

Stir the reaction with your resin for a few hours, TLC it if the formamide shows, filter and remove solvent. As a hint, wash your resin before use to remove any gunk from it (bitter experience showing here...)

I dont think the BZA would mess with your ring system, but there is a possibility that the formamide isn't electrophilic enough....worth a try if you are desperate!! I used it successfully for pesky PMB deprotections when I couldnt remove the p-anisaldehyde by FCC.

**Comment by mcoster** [comment]
It's great that there's so many suggestions! Just want to bear in mind that amides are really different beasts to aldehydes - the former are extremely unreactive towards nucleophiles. An amine resin won't meaningfully interact with formamide.

Formamide has a boiling point of 210 deg C at atmospheric pressure. If you use a pressure temperature nomograph (Aldrich has one), you can estimate its boiling point at a lower pressure. A half decent rotary vane pump will go below 1 mmHg, and a well maintained one, much lower. At these pressures, the estimated boiling point for formamide is below room temperature. So, if you're patient and have sufficient surface area or efficient mixing, it should be removed under vacuum.

In my institute, the natural product chemists use freeze dryers to recover samples from mixtures that can contain DMSO, DMF, TFA and ammonium formate. In my own work, I've removed multigram quantities of 1,3-propanediol (b. pt. 213 deg C) from a product by stirring the mixture (stirrer bar) in a round bottom flask under 'high vacuum' with gentle heating (40 deg C) for a couple of days.

**Comment by mbhebhe** [comment]
Thank you for the many suggestions, I will look into them and let you know how they go!

**Comment by MFernflower** [comment]
@mbhebhe Might I recommend a modified version of Mark's technique? Instead of stirring would it be possible to use sonication? Also, you could probably get away with like 60 C as related compounds like guanine decompose at about 360 C so you should be okay at 60 methinks

**Comment by mbhebhe** [comment]
We struggled with separating the product from the formamide so stopped the traditional S3 method and  moved on to the synthetic route suggested by Ed. 
I have successfully done the first two steps ([MNB22](https://au-mynotebook.labarchives.com/share/Tha%2520OSM%2520Series%25203/MTc4LjF8MjcwNjkvMTM3L1RyZWVOb2RlLzMyMjk0NTExODV8NDUyLjA5OTk5OTk5OTk5OTk3), [MNB25](https://au-mynotebook.labarchives.com/share/Tha%2520OSM%2520Series%25203/MTkzLjcwMDAwMDAwMDAwMDAyfDI3MDY5LzE0OS9UcmVlTm9kZS8xNDIyNDM0NjI1fDQ5MS43)). We can try the red route or the blue route to synthesise OSM-Furan. The blue route can be the alternative if brominating the cyclized furan is difficult. 
![image](https://user-images.githubusercontent.com/26862286/38075019-8dfaad12-337c-11e8-8f8b-68ff5b2c416b.png)

**Comment by drc007** [comment]
I think there is an error in your scheme, the nitrile should be directly attached to the furan ring.

**Comment by MFernflower** [comment]
Closing this issue see cross ref to https://github.com/OpenSourceMalaria/Series3/issues/10 

All pertinent info now in google doc https://docs.google.com/document/d/1JvSmlYWxe6nW5c5ue0qlYZay7WwUyBk2i7ZhI8UMTME

**Comment by mattodd** [comment]
Fine to close, but @mbhebhe please ensure that the suggestions made above (techniques and literature suggestions) are not wasted, and are incorporated somehow, **alongside attribution** (who made the suggestion). Any research report needs a brief description of possible solutions to problems even if those solutions were not attempted, so save others having to rediscover them in the future and to show that you've considered them critically.

Same applies to suggestions made in OpenSourceMalaria/Series3#10

Thanks for installing the DCNYS link @MFernflower

**Comment by MFernflower** [comment]
![carbamate](https://user-images.githubusercontent.com/3164942/51291663-e7407380-19d5-11e9-9bd9-317900991683.png)

Came across two interesting methods of carbamate cleavage @mbhebhe Perhaps they will be of use to you?

**Comment by mbhebhe** [comment]
Thanks, I will have a look
