### ISSUE TITLE
Photochemical possibilities 

### ISSUE THREAD

**Issue by MFernflower** [OpenSourceMalaria/OSM_To_Do_List#560]
I found this webpage that details a few interesting photochemical reactions for anybody who is interested in applying this type of chemistry to the OpenSourceMalaria project

http://www.hepatochem.com/sci-update/photoredox-box-setup/

The catalyst used: https://www.sigmaaldrich.com/catalog/product/aldrich/747793?lang=en&region=US

@maratsydney

**Comment by maratsydney** [comment]
Thanks @MFernflower, interesting chemistry.

**Comment by MFernflower** [comment]
A light like this should be able to carry out most of the reactions:
https://www.bulkreefsupply.com/kessil-a360n-tuna-blue-led-aquarium-light.html

Is the photochemical approach going to be tried sometime this year?
@maratsydney

**Comment by MFernflower** [comment]
Closing this issue - @mcoster feel free to make a post when your student is ready to attempt synthesis

**Comment by mattodd** [comment]
To avoid orphaning, link installed on [wiki on new LSF page](https://github.com/OpenSourceMalaria/Series4/wiki/Late-Stage-Functionalisation) that will eventually contain @ConorGraham 's work on this area, coming shortly.
