### ISSUE TITLE
Should OSM go for the Cochrane REWARD prize?

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#563]
The [Cochrane REWARD prize](http://www.cochrane.org/news/apply-cochrane-reward-prize-reducing-waste-research) is framed like this:  "An estimated $170 billion of research funding is wasted each year because its outcomes cannot be used. The waste occurs during 5 stages of research production: question selection, study design, research conduct, publication, and reporting. Much of this waste appears to be avoidable or remediable, but there are few proposed solutions. To stimulate and promote research in this area, Cochrane announces the Cochrane-REWARD prize. " 

[Application form](http://www.cochrane.org/sites/default/files/public/uploads/rewardprize_2018.pdf) requires:

1. Describe the initiative and how it has addressed research waste in at least one of the 5 stages of research (questions, design, conduct, publication, reporting) in the area of health (500 words max).

2. Describe any (pilot) data showing how the initiative has lowered research waste (500 words max).

3. Describe how the initiative might potentially be scaled up (250 words max).

4. Provide a justified estimate of the potential reduction in research waste that the initiative might achieve (250 words max)

Attach testimonials, photographs, news clippings, letters of support and similar material to support the submission/nomination.

It seems to me OSM is an excellent candidate for this. We would need to identify specific cases where OSM has reduced research waste. An example would be cases where people have not pursued something because someone else has already explored that avenue, where the relevant data are contained in OSM's online infrastructure and not in a formal publication. If we can identify some clear examples (anyone?) we can then extrapolate to a description of what would happen if OSM were to scale up. 

This issue is to call for thoughts on this, and whether we should apply, more generally. Deadline May 15th.

**Comment by cdsouthan** [comment]
It would seem we have little to loose, even if the questions are a bit of challenge.  Scale up seems the easiest case to make (e.g. take on several purified targets?) 

It could be argued  we have run the project quite cheaply ipso facto > less waste.  This would include saving a million by not needing an HTS,  not breaking the bank on reagent purchases, and of course a lot of gifted (in both senses of the word)  FTE time

Interestingly,  I have never seen Med Chem project costings per se in terms of say $/FTE hours per-lead. Does  anyone know of such estimates?    Then we could calibrate ourselves against such

**Comment by mattodd** [comment]
Hi all. The deadline approaches for this (Tuesday next week). A draft of the text needed for the Nomination Form is [here](https://github.com/OpenSourceMalaria/Series4/tree/master/Applications%20for%20Grants%20etc/2018%20Cochrane%20Reward%20Prize), along with some sample extra materials we're allowed to submit. Requirements:

1) If people have time, I'd value edits (both small and large) of the text in the nomination form. I may have missed something important, or mischaracterised something (have had a head cold all week...). Small things can be commented on below. Big things can be tracked changes in Word docs that are pasted into comments below or uploaded manually to the same repo. We're on the word limit for each of the 4 sections.

(note in particular my guesses of the size of cost savings are necessarily speculative)

2) The supporting docs are in response to this: "Attach testimonials, photographs, news clippings, letters of support and similar material to support the submission/nomination". I'd like to include more than we are doing, so any suggestions there gratefully received. I've not yet addressed the "letters of support" for example, but will attempt to do this.

3) I will look into a possible nominator.

**Comment by MedChemProf** [comment]
@mattodd I just uploaded a version 2 of the Nomination Form with all of my edits. I made suggested changes throughout the document, so I have turned on Track Changes for you to see my edits. The word count may need some adjustment, but I thought it would be best for you to see my thoughts prior to accepting the changes. I added a bit more to the efficiency gains in training of future scientists also.

**Comment by mattodd** [comment]
Version 4 of the Nomination Form [uploaded](https://github.com/OpenSourceMalaria/Series4/tree/master/Applications%20for%20Grants%20etc/2018%20Cochrane%20Reward%20Prize). We have a nominator and 2 recommendation letters so far - I can't share these publicly because I don't have explicit approval from the relevant employers (could get, don't have time). Any last-minute suggestions for tweaks to the text welcome, or suggestions for extra 3rd-party items we could submit (blogs, news items) that testify that open source can reduce waste.

Submitting in 24 hrs.

**Comment by mattodd** [comment]
Version 4 still most up to date version - thanks to @david1597 and @alintheopen for suggestions. Expanded list of supporting items and updated costs estimates of drug dev failure. All word limits hit. Just waiting on one recommendation letter.

**Comment by mcoster** [comment]
Sorry, I'd _really_ like to properly contribute to this, buuut, [insert usual comments about lack of time...] I don't know whether it fits nicely into the application, but one recent advancement we have made is to replace an undergraduate prac with experiments that lead to a valuable OSM intermediate. The old experiment resulted in ~ 20 g of a molecule that we had no use for and actually sent for disposal. The trial of the OSM undergrad prac has resulted in ~ 10 g of the difluoromethoxyphenyl substituted chlorotriazolopyrazine at the half way point and is estimated to produce a further 10 g by 1 June. All of which will be used by project students to make new OSM analogues in near future. Furthermore, the undergrad students have met the same or better learning outcomes vs previous years and there is (anecdotally) greater interest and engagement with this "living" undergraduate prac.

**Comment by mattodd** [comment]
Thanks Mark, it's an important point that we kind of address in the limited space we have when we say "Student crowdsourcing has been undertaken extensively (Australia, UK, US). Research waste is reduced by students generating outputs that are used in a real-world project, rather than generic laboratory outputs that are discarded" . Nuance is tricky when the word count is low, but I wanted to convey something of what you mention. Each instance is a relatively small saving on waste (from the perspective of a full drug dev program) but as a *scalable model* it would be highly significant, not least to get people realising (with great examples like yours) that uni pracs can achieve real, meaningful things.

**Comment by cdsouthan** [comment]
Apols  preparing for GtoPdb and BPS meetings in Edin but  I can pop an idea out while accepting there may be no room for it

Since we declare ourselves as being free of the tyranny of novelty for IP protection this brings a massive cost saving.  AWAK pharma companies will make and test 100s-1000s of analogues to push out into novel structures and claim the chemical space around each of their series as wide as they can. Note  also this results in the 18-month informatics shadow for the data.    We don't need to do this (although it was a bit of a paradox that S4 was novel space).

**Comment by drc007** [comment]
@cdsouthan I'm not sure this is true, I don't know of any pharma company that devotes significant chemistry resources simply to provide patent protection. Chemistry resources are simply too valuable to waste on such efforts. It may be that in certain times several parallel efforts are pushed forward and some subsequently dropped, but this is simply done at risk to shorten timelines.

**Comment by cdsouthan** [comment]
A moot point. I don't think the 1000s  of  data-supported exemplifications 
https://www.bindingdb.org/bind/ByPatent.jsp
represent shortest path to optimisation.  Note also they all push for novelty (by definition) which we dont have to

**Comment by drc007** [comment]
Interesting link. But most of those patents only have a few hundred examples. We already have nearly 700 molecules in the OSM spreadsheet.

**Comment by mattodd** [comment]
Thank you everyone for your inputs and thoughts. Application submitted just now - let's see how we go. [A note back-referencing this Issue](https://github.com/OpenSourceMalaria/Series4/blob/master/Applications%20for%20Grants%20etc/2018%20Cochrane%20Reward%20Prize/Relevant_GHI) added to prevent orphaning. Closing
