### ISSUE TITLE
What Open Source Malaria is Doing on World Malaria Day 2018

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#564]
To celebrate [World Malaria Day 2018](https://www.worldmalariaday2018.org/) we are on this page highlighting what Open Source Malaria (OSM) contributors are doing to fight this terrible disease.

We're all united in our wish to accelerate basic research towards eliminating malaria, and to work on the problem in a way that avoids secrecy. That way we can share our work, learn from each other quickly and involve the widest possible community of experts. Contributors have been asked to write a few words below to describe something they are currently working on, and to share a favorite picture of something related to their work.

Please feel free to link out to this page on other platforms to spread the work - _if you're reading this and want to be involved, you can be!_

**Comment by mattodd** [comment]
I'm Matthew Todd. A few years ago I founded [Open Source Malaria](http://opensourcemalaria.org/) with pioneers at the [Medicines for Malaria Venture](https://www.mmv.org/). I love working with the diverse people who comprise the OSM consortium. By freely giving their time and ideas to tackling this problem they are accelerating the research significantly. Together we've looked at four series of molecules ([we published the first](http://pubs.acs.org/doi/full/10.1021/acscentsci.6b00086)). The fourth series [includes molecules that are active in an animal model](https://github.com/OpenSourceMalaria/Series4/wiki). If we can show these molecules are effective enough, we will be able to get an open source-derived molecule into clinical trials, _which would be the first time that has ever happened_. If we can demonstrate such a precedent, of an alternative system, then drug discovery will change for good.

One thing I'm currently working is the financial/legal way in which an open source drug can reach patients by scoping out [how an open source pharma industry might look](http://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1002276), and thinking about [ways of funding it, on scale](https://intermolecular.wordpress.com/2015/05/29/funding-open-source-drug-discovery/). Here's a picture of the Sydney heart of OSM - Ed, David and Marat (Series 4) and Tha (Series 3).

![osmers april 2018](https://user-images.githubusercontent.com/4386101/39100949-b900b328-46d5-11e8-9b59-bf578dc0aafb.jpg)

**Comment by drc007** [comment]
I'm happy to contribute to [OSM](http://opensourcemalaria.org/) providing MedChem insight and computational chemistry support.  Also work with RSC BMCS to provide exposure to the great work carried out in the area including the Cambridge MedChem Meeting NTD session that can be viewed online here [Cambridge MedChem Meeting NTD session](https://youtu.be/XLOCFrjrMEY)

**Comment by cdsouthan** [comment]
I have been helping out with OSM since ~ 2012.  My main involvement is around cheminformatics in general and [databases](https://www.ncbi.nlm.nih.gov/pubmed/29451740) in particular.  My day job is working for the

**Comment by MedChemProf** [comment]
My name is Chase Smith and I am an Associate Professor of Medicinal Chemistry in the School of Pharmacy at MCPHS University (Worcester, MA, USA). The PharmD students working in my lab have been very enthusiastic in contributing their time and effort toward helping advance the goals of the Open Source Malaria ([OSM](http://opensourcemalaria.org/)) project. Early on in our work, we focused on initiatives to synthesize OSM Series 4 analogs with improved solubility characteristics as well as the development of synthetic methodologies to access a previously missing set of Series 4 compounds known as the [reversed amides](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/487). The group is currently in the planning stages to target compounds that would be considered Scaffold Hop’s of the OSM Series 4 analogs. We would welcome any questions or offers on collaboration. The following link leads to a repository of all of our laboratory work and results: [MCPHS Electronic Laboratory Notebook](https://mynotebook.labarchives.com/share/MCPHS%2520MedChem/MzUxLjB8MzY3Ny8yNzAvVHJlZU5vZGUvNDA0ODg3Njc4OHw4OTEuMA==).
![mcphs_image1](https://user-images.githubusercontent.com/14179120/39148402-3775ac8e-470a-11e8-8742-d89ca53bf21e.jpg)
![mcphs_image2](https://user-images.githubusercontent.com/14179120/39148403-377fcf20-470a-11e8-8802-1c1844b8e896.jpeg)

**Comment by holeung** [comment]
I am [Ho Leung Ng](holeungng.com). I am a professor of biochemistry and biophysics at Kansas State University. I contribute to computational chemistry and structural biology efforts to OSM. I am particularly interested in docking, applications of machine learning to chemistry, and predicting targets for bioactive molecules. We are testing OSM Series 3 compounds for activity against Plasmodium kinases.

![pfatp4_model](https://user-images.githubusercontent.com/10951570/39148802-da7eb4b4-4702-11e8-9271-dc52ef0afe44.png)
![lab photo1 2 26 18 small](https://user-images.githubusercontent.com/10951570/39148867-05dc2114-4703-11e8-9107-8011eba1f1c3.jpg)

**Comment by edwintse** [comment]
I'm Edwin Tse, one of Mat's PhD students here at the University of Sydney. I've been working on the OSM project since 2016 on a number of areas targeting unexplored SAR. Most recently, I have been making a range of phenyl bioisostere derivatives (notably the cubane and the carborane) and have also been tackling some of the compounds from the [Desirable Compounds Not Yet Synthesised](https://github.com/OpenSourceMalaria/Series4/wiki/Desirable-Compounds-Not-Yet-Synthesised) section of the project (such as the [hERG Evador](https://github.com/OpenSourceMalaria/Series4/issues/22) and currently the Oxazole).

![untitled wiley-15](https://user-images.githubusercontent.com/18062981/39160771-9dc510dc-47b0-11e8-8544-414fe4a4ce5b.jpeg)

**Comment by mcoster** [comment]
I'm Mark Coster. I am an Associate Professor in Chemistry at Griffith University in Brisbane, Australia. My group and I have been contributing to Open Source Malaria (OSM) for almost a year now, and [it has been a very rewarding experience.](https://github.com/OpenSourceMalaria/Series4/issues/15)

Just this week, we are rolling out a new undergraduate experiment in a 3rd year Advanced Organic Chemistry subject that I run. Previously students undertook an experiment designed to teach them some keys skills in organic chemistry, but I felt that the skills being taught needed updating and it was frustrating that the compound they prepared did not have a subsequent use after the students had left. We have now replaced that with an experiment where the ~ 100 students prepare a substituted triazolopyrazine structure of interest in the current [Series 4](https://github.com/OpenSourceMalaria/Series4) efforts of OSM. Along the way, my students will learn key synthetic chemistry techniques applicable to drug discovery research, such as reaction monitoring by thin layer chromatography (TLC), purification by flash column chromatography and structure elucidation by NMR spectroscopy. Best of all, the material they produce is a valuable intermediate in the synthesis of new anti-malarials by the OSM initiative. This material will be used by undergraduate project students at Griffith University and will be made available to other groups elsewhere.

![image](https://user-images.githubusercontent.com/28282596/39164416-c0233264-47c2-11e8-94a8-30bac57a0099.png)

Speaking of project students, this trimester at Griffith University, I am supervising 8 undergraduate project students, each [tasked with making a different, new Series 4 compound for screening against _P. falciparum._](https://github.com/OpenSourceMalaria/Series4/issues/28) As we enter the 7th week of their efforts, the students have run their key reaction, purified the product(s) and now wait excitedly for an opportunity to acquire NMR data to elucidate the structures of their compounds!

![20180308_131444](https://user-images.githubusercontent.com/28282596/39164343-6b66dec4-47c2-11e8-905c-3902a5773cf5.jpg)

**Comment by mbhebhe** [comment]
Hi my name is Mathamsanqa Bhebhe (Tha). I am one of Mat's PhD students at USyd. I am currently working on [Series 3](https://github.com/OpenSourceMalaria/Series3). 
So far in Series 3 they played around with different substituents on the thiophene core and it decreased the potency of the drug. So at the moment I am trying to change the scaffold of OSM-S-106 from the thiophene core to the [furan](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/539), [pyrrole](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/557) and [purine](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/558), to see if that will improve the potency of the original hit (OSM-S-106).
![image](https://user-images.githubusercontent.com/26862286/39164825-d6135322-47c4-11e8-9398-be45adf35e1d.png)
![image](https://user-images.githubusercontent.com/26862286/39165014-b1eda668-47c5-11e8-92e7-b0cb75235235.png)

**Comment by david1597** [comment]
Hi, I'm David Smith and I am a postdoc at Sydney University. I joined OSM nine months ago where my primary focus has been as a synthetic chemist. I came onto the project around the time that a [team](https://cen.acs.org/pharmaceuticals/drugDiscovery/Mixtures-liver-enzymes-improve-drug/96/i17) at Pfizer made a potent lead through a [biosynthesis](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/513). When I made what we thought was that compound in our lab, it [wasn't](https://github.com/OpenSourceMalaria/Series4/issues/24) potent! Turns out, we'd gone after the wrong compound. We know now what that structure is so I am currently going after that [target](https://github.com/OpenSourceMalaria/Series4/issues/36) and related compounds.

![image](https://user-images.githubusercontent.com/30584472/39165282-09eca106-47c7-11e8-90a6-7734817ffb77.png)

**Comment by MFernflower** [comment]
Most people know me as "Mandrake" but my real name is Anthony. I am a 20 year old PC gamer turned biochemistry nerd - I have been on and off with the OSM project for at-least 3 years or more. My main efforts include searching the known chemical literature for alternative synthesis methods and proposing compounds that have not been tested and/or use various seldom used bioisosteres/functional groups for the synthetic chemistry team to make real. 
![dddddd](https://user-images.githubusercontent.com/3164942/39169123-812d99c2-4764-11e8-9768-71998a17fe64.png)
![logp](https://user-images.githubusercontent.com/3164942/39169155-9dc011a0-4764-11e8-95ab-461bacd40433.png)

**Comment by MFernflower** [comment]
I'm pretty mutch the oddball here. I have no degree but was always interested in biochemistry.. I think I came across osm when trying to search for a unrelated malaria drug with a rather uncanny structure (aterolane) - after reading a bit i decided to join the project. When I started out I did not have a good grasp of drug design but have improved greatly as time has gone on

**Comment by mattodd** [comment]
Another super nice way to mark World Malaria Day by @maratsydney is over on OpenSourceMalaria/Series4#39 - the shipment of >20 brand new compounds to Dundee for blood stage potency evaluation.
