### ISSUE TITLE
Open Research Funding

### ISSUE THREAD

**Issue by drc007** [OpenSourceMalaria/OSM_To_Do_List#570]
@mattodd I guess you are aware of the WT Open Research Fund

https://wellcome.ac.uk/news/new-fund-support-groundbreaking-open-research

**Comment by mattodd** [comment]
Aware of it. Deadline 7th August. Upper limit of 50K GBP I think. Looks interesting and we should try to do something. I'm in transit and not terribly available. It would be very good if we could go in as OSM, and if people wanted to sketch out ideas here that might be within budget and scope. Delighted if someone else wanted to lead the application, and I can chip in when I can.

**Comment by drc007** [comment]
How about building a kinase inhibitor collection ? Not just for Malaria but all NTD.
