### ISSUE TITLE
Submission of a Review on Antimalarials

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#575]
@edwintse and @maratsydney have been reading up on the current malaria pipeline as part of their graduate studies. We had the idea recently of writing up some of this work as a useful, short review - a kind of _Field Guide to Malaria Medicines_. Ed came up with a really nice way to represent compound data graphically.

Anyway, within a short space of time we had an article that was looking complete. We just polished it a little and are nearly ready to submit. We realize, though, that this paper and its progress has not been shared, which was an oversight. It's not related to any of the Series OSM is looking at. But nevertheless.

So the paper is shared [here](https://github.com/OpenSourceMalaria/OSM_To_Do_List/tree/master/General%20Papers/2018%20Malaria%20Pipeline) in its current draft form. We're hoping to submit in the next 1-2 weeks. Any comments gratefully received. Small things or big. There are some little gaps in the compound data (marked with "?") and I intend to ask the relevant groups if they have those data to hand, since we couldn't find them in the lit. The supplementary info spreadsheet is also uploaded.

The emphasis of the paper is to summarize the hit to lead campaigns of the molecules in development. But we also needed to cover past and present medicines briefly to give the context. There's an emphasis on promising mechanisms of action.

It's going to _Malaria Journal_, and will be open access, obviously. The journal has kindly confirmed that they are fine with us posting it here before submission. ChemRXiv and other preprint servers don't seem to take reviews. So we're using OSM infrastructure (courtesy of Github) to run our own _preprint nanoserver_.

Ed and Marat have done a cracking job, but please don't hesitate to peer review here. Very happy to acknowledge peer review in the final article.

We were hoping that, following publication, this review could become the basis for a "living review" in a wiki style, i.e. a review that could be updated by the community continuously, perhaps with links to/from the MMV website, but we've not yet had that conversation with MMV or anyone else.

**Comment by mattodd** [comment]
Update: missing data now summarised as a spreadsheet [in the same place](https://github.com/OpenSourceMalaria/OSM_To_Do_List/tree/master/General%20Papers/2018%20Malaria%20Pipeline), including contact details taken from relevant papers. Will try to reach out to all these authors to pin down any remaining data if they are willing to share. Obviously if other people find these missing data, please say so below by commenting!

**Comment by holeung** [comment]
Very nicely done! This should be a valuable reference for years to come. I'll take a look at it. Please let me know if there is any way I can help.

**Comment by mattodd** [comment]
Update: Have written to corresponding authors asking for insight into missing data.
@cdsouthan yes a suitable and comprehensive mapping would be useful and we could use your help with that.

**Comment by cdsouthan** [comment]
Best of luck .....  JFTR my colleagues including Michael Spedding and Jane Armstrong (project leader) are impressed with the draft and the latter is x-checking what we don't have.  We hope to synch with our Jan release.   I assume the esteemed @edwintse and @maratsydney have ChemDraw files from which they can spawn SMILES and InChIs?

**Comment by holeung** [comment]
Some initial comments:

1. I would like to see more discussion of the potential mechanisms of action and resistance for the two most important drug classes, quinines and artemisinins. More insight into these areas may lead to new, better drugs. In addition, the mechanism of the artemisinins is still a mystery and scientifically intriguing.

2. There are many more active compounds being investigated that work by different mechanisms. For example, there are many protein and lipid kinase inhibitors that are being explored.

I can write something addressing these points if you would like.

**Comment by mattodd** [comment]
Thanks @holeung 

Well, the review is intended to be brief, meaning we're referencing out to larger studies related to MoA and mechanisms of resistance. @edwintse @maratsydney are there significant articles in the last few years that might bolster this part of the review for quin/art, or do you think we're covered?

Re other compounds - we've had to draw a line somewhere, otherwise we'll be discussing a lot of compounds, and we decided the line would be drawn at the clinical phase. So I think we're covering all compounds that have been in a clinical trial of some kind or which are scheduled for a trial. Obviously we link out to the MMV website which has a healthy selection of projects that are in an earlier phase of development. An article describing the landscape of targets that are the subject of more speculative R&D would be interesting, but could constitute an article in itself... Which we could think about.

**Comment by mattodd** [comment]
**Update**: have reached out to all people who have not yet responded to our request for data (many have, very kindly and promptly) and we'll give remaining folks till _Friday_ before we go ahead with organising submission. Data may not be available, or people may just be busy. Updated sheet of missing datapoints is available, as well as an updated draft of the review itself. I'll also ping folks at MMV, just to see if they'd like to proof/chip in.

**Comment by cdsouthan** [comment]
You can put me down as a formally suggested referee if you like.  Mind you I think I need a beer(s) pledge to get me in a good reviewing mood .....

**Comment by MFernflower** [comment]
One might question if it would be a good idea to do paper proofreading after a hearty session in the pub

**Comment by cdsouthan** [comment]
@edwintse @maratsydney do you have the  CDX files?

**Comment by edwintse** [comment]
@cdsouthan Sure do, any in particular?

**Comment by cdsouthan** [comment]
Not just yet, when my colleague gets round to triaging the paper we can pick up those for code names we don't have structures for.

**Comment by cdsouthan** [comment]
Much better idea,-  please prepare small data sheet with SMILES (generated from the CDXs) and the names or code numbers in the text.  This could go as Figshare supp dat for the paper?

**Comment by drc007** [comment]
I'd avoid any binary data format like .cdx, go for an plain text format, SMILES, SDF, MOL etc.

**Comment by cdsouthan** [comment]
Amen, yes - SMILES should do nicely :)  If there any round-tripping issues (almost certain to be a few) these will get picked up during the PubChem mapping

**Comment by mattodd** [comment]
@cdsouthan @drc007 Just to clarify what you're after here. All compounds in the paper in one chemdraw sheet saved as SDF or something equivalent? Do you want correspondence with compound numbering in the paper? If you can lay it out for us, it'll make it easier to get it right. Going to submit tomorrow, we hope, and we could include this file with the submission (to be posted at the journal) if that is eventually useful.

**Comment by cdsouthan** [comment]
Personally we at GtoPdb would be fine just with SMILES against anything that has a code number (i.e. roughly from Fig 6 onwards).  The compounds with established INN names don't need to go in supp data because they (on a good day) they will retrieve unequivocally from PubChem.

**Comment by cdsouthan** [comment]
We (at GtoPdb) would be fine with just a mapping sheet of SMILES against the code numbers   (i.e from Fig 6 onward and in bold in the text)  All the  INN names should map unequivocally into PubChem (on a good day) so we don't need them.

**Comment by mattodd** [comment]
Update: review submitted today. Thank you for all your advice and comments. Will let you know how it goes.
