### ISSUE TITLE
Target for Quinine identified

### ISSUE THREAD

**Issue by drc007** [OpenSourceMalaria/OSM_To_Do_List#578]
Worth a read, includes introduction on defining targets in Malaria.

http://stm.sciencemag.org/content/11/473/eaau3174

Quinine binds to PfPNP at low nanomolar affinity, suggesting a substantial contribution to its therapeutic effect. 

(Added by MFernflower: You can get a 3d view of the PfPNP-Quinine interaction via the PDB http://www.rcsb.org/3d-view/5ZNC?preset=ligandInteraction&sele=QI9 )

**Comment by MFernflower** [comment]
Very interesting!! OSM series five anybody? 😀

**Comment by mattodd** [comment]
Closing since added to Pipeline Review repo: OpenSourceMalaria/pipeline_living_review#2
