### ISSUE TITLE
MMV Call for Proposals - Deadline March 29th

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#579]
As @drc007 already mentioned in OpenSourceMalaria/Series3#12 and on his [blog](https://www.cambridgemedchemconsulting.com/news/index_files/ab9b8d1802e570728c7b25a9787aa115-358.html), MMV have a call for proposals, deadline March 29th.

Question: Is anything we're doing in OSM particularly relevant to this call? Please suggest below.

**Example**: If Series 3 really is hitting asparaginyl tRNA synthetase (OpenSourceMalaria/Series3#12), maybe we should request some support to pursue it further? The relevant criteria are:

"Novel chemical series with EC50<500nM (_yes_) and which have **one or more** of the following key features
A known, novel mechanism of action (_maybe_)
An inability to select resistant mutants in vitro (_no_)
Activity at more than one life-cycle stage (_no_)
A long half-life (ideally >4h in rodents) (_yes >4h in rat hepatocytes_) and confirmed in vivo efficacy (_not yet tested_)"

(Further support for Series 4 depends for the moment on values we need to get for clearance rate of OHOH compound - the subject of another issue.)

**Comment by MFernflower** [comment]
Would it be possible to get the results of @StuartRalph 's assay before the MMV deadline? Would they be okay with only two lab tests re target? @mattodd

**Comment by mattodd** [comment]
I think the pipeline is the other experiments which are already underway mentioned by @sottilie involving a protein synthesis assay and MIT/Sanger work outlines in https://github.com/OpenSourceMalaria/Series3/issues/12#issuecomment-458220293. I think @stuartralph would step in if confirmation is needed.

**Comment by MFernflower** [comment]
Thanks for bringing me up to speed @mattodd

**Comment by mattodd** [comment]
Closing since the deadline has passed. When there is greater certainty about the Series 3 mechanism of action, and if the MoA is novel, we will need to pursue funds for the work. Non-orphaned [here](https://github.com/OpenSourceMalaria/Series3/wiki/Funding-for-this-Series).
