### ISSUE TITLE
Are you interested in computer-designed molecules against PF (3D7 strain) growth inhibition?

### ISSUE THREAD

**Issue by UnixJunkie** [OpenSourceMalaria/OSM_To_Do_List#585]
The molecules are designed to be:
- lead-like
- easy to synthesize
- have uniq scaffolds
- non reactive

**Comment by UnixJunkie** [comment]
The QSAR model (scoring function for the designed molecules), is based on data released in this paper:
"Thousands of chemical starting points for antimalarial lead identification"
https://www.nature.com/articles/nature09107

**Comment by edwquim2026** [comment]
yes
