### ISSUE TITLE
Etica protocol Update

### ISSUE THREAD

**Issue by kevin-wad** [OpenSourceMalaria/OSM_To_Do_List#590]
Hi,
I'm Kevin Wad from Etica protcol. I posted here back in 2019: https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/582#issue-509470849

Just to keep you updated and inform you that Etica launched on april 17th 2022.
For reminder, Etica is the first blockchain for Open source medical research without intellectual property.
We are looking for researchers to help us.

website: https://www.eticaprotocol.org/
discord: https://discord.gg/CrTKpETKXc
reddit: https://www.reddit.com/r/Etica

Best regards

**Comment by mattodd** [comment]
Closing since not followed up.
